use std::fs;
use std::io::Write;
use std::path::Path;

pub fn create_file(path: &Path) -> fs::File {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).unwrap();
    }
    let mut file = fs::File::create(path).unwrap();
    writeln!(file, "// AUTO-GENERATED BY ferrumc-data-gen").unwrap();
    writeln!(file, "// DO NOT EDIT MANUALLY").unwrap();
    writeln!(file, "").unwrap();

    file
}

pub fn write_mod_file(output_dir: &Path) {
    let mut file = fs::File::create(output_dir.join("mod.rs")).unwrap();

    writeln!(file, "pub mod blocks;").unwrap();
    writeln!(file, "pub mod entities;").unwrap();
    writeln!(file, "pub mod items;").unwrap();
    writeln!(file, "pub mod mappings;").unwrap();
    writeln!(file, "pub mod packets;").unwrap();
    //    writeln!(file, "pub mod registries;").unwrap();
}
