# IP or hostname where the server will bind. Leave as 0.0.0.0 if you want it to be accessible from any IP.
host = "0.0.0.0"
# Server port (0-65535). Minecraft's default port is 25565, so you probably want to leave it as is.
port = 25565
# Message of the day. A random one will be selected.
motd = ["Welcome to the best server ever!", "Rust", "Good luck, have fun!"]
# Maximum number of players
max_players = 100
# How many network updates per second per user
network_tick_rate = 30
# World name to load
world = "world"
# Whether the server should validate players via the whitelist
whitelist = false
# Network compression threshold (can be negative). This decides how long a packet has to be before it is compressed.
# Very small packets may actually increase in size when compressed, so setting it to 0 won't be perfect in all situations.
# Set to -1 to disable compression.
network_compression_threshold = 64

# Database configuration
[database]
# Compression algorithm (brotli, deflate, gzip, zlib, zstd)
compression = "gzip"
# Path to the world database
db_path = "world"
# Compression level (0-22) for the database. Higher values mean less disk space but will take longer to read/write.
compression_level = 5
# Map size
# The max size of the database's memory map in GB. Basically you need this to be big enough
# to hold everything before it starts writing to disk. This isn't memory use though, it's just
# how much we can map into memory if needed, so you can set this to an insane number if you want,
# but it won't actually use that much memory, it'll just show up as virtual memory use.
# The default is 1TB, which should be more than enough for most worlds. Set this higher if you have a huge world.
map_size = 1_000
# The time to live for cache entries in seconds.
cache_ttl = 60
# How big the cache can be in kb.
cache_capacity = 20_000

whitelist = false