#[allow(unused_imports)]
use ferrumc_block_properties::*;
#[allow(dead_code)]
#[derive(Clone, Debug)]
pub enum ButtonBlockType {
    AcaciaButton,
    BambooButton,
    BirchButton,
    CherryButton,
    CrimsonButton,
    DarkOakButton,
    JungleButton,
    Lever,
    MangroveButton,
    OakButton,
    PaleOakButton,
    PolishedBlackstoneButton,
    SpruceButton,
    StoneButton,
    WarpedButton,
}
#[allow(dead_code)]
#[derive(Clone, Debug)]
pub struct ButtonBlock {
    pub block_type: ButtonBlockType,
    pub face: AttachFace,
    pub facing: Direction,
    pub powered: bool,
}
impl TryInto<u32> for ButtonBlock {
    type Error = ();
    fn try_into(self) -> Result<u32, Self::Error> {
        #[allow(unreachable_patterns)]
        match self {
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: true,
            } => Ok(9492u32),
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: false,
            } => Ok(9493u32),
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: true,
            } => Ok(9494u32),
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: false,
            } => Ok(9495u32),
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: true,
            } => Ok(9496u32),
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: false,
            } => Ok(9497u32),
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: true,
            } => Ok(9498u32),
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: false,
            } => Ok(9499u32),
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: true,
            } => Ok(9500u32),
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: false,
            } => Ok(9501u32),
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: true,
            } => Ok(9502u32),
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: false,
            } => Ok(9503u32),
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: true,
            } => Ok(9504u32),
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: false,
            } => Ok(9505u32),
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: true,
            } => Ok(9506u32),
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: false,
            } => Ok(9507u32),
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: true,
            } => Ok(9508u32),
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: false,
            } => Ok(9509u32),
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: true,
            } => Ok(9510u32),
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: false,
            } => Ok(9511u32),
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: true,
            } => Ok(9512u32),
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: false,
            } => Ok(9513u32),
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: true,
            } => Ok(9514u32),
            ButtonBlock {
                block_type: ButtonBlockType::AcaciaButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: false,
            } => Ok(9515u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: true,
            } => Ok(9612u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: false,
            } => Ok(9613u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: true,
            } => Ok(9614u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: false,
            } => Ok(9615u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: true,
            } => Ok(9616u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: false,
            } => Ok(9617u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: true,
            } => Ok(9618u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: false,
            } => Ok(9619u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: true,
            } => Ok(9620u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: false,
            } => Ok(9621u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: true,
            } => Ok(9622u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: false,
            } => Ok(9623u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: true,
            } => Ok(9624u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: false,
            } => Ok(9625u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: true,
            } => Ok(9626u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: false,
            } => Ok(9627u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: true,
            } => Ok(9628u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: false,
            } => Ok(9629u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: true,
            } => Ok(9630u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: false,
            } => Ok(9631u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: true,
            } => Ok(9632u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: false,
            } => Ok(9633u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: true,
            } => Ok(9634u32),
            ButtonBlock {
                block_type: ButtonBlockType::BambooButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: false,
            } => Ok(9635u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: true,
            } => Ok(9444u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: false,
            } => Ok(9445u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: true,
            } => Ok(9446u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: false,
            } => Ok(9447u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: true,
            } => Ok(9448u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: false,
            } => Ok(9449u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: true,
            } => Ok(9450u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: false,
            } => Ok(9451u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: true,
            } => Ok(9452u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: false,
            } => Ok(9453u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: true,
            } => Ok(9454u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: false,
            } => Ok(9455u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: true,
            } => Ok(9456u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: false,
            } => Ok(9457u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: true,
            } => Ok(9458u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: false,
            } => Ok(9459u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: true,
            } => Ok(9460u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: false,
            } => Ok(9461u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: true,
            } => Ok(9462u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: false,
            } => Ok(9463u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: true,
            } => Ok(9464u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: false,
            } => Ok(9465u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: true,
            } => Ok(9466u32),
            ButtonBlock {
                block_type: ButtonBlockType::BirchButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: false,
            } => Ok(9467u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: true,
            } => Ok(9516u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: false,
            } => Ok(9517u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: true,
            } => Ok(9518u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: false,
            } => Ok(9519u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: true,
            } => Ok(9520u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: false,
            } => Ok(9521u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: true,
            } => Ok(9522u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: false,
            } => Ok(9523u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: true,
            } => Ok(9524u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: false,
            } => Ok(9525u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: true,
            } => Ok(9526u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: false,
            } => Ok(9527u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: true,
            } => Ok(9528u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: false,
            } => Ok(9529u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: true,
            } => Ok(9530u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: false,
            } => Ok(9531u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: true,
            } => Ok(9532u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: false,
            } => Ok(9533u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: true,
            } => Ok(9534u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: false,
            } => Ok(9535u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: true,
            } => Ok(9536u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: false,
            } => Ok(9537u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: true,
            } => Ok(9538u32),
            ButtonBlock {
                block_type: ButtonBlockType::CherryButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: false,
            } => Ok(9539u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: true,
            } => Ok(20123u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: false,
            } => Ok(20124u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: true,
            } => Ok(20125u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: false,
            } => Ok(20126u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: true,
            } => Ok(20127u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: false,
            } => Ok(20128u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: true,
            } => Ok(20129u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: false,
            } => Ok(20130u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: true,
            } => Ok(20131u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: false,
            } => Ok(20132u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: true,
            } => Ok(20133u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: false,
            } => Ok(20134u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: true,
            } => Ok(20135u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: false,
            } => Ok(20136u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: true,
            } => Ok(20137u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: false,
            } => Ok(20138u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: true,
            } => Ok(20139u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: false,
            } => Ok(20140u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: true,
            } => Ok(20141u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: false,
            } => Ok(20142u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: true,
            } => Ok(20143u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: false,
            } => Ok(20144u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: true,
            } => Ok(20145u32),
            ButtonBlock {
                block_type: ButtonBlockType::CrimsonButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: false,
            } => Ok(20146u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: true,
            } => Ok(9540u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: false,
            } => Ok(9541u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: true,
            } => Ok(9542u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: false,
            } => Ok(9543u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: true,
            } => Ok(9544u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: false,
            } => Ok(9545u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: true,
            } => Ok(9546u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: false,
            } => Ok(9547u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: true,
            } => Ok(9548u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: false,
            } => Ok(9549u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: true,
            } => Ok(9550u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: false,
            } => Ok(9551u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: true,
            } => Ok(9552u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: false,
            } => Ok(9553u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: true,
            } => Ok(9554u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: false,
            } => Ok(9555u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: true,
            } => Ok(9556u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: false,
            } => Ok(9557u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: true,
            } => Ok(9558u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: false,
            } => Ok(9559u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: true,
            } => Ok(9560u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: false,
            } => Ok(9561u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: true,
            } => Ok(9562u32),
            ButtonBlock {
                block_type: ButtonBlockType::DarkOakButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: false,
            } => Ok(9563u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: true,
            } => Ok(9468u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: false,
            } => Ok(9469u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: true,
            } => Ok(9470u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: false,
            } => Ok(9471u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: true,
            } => Ok(9472u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: false,
            } => Ok(9473u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: true,
            } => Ok(9474u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: false,
            } => Ok(9475u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: true,
            } => Ok(9476u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: false,
            } => Ok(9477u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: true,
            } => Ok(9478u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: false,
            } => Ok(9479u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: true,
            } => Ok(9480u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: false,
            } => Ok(9481u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: true,
            } => Ok(9482u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: false,
            } => Ok(9483u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: true,
            } => Ok(9484u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: false,
            } => Ok(9485u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: true,
            } => Ok(9486u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: false,
            } => Ok(9487u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: true,
            } => Ok(9488u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: false,
            } => Ok(9489u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: true,
            } => Ok(9490u32),
            ButtonBlock {
                block_type: ButtonBlockType::JungleButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: false,
            } => Ok(9491u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: true,
            } => Ok(5802u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: false,
            } => Ok(5803u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: true,
            } => Ok(5804u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: false,
            } => Ok(5805u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: true,
            } => Ok(5806u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: false,
            } => Ok(5807u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: true,
            } => Ok(5808u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: false,
            } => Ok(5809u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: true,
            } => Ok(5810u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: false,
            } => Ok(5811u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: true,
            } => Ok(5812u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: false,
            } => Ok(5813u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: true,
            } => Ok(5814u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: false,
            } => Ok(5815u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: true,
            } => Ok(5816u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: false,
            } => Ok(5817u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: true,
            } => Ok(5818u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: false,
            } => Ok(5819u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: true,
            } => Ok(5820u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: false,
            } => Ok(5821u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: true,
            } => Ok(5822u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: false,
            } => Ok(5823u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: true,
            } => Ok(5824u32),
            ButtonBlock {
                block_type: ButtonBlockType::Lever,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: false,
            } => Ok(5825u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: true,
            } => Ok(9588u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: false,
            } => Ok(9589u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: true,
            } => Ok(9590u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: false,
            } => Ok(9591u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: true,
            } => Ok(9592u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: false,
            } => Ok(9593u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: true,
            } => Ok(9594u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: false,
            } => Ok(9595u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: true,
            } => Ok(9596u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: false,
            } => Ok(9597u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: true,
            } => Ok(9598u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: false,
            } => Ok(9599u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: true,
            } => Ok(9600u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: false,
            } => Ok(9601u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: true,
            } => Ok(9602u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: false,
            } => Ok(9603u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: true,
            } => Ok(9604u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: false,
            } => Ok(9605u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: true,
            } => Ok(9606u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: false,
            } => Ok(9607u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: true,
            } => Ok(9608u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: false,
            } => Ok(9609u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: true,
            } => Ok(9610u32),
            ButtonBlock {
                block_type: ButtonBlockType::MangroveButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: false,
            } => Ok(9611u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: true,
            } => Ok(9396u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: false,
            } => Ok(9397u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: true,
            } => Ok(9398u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: false,
            } => Ok(9399u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: true,
            } => Ok(9400u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: false,
            } => Ok(9401u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: true,
            } => Ok(9402u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: false,
            } => Ok(9403u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: true,
            } => Ok(9404u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: false,
            } => Ok(9405u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: true,
            } => Ok(9406u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: false,
            } => Ok(9407u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: true,
            } => Ok(9408u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: false,
            } => Ok(9409u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: true,
            } => Ok(9410u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: false,
            } => Ok(9411u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: true,
            } => Ok(9412u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: false,
            } => Ok(9413u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: true,
            } => Ok(9414u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: false,
            } => Ok(9415u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: true,
            } => Ok(9416u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: false,
            } => Ok(9417u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: true,
            } => Ok(9418u32),
            ButtonBlock {
                block_type: ButtonBlockType::OakButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: false,
            } => Ok(9419u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: true,
            } => Ok(9564u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: false,
            } => Ok(9565u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: true,
            } => Ok(9566u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: false,
            } => Ok(9567u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: true,
            } => Ok(9568u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: false,
            } => Ok(9569u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: true,
            } => Ok(9570u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: false,
            } => Ok(9571u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: true,
            } => Ok(9572u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: false,
            } => Ok(9573u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: true,
            } => Ok(9574u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: false,
            } => Ok(9575u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: true,
            } => Ok(9576u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: false,
            } => Ok(9577u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: true,
            } => Ok(9578u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: false,
            } => Ok(9579u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: true,
            } => Ok(9580u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: false,
            } => Ok(9581u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: true,
            } => Ok(9582u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: false,
            } => Ok(9583u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: true,
            } => Ok(9584u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: false,
            } => Ok(9585u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: true,
            } => Ok(9586u32),
            ButtonBlock {
                block_type: ButtonBlockType::PaleOakButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: false,
            } => Ok(9587u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: true,
            } => Ok(21402u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: false,
            } => Ok(21403u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: true,
            } => Ok(21404u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: false,
            } => Ok(21405u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: true,
            } => Ok(21406u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: false,
            } => Ok(21407u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: true,
            } => Ok(21408u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: false,
            } => Ok(21409u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: true,
            } => Ok(21410u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: false,
            } => Ok(21411u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: true,
            } => Ok(21412u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: false,
            } => Ok(21413u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: true,
            } => Ok(21414u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: false,
            } => Ok(21415u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: true,
            } => Ok(21416u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: false,
            } => Ok(21417u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: true,
            } => Ok(21418u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: false,
            } => Ok(21419u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: true,
            } => Ok(21420u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: false,
            } => Ok(21421u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: true,
            } => Ok(21422u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: false,
            } => Ok(21423u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: true,
            } => Ok(21424u32),
            ButtonBlock {
                block_type: ButtonBlockType::PolishedBlackstoneButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: false,
            } => Ok(21425u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: true,
            } => Ok(9420u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: false,
            } => Ok(9421u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: true,
            } => Ok(9422u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: false,
            } => Ok(9423u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: true,
            } => Ok(9424u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: false,
            } => Ok(9425u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: true,
            } => Ok(9426u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: false,
            } => Ok(9427u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: true,
            } => Ok(9428u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: false,
            } => Ok(9429u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: true,
            } => Ok(9430u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: false,
            } => Ok(9431u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: true,
            } => Ok(9432u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: false,
            } => Ok(9433u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: true,
            } => Ok(9434u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: false,
            } => Ok(9435u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: true,
            } => Ok(9436u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: false,
            } => Ok(9437u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: true,
            } => Ok(9438u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: false,
            } => Ok(9439u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: true,
            } => Ok(9440u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: false,
            } => Ok(9441u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: true,
            } => Ok(9442u32),
            ButtonBlock {
                block_type: ButtonBlockType::SpruceButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: false,
            } => Ok(9443u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: true,
            } => Ok(5926u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: false,
            } => Ok(5927u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: true,
            } => Ok(5928u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: false,
            } => Ok(5929u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: true,
            } => Ok(5930u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: false,
            } => Ok(5931u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: true,
            } => Ok(5932u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: false,
            } => Ok(5933u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: true,
            } => Ok(5934u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: false,
            } => Ok(5935u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: true,
            } => Ok(5936u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: false,
            } => Ok(5937u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: true,
            } => Ok(5938u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: false,
            } => Ok(5939u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: true,
            } => Ok(5940u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: false,
            } => Ok(5941u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: true,
            } => Ok(5942u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: false,
            } => Ok(5943u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: true,
            } => Ok(5944u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: false,
            } => Ok(5945u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: true,
            } => Ok(5946u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: false,
            } => Ok(5947u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: true,
            } => Ok(5948u32),
            ButtonBlock {
                block_type: ButtonBlockType::StoneButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: false,
            } => Ok(5949u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: true,
            } => Ok(20147u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Floor,
                facing: Direction::North,
                powered: false,
            } => Ok(20148u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: true,
            } => Ok(20149u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Floor,
                facing: Direction::South,
                powered: false,
            } => Ok(20150u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: true,
            } => Ok(20151u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Floor,
                facing: Direction::West,
                powered: false,
            } => Ok(20152u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: true,
            } => Ok(20153u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Floor,
                facing: Direction::East,
                powered: false,
            } => Ok(20154u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: true,
            } => Ok(20155u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Wall,
                facing: Direction::North,
                powered: false,
            } => Ok(20156u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: true,
            } => Ok(20157u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Wall,
                facing: Direction::South,
                powered: false,
            } => Ok(20158u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: true,
            } => Ok(20159u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Wall,
                facing: Direction::West,
                powered: false,
            } => Ok(20160u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: true,
            } => Ok(20161u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Wall,
                facing: Direction::East,
                powered: false,
            } => Ok(20162u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: true,
            } => Ok(20163u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Ceiling,
                facing: Direction::North,
                powered: false,
            } => Ok(20164u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: true,
            } => Ok(20165u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Ceiling,
                facing: Direction::South,
                powered: false,
            } => Ok(20166u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: true,
            } => Ok(20167u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Ceiling,
                facing: Direction::West,
                powered: false,
            } => Ok(20168u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: true,
            } => Ok(20169u32),
            ButtonBlock {
                block_type: ButtonBlockType::WarpedButton,
                face: AttachFace::Ceiling,
                facing: Direction::East,
                powered: false,
            } => Ok(20170u32),
            _ => Err(()),
        }
    }
}
