#[allow(unused_imports)]
use ferrumc_block_properties::*;
#[allow(dead_code)]
#[derive(Clone, Debug)]
pub enum CampfireBlockType {
    Campfire,
    SoulCampfire,
}
#[allow(dead_code)]
#[derive(Clone, Debug)]
pub struct CampfireBlock {
    pub block_type: CampfireBlockType,
    pub facing: Direction,
    pub lit: bool,
    pub signal_fire: bool,
    pub waterlogged: bool,
}
impl TryInto<u32> for CampfireBlock {
    type Error = ();
    fn try_into(self) -> Result<u32, Self::Error> {
        #[allow(unreachable_patterns)]
        match self {
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::North,
                lit: true,
                signal_fire: true,
                waterlogged: true,
            } => Ok(19534u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::North,
                lit: true,
                signal_fire: true,
                waterlogged: false,
            } => Ok(19535u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::North,
                lit: true,
                signal_fire: false,
                waterlogged: true,
            } => Ok(19536u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::North,
                lit: true,
                signal_fire: false,
                waterlogged: false,
            } => Ok(19537u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::North,
                lit: false,
                signal_fire: true,
                waterlogged: true,
            } => Ok(19538u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::North,
                lit: false,
                signal_fire: true,
                waterlogged: false,
            } => Ok(19539u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::North,
                lit: false,
                signal_fire: false,
                waterlogged: true,
            } => Ok(19540u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::North,
                lit: false,
                signal_fire: false,
                waterlogged: false,
            } => Ok(19541u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::South,
                lit: true,
                signal_fire: true,
                waterlogged: true,
            } => Ok(19542u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::South,
                lit: true,
                signal_fire: true,
                waterlogged: false,
            } => Ok(19543u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::South,
                lit: true,
                signal_fire: false,
                waterlogged: true,
            } => Ok(19544u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::South,
                lit: true,
                signal_fire: false,
                waterlogged: false,
            } => Ok(19545u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::South,
                lit: false,
                signal_fire: true,
                waterlogged: true,
            } => Ok(19546u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::South,
                lit: false,
                signal_fire: true,
                waterlogged: false,
            } => Ok(19547u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::South,
                lit: false,
                signal_fire: false,
                waterlogged: true,
            } => Ok(19548u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::South,
                lit: false,
                signal_fire: false,
                waterlogged: false,
            } => Ok(19549u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::West,
                lit: true,
                signal_fire: true,
                waterlogged: true,
            } => Ok(19550u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::West,
                lit: true,
                signal_fire: true,
                waterlogged: false,
            } => Ok(19551u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::West,
                lit: true,
                signal_fire: false,
                waterlogged: true,
            } => Ok(19552u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::West,
                lit: true,
                signal_fire: false,
                waterlogged: false,
            } => Ok(19553u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::West,
                lit: false,
                signal_fire: true,
                waterlogged: true,
            } => Ok(19554u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::West,
                lit: false,
                signal_fire: true,
                waterlogged: false,
            } => Ok(19555u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::West,
                lit: false,
                signal_fire: false,
                waterlogged: true,
            } => Ok(19556u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::West,
                lit: false,
                signal_fire: false,
                waterlogged: false,
            } => Ok(19557u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::East,
                lit: true,
                signal_fire: true,
                waterlogged: true,
            } => Ok(19558u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::East,
                lit: true,
                signal_fire: true,
                waterlogged: false,
            } => Ok(19559u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::East,
                lit: true,
                signal_fire: false,
                waterlogged: true,
            } => Ok(19560u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::East,
                lit: true,
                signal_fire: false,
                waterlogged: false,
            } => Ok(19561u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::East,
                lit: false,
                signal_fire: true,
                waterlogged: true,
            } => Ok(19562u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::East,
                lit: false,
                signal_fire: true,
                waterlogged: false,
            } => Ok(19563u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::East,
                lit: false,
                signal_fire: false,
                waterlogged: true,
            } => Ok(19564u32),
            CampfireBlock {
                block_type: CampfireBlockType::Campfire,
                facing: Direction::East,
                lit: false,
                signal_fire: false,
                waterlogged: false,
            } => Ok(19565u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::North,
                lit: true,
                signal_fire: true,
                waterlogged: true,
            } => Ok(19566u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::North,
                lit: true,
                signal_fire: true,
                waterlogged: false,
            } => Ok(19567u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::North,
                lit: true,
                signal_fire: false,
                waterlogged: true,
            } => Ok(19568u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::North,
                lit: true,
                signal_fire: false,
                waterlogged: false,
            } => Ok(19569u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::North,
                lit: false,
                signal_fire: true,
                waterlogged: true,
            } => Ok(19570u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::North,
                lit: false,
                signal_fire: true,
                waterlogged: false,
            } => Ok(19571u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::North,
                lit: false,
                signal_fire: false,
                waterlogged: true,
            } => Ok(19572u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::North,
                lit: false,
                signal_fire: false,
                waterlogged: false,
            } => Ok(19573u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::South,
                lit: true,
                signal_fire: true,
                waterlogged: true,
            } => Ok(19574u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::South,
                lit: true,
                signal_fire: true,
                waterlogged: false,
            } => Ok(19575u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::South,
                lit: true,
                signal_fire: false,
                waterlogged: true,
            } => Ok(19576u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::South,
                lit: true,
                signal_fire: false,
                waterlogged: false,
            } => Ok(19577u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::South,
                lit: false,
                signal_fire: true,
                waterlogged: true,
            } => Ok(19578u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::South,
                lit: false,
                signal_fire: true,
                waterlogged: false,
            } => Ok(19579u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::South,
                lit: false,
                signal_fire: false,
                waterlogged: true,
            } => Ok(19580u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::South,
                lit: false,
                signal_fire: false,
                waterlogged: false,
            } => Ok(19581u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::West,
                lit: true,
                signal_fire: true,
                waterlogged: true,
            } => Ok(19582u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::West,
                lit: true,
                signal_fire: true,
                waterlogged: false,
            } => Ok(19583u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::West,
                lit: true,
                signal_fire: false,
                waterlogged: true,
            } => Ok(19584u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::West,
                lit: true,
                signal_fire: false,
                waterlogged: false,
            } => Ok(19585u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::West,
                lit: false,
                signal_fire: true,
                waterlogged: true,
            } => Ok(19586u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::West,
                lit: false,
                signal_fire: true,
                waterlogged: false,
            } => Ok(19587u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::West,
                lit: false,
                signal_fire: false,
                waterlogged: true,
            } => Ok(19588u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::West,
                lit: false,
                signal_fire: false,
                waterlogged: false,
            } => Ok(19589u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::East,
                lit: true,
                signal_fire: true,
                waterlogged: true,
            } => Ok(19590u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::East,
                lit: true,
                signal_fire: true,
                waterlogged: false,
            } => Ok(19591u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::East,
                lit: true,
                signal_fire: false,
                waterlogged: true,
            } => Ok(19592u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::East,
                lit: true,
                signal_fire: false,
                waterlogged: false,
            } => Ok(19593u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::East,
                lit: false,
                signal_fire: true,
                waterlogged: true,
            } => Ok(19594u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::East,
                lit: false,
                signal_fire: true,
                waterlogged: false,
            } => Ok(19595u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::East,
                lit: false,
                signal_fire: false,
                waterlogged: true,
            } => Ok(19596u32),
            CampfireBlock {
                block_type: CampfireBlockType::SoulCampfire,
                facing: Direction::East,
                lit: false,
                signal_fire: false,
                waterlogged: false,
            } => Ok(19597u32),
            _ => Err(()),
        }
    }
}
