#[allow(unused_imports)]
use ferrumc_block_properties::*;
#[allow(dead_code)]
#[derive(Clone, Debug)]
pub enum CandleBlockType {
    BlackCandle,
    BlueCandle,
    BrownCandle,
    Candle,
    CyanCandle,
    GrayCandle,
    GreenCandle,
    LightBlueCandle,
    LightGrayCandle,
    LimeCandle,
    MagentaCandle,
    OrangeCandle,
    PinkCandle,
    PurpleCandle,
    RedCandle,
    WhiteCandle,
    YellowCandle,
}
#[allow(dead_code)]
#[derive(Clone, Debug)]
pub struct CandleBlock {
    pub block_type: CandleBlockType,
    pub candles: i32,
    pub lit: bool,
    pub waterlogged: bool,
}
impl TryInto<u32> for CandleBlock {
    type Error = ();
    fn try_into(self) -> Result<u32, Self::Error> {
        #[allow(unreachable_patterns)]
        match self {
            CandleBlock {
                block_type: CandleBlockType::BlackCandle,
                candles: 1i32,
                lit: true,
                waterlogged: true,
            } => Ok(22009u32),
            CandleBlock {
                block_type: CandleBlockType::BlackCandle,
                candles: 1i32,
                lit: true,
                waterlogged: false,
            } => Ok(22010u32),
            CandleBlock {
                block_type: CandleBlockType::BlackCandle,
                candles: 1i32,
                lit: false,
                waterlogged: true,
            } => Ok(22011u32),
            CandleBlock {
                block_type: CandleBlockType::BlackCandle,
                candles: 1i32,
                lit: false,
                waterlogged: false,
            } => Ok(22012u32),
            CandleBlock {
                block_type: CandleBlockType::BlackCandle,
                candles: 2i32,
                lit: true,
                waterlogged: true,
            } => Ok(22013u32),
            CandleBlock {
                block_type: CandleBlockType::BlackCandle,
                candles: 2i32,
                lit: true,
                waterlogged: false,
            } => Ok(22014u32),
            CandleBlock {
                block_type: CandleBlockType::BlackCandle,
                candles: 2i32,
                lit: false,
                waterlogged: true,
            } => Ok(22015u32),
            CandleBlock {
                block_type: CandleBlockType::BlackCandle,
                candles: 2i32,
                lit: false,
                waterlogged: false,
            } => Ok(22016u32),
            CandleBlock {
                block_type: CandleBlockType::BlackCandle,
                candles: 3i32,
                lit: true,
                waterlogged: true,
            } => Ok(22017u32),
            CandleBlock {
                block_type: CandleBlockType::BlackCandle,
                candles: 3i32,
                lit: true,
                waterlogged: false,
            } => Ok(22018u32),
            CandleBlock {
                block_type: CandleBlockType::BlackCandle,
                candles: 3i32,
                lit: false,
                waterlogged: true,
            } => Ok(22019u32),
            CandleBlock {
                block_type: CandleBlockType::BlackCandle,
                candles: 3i32,
                lit: false,
                waterlogged: false,
            } => Ok(22020u32),
            CandleBlock {
                block_type: CandleBlockType::BlackCandle,
                candles: 4i32,
                lit: true,
                waterlogged: true,
            } => Ok(22021u32),
            CandleBlock {
                block_type: CandleBlockType::BlackCandle,
                candles: 4i32,
                lit: true,
                waterlogged: false,
            } => Ok(22022u32),
            CandleBlock {
                block_type: CandleBlockType::BlackCandle,
                candles: 4i32,
                lit: false,
                waterlogged: true,
            } => Ok(22023u32),
            CandleBlock {
                block_type: CandleBlockType::BlackCandle,
                candles: 4i32,
                lit: false,
                waterlogged: false,
            } => Ok(22024u32),
            CandleBlock {
                block_type: CandleBlockType::BlueCandle,
                candles: 1i32,
                lit: true,
                waterlogged: true,
            } => Ok(21945u32),
            CandleBlock {
                block_type: CandleBlockType::BlueCandle,
                candles: 1i32,
                lit: true,
                waterlogged: false,
            } => Ok(21946u32),
            CandleBlock {
                block_type: CandleBlockType::BlueCandle,
                candles: 1i32,
                lit: false,
                waterlogged: true,
            } => Ok(21947u32),
            CandleBlock {
                block_type: CandleBlockType::BlueCandle,
                candles: 1i32,
                lit: false,
                waterlogged: false,
            } => Ok(21948u32),
            CandleBlock {
                block_type: CandleBlockType::BlueCandle,
                candles: 2i32,
                lit: true,
                waterlogged: true,
            } => Ok(21949u32),
            CandleBlock {
                block_type: CandleBlockType::BlueCandle,
                candles: 2i32,
                lit: true,
                waterlogged: false,
            } => Ok(21950u32),
            CandleBlock {
                block_type: CandleBlockType::BlueCandle,
                candles: 2i32,
                lit: false,
                waterlogged: true,
            } => Ok(21951u32),
            CandleBlock {
                block_type: CandleBlockType::BlueCandle,
                candles: 2i32,
                lit: false,
                waterlogged: false,
            } => Ok(21952u32),
            CandleBlock {
                block_type: CandleBlockType::BlueCandle,
                candles: 3i32,
                lit: true,
                waterlogged: true,
            } => Ok(21953u32),
            CandleBlock {
                block_type: CandleBlockType::BlueCandle,
                candles: 3i32,
                lit: true,
                waterlogged: false,
            } => Ok(21954u32),
            CandleBlock {
                block_type: CandleBlockType::BlueCandle,
                candles: 3i32,
                lit: false,
                waterlogged: true,
            } => Ok(21955u32),
            CandleBlock {
                block_type: CandleBlockType::BlueCandle,
                candles: 3i32,
                lit: false,
                waterlogged: false,
            } => Ok(21956u32),
            CandleBlock {
                block_type: CandleBlockType::BlueCandle,
                candles: 4i32,
                lit: true,
                waterlogged: true,
            } => Ok(21957u32),
            CandleBlock {
                block_type: CandleBlockType::BlueCandle,
                candles: 4i32,
                lit: true,
                waterlogged: false,
            } => Ok(21958u32),
            CandleBlock {
                block_type: CandleBlockType::BlueCandle,
                candles: 4i32,
                lit: false,
                waterlogged: true,
            } => Ok(21959u32),
            CandleBlock {
                block_type: CandleBlockType::BlueCandle,
                candles: 4i32,
                lit: false,
                waterlogged: false,
            } => Ok(21960u32),
            CandleBlock {
                block_type: CandleBlockType::BrownCandle,
                candles: 1i32,
                lit: true,
                waterlogged: true,
            } => Ok(21961u32),
            CandleBlock {
                block_type: CandleBlockType::BrownCandle,
                candles: 1i32,
                lit: true,
                waterlogged: false,
            } => Ok(21962u32),
            CandleBlock {
                block_type: CandleBlockType::BrownCandle,
                candles: 1i32,
                lit: false,
                waterlogged: true,
            } => Ok(21963u32),
            CandleBlock {
                block_type: CandleBlockType::BrownCandle,
                candles: 1i32,
                lit: false,
                waterlogged: false,
            } => Ok(21964u32),
            CandleBlock {
                block_type: CandleBlockType::BrownCandle,
                candles: 2i32,
                lit: true,
                waterlogged: true,
            } => Ok(21965u32),
            CandleBlock {
                block_type: CandleBlockType::BrownCandle,
                candles: 2i32,
                lit: true,
                waterlogged: false,
            } => Ok(21966u32),
            CandleBlock {
                block_type: CandleBlockType::BrownCandle,
                candles: 2i32,
                lit: false,
                waterlogged: true,
            } => Ok(21967u32),
            CandleBlock {
                block_type: CandleBlockType::BrownCandle,
                candles: 2i32,
                lit: false,
                waterlogged: false,
            } => Ok(21968u32),
            CandleBlock {
                block_type: CandleBlockType::BrownCandle,
                candles: 3i32,
                lit: true,
                waterlogged: true,
            } => Ok(21969u32),
            CandleBlock {
                block_type: CandleBlockType::BrownCandle,
                candles: 3i32,
                lit: true,
                waterlogged: false,
            } => Ok(21970u32),
            CandleBlock {
                block_type: CandleBlockType::BrownCandle,
                candles: 3i32,
                lit: false,
                waterlogged: true,
            } => Ok(21971u32),
            CandleBlock {
                block_type: CandleBlockType::BrownCandle,
                candles: 3i32,
                lit: false,
                waterlogged: false,
            } => Ok(21972u32),
            CandleBlock {
                block_type: CandleBlockType::BrownCandle,
                candles: 4i32,
                lit: true,
                waterlogged: true,
            } => Ok(21973u32),
            CandleBlock {
                block_type: CandleBlockType::BrownCandle,
                candles: 4i32,
                lit: true,
                waterlogged: false,
            } => Ok(21974u32),
            CandleBlock {
                block_type: CandleBlockType::BrownCandle,
                candles: 4i32,
                lit: false,
                waterlogged: true,
            } => Ok(21975u32),
            CandleBlock {
                block_type: CandleBlockType::BrownCandle,
                candles: 4i32,
                lit: false,
                waterlogged: false,
            } => Ok(21976u32),
            CandleBlock {
                block_type: CandleBlockType::Candle,
                candles: 1i32,
                lit: true,
                waterlogged: true,
            } => Ok(21753u32),
            CandleBlock {
                block_type: CandleBlockType::Candle,
                candles: 1i32,
                lit: true,
                waterlogged: false,
            } => Ok(21754u32),
            CandleBlock {
                block_type: CandleBlockType::Candle,
                candles: 1i32,
                lit: false,
                waterlogged: true,
            } => Ok(21755u32),
            CandleBlock {
                block_type: CandleBlockType::Candle,
                candles: 1i32,
                lit: false,
                waterlogged: false,
            } => Ok(21756u32),
            CandleBlock {
                block_type: CandleBlockType::Candle,
                candles: 2i32,
                lit: true,
                waterlogged: true,
            } => Ok(21757u32),
            CandleBlock {
                block_type: CandleBlockType::Candle,
                candles: 2i32,
                lit: true,
                waterlogged: false,
            } => Ok(21758u32),
            CandleBlock {
                block_type: CandleBlockType::Candle,
                candles: 2i32,
                lit: false,
                waterlogged: true,
            } => Ok(21759u32),
            CandleBlock {
                block_type: CandleBlockType::Candle,
                candles: 2i32,
                lit: false,
                waterlogged: false,
            } => Ok(21760u32),
            CandleBlock {
                block_type: CandleBlockType::Candle,
                candles: 3i32,
                lit: true,
                waterlogged: true,
            } => Ok(21761u32),
            CandleBlock {
                block_type: CandleBlockType::Candle,
                candles: 3i32,
                lit: true,
                waterlogged: false,
            } => Ok(21762u32),
            CandleBlock {
                block_type: CandleBlockType::Candle,
                candles: 3i32,
                lit: false,
                waterlogged: true,
            } => Ok(21763u32),
            CandleBlock {
                block_type: CandleBlockType::Candle,
                candles: 3i32,
                lit: false,
                waterlogged: false,
            } => Ok(21764u32),
            CandleBlock {
                block_type: CandleBlockType::Candle,
                candles: 4i32,
                lit: true,
                waterlogged: true,
            } => Ok(21765u32),
            CandleBlock {
                block_type: CandleBlockType::Candle,
                candles: 4i32,
                lit: true,
                waterlogged: false,
            } => Ok(21766u32),
            CandleBlock {
                block_type: CandleBlockType::Candle,
                candles: 4i32,
                lit: false,
                waterlogged: true,
            } => Ok(21767u32),
            CandleBlock {
                block_type: CandleBlockType::Candle,
                candles: 4i32,
                lit: false,
                waterlogged: false,
            } => Ok(21768u32),
            CandleBlock {
                block_type: CandleBlockType::CyanCandle,
                candles: 1i32,
                lit: true,
                waterlogged: true,
            } => Ok(21913u32),
            CandleBlock {
                block_type: CandleBlockType::CyanCandle,
                candles: 1i32,
                lit: true,
                waterlogged: false,
            } => Ok(21914u32),
            CandleBlock {
                block_type: CandleBlockType::CyanCandle,
                candles: 1i32,
                lit: false,
                waterlogged: true,
            } => Ok(21915u32),
            CandleBlock {
                block_type: CandleBlockType::CyanCandle,
                candles: 1i32,
                lit: false,
                waterlogged: false,
            } => Ok(21916u32),
            CandleBlock {
                block_type: CandleBlockType::CyanCandle,
                candles: 2i32,
                lit: true,
                waterlogged: true,
            } => Ok(21917u32),
            CandleBlock {
                block_type: CandleBlockType::CyanCandle,
                candles: 2i32,
                lit: true,
                waterlogged: false,
            } => Ok(21918u32),
            CandleBlock {
                block_type: CandleBlockType::CyanCandle,
                candles: 2i32,
                lit: false,
                waterlogged: true,
            } => Ok(21919u32),
            CandleBlock {
                block_type: CandleBlockType::CyanCandle,
                candles: 2i32,
                lit: false,
                waterlogged: false,
            } => Ok(21920u32),
            CandleBlock {
                block_type: CandleBlockType::CyanCandle,
                candles: 3i32,
                lit: true,
                waterlogged: true,
            } => Ok(21921u32),
            CandleBlock {
                block_type: CandleBlockType::CyanCandle,
                candles: 3i32,
                lit: true,
                waterlogged: false,
            } => Ok(21922u32),
            CandleBlock {
                block_type: CandleBlockType::CyanCandle,
                candles: 3i32,
                lit: false,
                waterlogged: true,
            } => Ok(21923u32),
            CandleBlock {
                block_type: CandleBlockType::CyanCandle,
                candles: 3i32,
                lit: false,
                waterlogged: false,
            } => Ok(21924u32),
            CandleBlock {
                block_type: CandleBlockType::CyanCandle,
                candles: 4i32,
                lit: true,
                waterlogged: true,
            } => Ok(21925u32),
            CandleBlock {
                block_type: CandleBlockType::CyanCandle,
                candles: 4i32,
                lit: true,
                waterlogged: false,
            } => Ok(21926u32),
            CandleBlock {
                block_type: CandleBlockType::CyanCandle,
                candles: 4i32,
                lit: false,
                waterlogged: true,
            } => Ok(21927u32),
            CandleBlock {
                block_type: CandleBlockType::CyanCandle,
                candles: 4i32,
                lit: false,
                waterlogged: false,
            } => Ok(21928u32),
            CandleBlock {
                block_type: CandleBlockType::GrayCandle,
                candles: 1i32,
                lit: true,
                waterlogged: true,
            } => Ok(21881u32),
            CandleBlock {
                block_type: CandleBlockType::GrayCandle,
                candles: 1i32,
                lit: true,
                waterlogged: false,
            } => Ok(21882u32),
            CandleBlock {
                block_type: CandleBlockType::GrayCandle,
                candles: 1i32,
                lit: false,
                waterlogged: true,
            } => Ok(21883u32),
            CandleBlock {
                block_type: CandleBlockType::GrayCandle,
                candles: 1i32,
                lit: false,
                waterlogged: false,
            } => Ok(21884u32),
            CandleBlock {
                block_type: CandleBlockType::GrayCandle,
                candles: 2i32,
                lit: true,
                waterlogged: true,
            } => Ok(21885u32),
            CandleBlock {
                block_type: CandleBlockType::GrayCandle,
                candles: 2i32,
                lit: true,
                waterlogged: false,
            } => Ok(21886u32),
            CandleBlock {
                block_type: CandleBlockType::GrayCandle,
                candles: 2i32,
                lit: false,
                waterlogged: true,
            } => Ok(21887u32),
            CandleBlock {
                block_type: CandleBlockType::GrayCandle,
                candles: 2i32,
                lit: false,
                waterlogged: false,
            } => Ok(21888u32),
            CandleBlock {
                block_type: CandleBlockType::GrayCandle,
                candles: 3i32,
                lit: true,
                waterlogged: true,
            } => Ok(21889u32),
            CandleBlock {
                block_type: CandleBlockType::GrayCandle,
                candles: 3i32,
                lit: true,
                waterlogged: false,
            } => Ok(21890u32),
            CandleBlock {
                block_type: CandleBlockType::GrayCandle,
                candles: 3i32,
                lit: false,
                waterlogged: true,
            } => Ok(21891u32),
            CandleBlock {
                block_type: CandleBlockType::GrayCandle,
                candles: 3i32,
                lit: false,
                waterlogged: false,
            } => Ok(21892u32),
            CandleBlock {
                block_type: CandleBlockType::GrayCandle,
                candles: 4i32,
                lit: true,
                waterlogged: true,
            } => Ok(21893u32),
            CandleBlock {
                block_type: CandleBlockType::GrayCandle,
                candles: 4i32,
                lit: true,
                waterlogged: false,
            } => Ok(21894u32),
            CandleBlock {
                block_type: CandleBlockType::GrayCandle,
                candles: 4i32,
                lit: false,
                waterlogged: true,
            } => Ok(21895u32),
            CandleBlock {
                block_type: CandleBlockType::GrayCandle,
                candles: 4i32,
                lit: false,
                waterlogged: false,
            } => Ok(21896u32),
            CandleBlock {
                block_type: CandleBlockType::GreenCandle,
                candles: 1i32,
                lit: true,
                waterlogged: true,
            } => Ok(21977u32),
            CandleBlock {
                block_type: CandleBlockType::GreenCandle,
                candles: 1i32,
                lit: true,
                waterlogged: false,
            } => Ok(21978u32),
            CandleBlock {
                block_type: CandleBlockType::GreenCandle,
                candles: 1i32,
                lit: false,
                waterlogged: true,
            } => Ok(21979u32),
            CandleBlock {
                block_type: CandleBlockType::GreenCandle,
                candles: 1i32,
                lit: false,
                waterlogged: false,
            } => Ok(21980u32),
            CandleBlock {
                block_type: CandleBlockType::GreenCandle,
                candles: 2i32,
                lit: true,
                waterlogged: true,
            } => Ok(21981u32),
            CandleBlock {
                block_type: CandleBlockType::GreenCandle,
                candles: 2i32,
                lit: true,
                waterlogged: false,
            } => Ok(21982u32),
            CandleBlock {
                block_type: CandleBlockType::GreenCandle,
                candles: 2i32,
                lit: false,
                waterlogged: true,
            } => Ok(21983u32),
            CandleBlock {
                block_type: CandleBlockType::GreenCandle,
                candles: 2i32,
                lit: false,
                waterlogged: false,
            } => Ok(21984u32),
            CandleBlock {
                block_type: CandleBlockType::GreenCandle,
                candles: 3i32,
                lit: true,
                waterlogged: true,
            } => Ok(21985u32),
            CandleBlock {
                block_type: CandleBlockType::GreenCandle,
                candles: 3i32,
                lit: true,
                waterlogged: false,
            } => Ok(21986u32),
            CandleBlock {
                block_type: CandleBlockType::GreenCandle,
                candles: 3i32,
                lit: false,
                waterlogged: true,
            } => Ok(21987u32),
            CandleBlock {
                block_type: CandleBlockType::GreenCandle,
                candles: 3i32,
                lit: false,
                waterlogged: false,
            } => Ok(21988u32),
            CandleBlock {
                block_type: CandleBlockType::GreenCandle,
                candles: 4i32,
                lit: true,
                waterlogged: true,
            } => Ok(21989u32),
            CandleBlock {
                block_type: CandleBlockType::GreenCandle,
                candles: 4i32,
                lit: true,
                waterlogged: false,
            } => Ok(21990u32),
            CandleBlock {
                block_type: CandleBlockType::GreenCandle,
                candles: 4i32,
                lit: false,
                waterlogged: true,
            } => Ok(21991u32),
            CandleBlock {
                block_type: CandleBlockType::GreenCandle,
                candles: 4i32,
                lit: false,
                waterlogged: false,
            } => Ok(21992u32),
            CandleBlock {
                block_type: CandleBlockType::LightBlueCandle,
                candles: 1i32,
                lit: true,
                waterlogged: true,
            } => Ok(21817u32),
            CandleBlock {
                block_type: CandleBlockType::LightBlueCandle,
                candles: 1i32,
                lit: true,
                waterlogged: false,
            } => Ok(21818u32),
            CandleBlock {
                block_type: CandleBlockType::LightBlueCandle,
                candles: 1i32,
                lit: false,
                waterlogged: true,
            } => Ok(21819u32),
            CandleBlock {
                block_type: CandleBlockType::LightBlueCandle,
                candles: 1i32,
                lit: false,
                waterlogged: false,
            } => Ok(21820u32),
            CandleBlock {
                block_type: CandleBlockType::LightBlueCandle,
                candles: 2i32,
                lit: true,
                waterlogged: true,
            } => Ok(21821u32),
            CandleBlock {
                block_type: CandleBlockType::LightBlueCandle,
                candles: 2i32,
                lit: true,
                waterlogged: false,
            } => Ok(21822u32),
            CandleBlock {
                block_type: CandleBlockType::LightBlueCandle,
                candles: 2i32,
                lit: false,
                waterlogged: true,
            } => Ok(21823u32),
            CandleBlock {
                block_type: CandleBlockType::LightBlueCandle,
                candles: 2i32,
                lit: false,
                waterlogged: false,
            } => Ok(21824u32),
            CandleBlock {
                block_type: CandleBlockType::LightBlueCandle,
                candles: 3i32,
                lit: true,
                waterlogged: true,
            } => Ok(21825u32),
            CandleBlock {
                block_type: CandleBlockType::LightBlueCandle,
                candles: 3i32,
                lit: true,
                waterlogged: false,
            } => Ok(21826u32),
            CandleBlock {
                block_type: CandleBlockType::LightBlueCandle,
                candles: 3i32,
                lit: false,
                waterlogged: true,
            } => Ok(21827u32),
            CandleBlock {
                block_type: CandleBlockType::LightBlueCandle,
                candles: 3i32,
                lit: false,
                waterlogged: false,
            } => Ok(21828u32),
            CandleBlock {
                block_type: CandleBlockType::LightBlueCandle,
                candles: 4i32,
                lit: true,
                waterlogged: true,
            } => Ok(21829u32),
            CandleBlock {
                block_type: CandleBlockType::LightBlueCandle,
                candles: 4i32,
                lit: true,
                waterlogged: false,
            } => Ok(21830u32),
            CandleBlock {
                block_type: CandleBlockType::LightBlueCandle,
                candles: 4i32,
                lit: false,
                waterlogged: true,
            } => Ok(21831u32),
            CandleBlock {
                block_type: CandleBlockType::LightBlueCandle,
                candles: 4i32,
                lit: false,
                waterlogged: false,
            } => Ok(21832u32),
            CandleBlock {
                block_type: CandleBlockType::LightGrayCandle,
                candles: 1i32,
                lit: true,
                waterlogged: true,
            } => Ok(21897u32),
            CandleBlock {
                block_type: CandleBlockType::LightGrayCandle,
                candles: 1i32,
                lit: true,
                waterlogged: false,
            } => Ok(21898u32),
            CandleBlock {
                block_type: CandleBlockType::LightGrayCandle,
                candles: 1i32,
                lit: false,
                waterlogged: true,
            } => Ok(21899u32),
            CandleBlock {
                block_type: CandleBlockType::LightGrayCandle,
                candles: 1i32,
                lit: false,
                waterlogged: false,
            } => Ok(21900u32),
            CandleBlock {
                block_type: CandleBlockType::LightGrayCandle,
                candles: 2i32,
                lit: true,
                waterlogged: true,
            } => Ok(21901u32),
            CandleBlock {
                block_type: CandleBlockType::LightGrayCandle,
                candles: 2i32,
                lit: true,
                waterlogged: false,
            } => Ok(21902u32),
            CandleBlock {
                block_type: CandleBlockType::LightGrayCandle,
                candles: 2i32,
                lit: false,
                waterlogged: true,
            } => Ok(21903u32),
            CandleBlock {
                block_type: CandleBlockType::LightGrayCandle,
                candles: 2i32,
                lit: false,
                waterlogged: false,
            } => Ok(21904u32),
            CandleBlock {
                block_type: CandleBlockType::LightGrayCandle,
                candles: 3i32,
                lit: true,
                waterlogged: true,
            } => Ok(21905u32),
            CandleBlock {
                block_type: CandleBlockType::LightGrayCandle,
                candles: 3i32,
                lit: true,
                waterlogged: false,
            } => Ok(21906u32),
            CandleBlock {
                block_type: CandleBlockType::LightGrayCandle,
                candles: 3i32,
                lit: false,
                waterlogged: true,
            } => Ok(21907u32),
            CandleBlock {
                block_type: CandleBlockType::LightGrayCandle,
                candles: 3i32,
                lit: false,
                waterlogged: false,
            } => Ok(21908u32),
            CandleBlock {
                block_type: CandleBlockType::LightGrayCandle,
                candles: 4i32,
                lit: true,
                waterlogged: true,
            } => Ok(21909u32),
            CandleBlock {
                block_type: CandleBlockType::LightGrayCandle,
                candles: 4i32,
                lit: true,
                waterlogged: false,
            } => Ok(21910u32),
            CandleBlock {
                block_type: CandleBlockType::LightGrayCandle,
                candles: 4i32,
                lit: false,
                waterlogged: true,
            } => Ok(21911u32),
            CandleBlock {
                block_type: CandleBlockType::LightGrayCandle,
                candles: 4i32,
                lit: false,
                waterlogged: false,
            } => Ok(21912u32),
            CandleBlock {
                block_type: CandleBlockType::LimeCandle,
                candles: 1i32,
                lit: true,
                waterlogged: true,
            } => Ok(21849u32),
            CandleBlock {
                block_type: CandleBlockType::LimeCandle,
                candles: 1i32,
                lit: true,
                waterlogged: false,
            } => Ok(21850u32),
            CandleBlock {
                block_type: CandleBlockType::LimeCandle,
                candles: 1i32,
                lit: false,
                waterlogged: true,
            } => Ok(21851u32),
            CandleBlock {
                block_type: CandleBlockType::LimeCandle,
                candles: 1i32,
                lit: false,
                waterlogged: false,
            } => Ok(21852u32),
            CandleBlock {
                block_type: CandleBlockType::LimeCandle,
                candles: 2i32,
                lit: true,
                waterlogged: true,
            } => Ok(21853u32),
            CandleBlock {
                block_type: CandleBlockType::LimeCandle,
                candles: 2i32,
                lit: true,
                waterlogged: false,
            } => Ok(21854u32),
            CandleBlock {
                block_type: CandleBlockType::LimeCandle,
                candles: 2i32,
                lit: false,
                waterlogged: true,
            } => Ok(21855u32),
            CandleBlock {
                block_type: CandleBlockType::LimeCandle,
                candles: 2i32,
                lit: false,
                waterlogged: false,
            } => Ok(21856u32),
            CandleBlock {
                block_type: CandleBlockType::LimeCandle,
                candles: 3i32,
                lit: true,
                waterlogged: true,
            } => Ok(21857u32),
            CandleBlock {
                block_type: CandleBlockType::LimeCandle,
                candles: 3i32,
                lit: true,
                waterlogged: false,
            } => Ok(21858u32),
            CandleBlock {
                block_type: CandleBlockType::LimeCandle,
                candles: 3i32,
                lit: false,
                waterlogged: true,
            } => Ok(21859u32),
            CandleBlock {
                block_type: CandleBlockType::LimeCandle,
                candles: 3i32,
                lit: false,
                waterlogged: false,
            } => Ok(21860u32),
            CandleBlock {
                block_type: CandleBlockType::LimeCandle,
                candles: 4i32,
                lit: true,
                waterlogged: true,
            } => Ok(21861u32),
            CandleBlock {
                block_type: CandleBlockType::LimeCandle,
                candles: 4i32,
                lit: true,
                waterlogged: false,
            } => Ok(21862u32),
            CandleBlock {
                block_type: CandleBlockType::LimeCandle,
                candles: 4i32,
                lit: false,
                waterlogged: true,
            } => Ok(21863u32),
            CandleBlock {
                block_type: CandleBlockType::LimeCandle,
                candles: 4i32,
                lit: false,
                waterlogged: false,
            } => Ok(21864u32),
            CandleBlock {
                block_type: CandleBlockType::MagentaCandle,
                candles: 1i32,
                lit: true,
                waterlogged: true,
            } => Ok(21801u32),
            CandleBlock {
                block_type: CandleBlockType::MagentaCandle,
                candles: 1i32,
                lit: true,
                waterlogged: false,
            } => Ok(21802u32),
            CandleBlock {
                block_type: CandleBlockType::MagentaCandle,
                candles: 1i32,
                lit: false,
                waterlogged: true,
            } => Ok(21803u32),
            CandleBlock {
                block_type: CandleBlockType::MagentaCandle,
                candles: 1i32,
                lit: false,
                waterlogged: false,
            } => Ok(21804u32),
            CandleBlock {
                block_type: CandleBlockType::MagentaCandle,
                candles: 2i32,
                lit: true,
                waterlogged: true,
            } => Ok(21805u32),
            CandleBlock {
                block_type: CandleBlockType::MagentaCandle,
                candles: 2i32,
                lit: true,
                waterlogged: false,
            } => Ok(21806u32),
            CandleBlock {
                block_type: CandleBlockType::MagentaCandle,
                candles: 2i32,
                lit: false,
                waterlogged: true,
            } => Ok(21807u32),
            CandleBlock {
                block_type: CandleBlockType::MagentaCandle,
                candles: 2i32,
                lit: false,
                waterlogged: false,
            } => Ok(21808u32),
            CandleBlock {
                block_type: CandleBlockType::MagentaCandle,
                candles: 3i32,
                lit: true,
                waterlogged: true,
            } => Ok(21809u32),
            CandleBlock {
                block_type: CandleBlockType::MagentaCandle,
                candles: 3i32,
                lit: true,
                waterlogged: false,
            } => Ok(21810u32),
            CandleBlock {
                block_type: CandleBlockType::MagentaCandle,
                candles: 3i32,
                lit: false,
                waterlogged: true,
            } => Ok(21811u32),
            CandleBlock {
                block_type: CandleBlockType::MagentaCandle,
                candles: 3i32,
                lit: false,
                waterlogged: false,
            } => Ok(21812u32),
            CandleBlock {
                block_type: CandleBlockType::MagentaCandle,
                candles: 4i32,
                lit: true,
                waterlogged: true,
            } => Ok(21813u32),
            CandleBlock {
                block_type: CandleBlockType::MagentaCandle,
                candles: 4i32,
                lit: true,
                waterlogged: false,
            } => Ok(21814u32),
            CandleBlock {
                block_type: CandleBlockType::MagentaCandle,
                candles: 4i32,
                lit: false,
                waterlogged: true,
            } => Ok(21815u32),
            CandleBlock {
                block_type: CandleBlockType::MagentaCandle,
                candles: 4i32,
                lit: false,
                waterlogged: false,
            } => Ok(21816u32),
            CandleBlock {
                block_type: CandleBlockType::OrangeCandle,
                candles: 1i32,
                lit: true,
                waterlogged: true,
            } => Ok(21785u32),
            CandleBlock {
                block_type: CandleBlockType::OrangeCandle,
                candles: 1i32,
                lit: true,
                waterlogged: false,
            } => Ok(21786u32),
            CandleBlock {
                block_type: CandleBlockType::OrangeCandle,
                candles: 1i32,
                lit: false,
                waterlogged: true,
            } => Ok(21787u32),
            CandleBlock {
                block_type: CandleBlockType::OrangeCandle,
                candles: 1i32,
                lit: false,
                waterlogged: false,
            } => Ok(21788u32),
            CandleBlock {
                block_type: CandleBlockType::OrangeCandle,
                candles: 2i32,
                lit: true,
                waterlogged: true,
            } => Ok(21789u32),
            CandleBlock {
                block_type: CandleBlockType::OrangeCandle,
                candles: 2i32,
                lit: true,
                waterlogged: false,
            } => Ok(21790u32),
            CandleBlock {
                block_type: CandleBlockType::OrangeCandle,
                candles: 2i32,
                lit: false,
                waterlogged: true,
            } => Ok(21791u32),
            CandleBlock {
                block_type: CandleBlockType::OrangeCandle,
                candles: 2i32,
                lit: false,
                waterlogged: false,
            } => Ok(21792u32),
            CandleBlock {
                block_type: CandleBlockType::OrangeCandle,
                candles: 3i32,
                lit: true,
                waterlogged: true,
            } => Ok(21793u32),
            CandleBlock {
                block_type: CandleBlockType::OrangeCandle,
                candles: 3i32,
                lit: true,
                waterlogged: false,
            } => Ok(21794u32),
            CandleBlock {
                block_type: CandleBlockType::OrangeCandle,
                candles: 3i32,
                lit: false,
                waterlogged: true,
            } => Ok(21795u32),
            CandleBlock {
                block_type: CandleBlockType::OrangeCandle,
                candles: 3i32,
                lit: false,
                waterlogged: false,
            } => Ok(21796u32),
            CandleBlock {
                block_type: CandleBlockType::OrangeCandle,
                candles: 4i32,
                lit: true,
                waterlogged: true,
            } => Ok(21797u32),
            CandleBlock {
                block_type: CandleBlockType::OrangeCandle,
                candles: 4i32,
                lit: true,
                waterlogged: false,
            } => Ok(21798u32),
            CandleBlock {
                block_type: CandleBlockType::OrangeCandle,
                candles: 4i32,
                lit: false,
                waterlogged: true,
            } => Ok(21799u32),
            CandleBlock {
                block_type: CandleBlockType::OrangeCandle,
                candles: 4i32,
                lit: false,
                waterlogged: false,
            } => Ok(21800u32),
            CandleBlock {
                block_type: CandleBlockType::PinkCandle,
                candles: 1i32,
                lit: true,
                waterlogged: true,
            } => Ok(21865u32),
            CandleBlock {
                block_type: CandleBlockType::PinkCandle,
                candles: 1i32,
                lit: true,
                waterlogged: false,
            } => Ok(21866u32),
            CandleBlock {
                block_type: CandleBlockType::PinkCandle,
                candles: 1i32,
                lit: false,
                waterlogged: true,
            } => Ok(21867u32),
            CandleBlock {
                block_type: CandleBlockType::PinkCandle,
                candles: 1i32,
                lit: false,
                waterlogged: false,
            } => Ok(21868u32),
            CandleBlock {
                block_type: CandleBlockType::PinkCandle,
                candles: 2i32,
                lit: true,
                waterlogged: true,
            } => Ok(21869u32),
            CandleBlock {
                block_type: CandleBlockType::PinkCandle,
                candles: 2i32,
                lit: true,
                waterlogged: false,
            } => Ok(21870u32),
            CandleBlock {
                block_type: CandleBlockType::PinkCandle,
                candles: 2i32,
                lit: false,
                waterlogged: true,
            } => Ok(21871u32),
            CandleBlock {
                block_type: CandleBlockType::PinkCandle,
                candles: 2i32,
                lit: false,
                waterlogged: false,
            } => Ok(21872u32),
            CandleBlock {
                block_type: CandleBlockType::PinkCandle,
                candles: 3i32,
                lit: true,
                waterlogged: true,
            } => Ok(21873u32),
            CandleBlock {
                block_type: CandleBlockType::PinkCandle,
                candles: 3i32,
                lit: true,
                waterlogged: false,
            } => Ok(21874u32),
            CandleBlock {
                block_type: CandleBlockType::PinkCandle,
                candles: 3i32,
                lit: false,
                waterlogged: true,
            } => Ok(21875u32),
            CandleBlock {
                block_type: CandleBlockType::PinkCandle,
                candles: 3i32,
                lit: false,
                waterlogged: false,
            } => Ok(21876u32),
            CandleBlock {
                block_type: CandleBlockType::PinkCandle,
                candles: 4i32,
                lit: true,
                waterlogged: true,
            } => Ok(21877u32),
            CandleBlock {
                block_type: CandleBlockType::PinkCandle,
                candles: 4i32,
                lit: true,
                waterlogged: false,
            } => Ok(21878u32),
            CandleBlock {
                block_type: CandleBlockType::PinkCandle,
                candles: 4i32,
                lit: false,
                waterlogged: true,
            } => Ok(21879u32),
            CandleBlock {
                block_type: CandleBlockType::PinkCandle,
                candles: 4i32,
                lit: false,
                waterlogged: false,
            } => Ok(21880u32),
            CandleBlock {
                block_type: CandleBlockType::PurpleCandle,
                candles: 1i32,
                lit: true,
                waterlogged: true,
            } => Ok(21929u32),
            CandleBlock {
                block_type: CandleBlockType::PurpleCandle,
                candles: 1i32,
                lit: true,
                waterlogged: false,
            } => Ok(21930u32),
            CandleBlock {
                block_type: CandleBlockType::PurpleCandle,
                candles: 1i32,
                lit: false,
                waterlogged: true,
            } => Ok(21931u32),
            CandleBlock {
                block_type: CandleBlockType::PurpleCandle,
                candles: 1i32,
                lit: false,
                waterlogged: false,
            } => Ok(21932u32),
            CandleBlock {
                block_type: CandleBlockType::PurpleCandle,
                candles: 2i32,
                lit: true,
                waterlogged: true,
            } => Ok(21933u32),
            CandleBlock {
                block_type: CandleBlockType::PurpleCandle,
                candles: 2i32,
                lit: true,
                waterlogged: false,
            } => Ok(21934u32),
            CandleBlock {
                block_type: CandleBlockType::PurpleCandle,
                candles: 2i32,
                lit: false,
                waterlogged: true,
            } => Ok(21935u32),
            CandleBlock {
                block_type: CandleBlockType::PurpleCandle,
                candles: 2i32,
                lit: false,
                waterlogged: false,
            } => Ok(21936u32),
            CandleBlock {
                block_type: CandleBlockType::PurpleCandle,
                candles: 3i32,
                lit: true,
                waterlogged: true,
            } => Ok(21937u32),
            CandleBlock {
                block_type: CandleBlockType::PurpleCandle,
                candles: 3i32,
                lit: true,
                waterlogged: false,
            } => Ok(21938u32),
            CandleBlock {
                block_type: CandleBlockType::PurpleCandle,
                candles: 3i32,
                lit: false,
                waterlogged: true,
            } => Ok(21939u32),
            CandleBlock {
                block_type: CandleBlockType::PurpleCandle,
                candles: 3i32,
                lit: false,
                waterlogged: false,
            } => Ok(21940u32),
            CandleBlock {
                block_type: CandleBlockType::PurpleCandle,
                candles: 4i32,
                lit: true,
                waterlogged: true,
            } => Ok(21941u32),
            CandleBlock {
                block_type: CandleBlockType::PurpleCandle,
                candles: 4i32,
                lit: true,
                waterlogged: false,
            } => Ok(21942u32),
            CandleBlock {
                block_type: CandleBlockType::PurpleCandle,
                candles: 4i32,
                lit: false,
                waterlogged: true,
            } => Ok(21943u32),
            CandleBlock {
                block_type: CandleBlockType::PurpleCandle,
                candles: 4i32,
                lit: false,
                waterlogged: false,
            } => Ok(21944u32),
            CandleBlock {
                block_type: CandleBlockType::RedCandle,
                candles: 1i32,
                lit: true,
                waterlogged: true,
            } => Ok(21993u32),
            CandleBlock {
                block_type: CandleBlockType::RedCandle,
                candles: 1i32,
                lit: true,
                waterlogged: false,
            } => Ok(21994u32),
            CandleBlock {
                block_type: CandleBlockType::RedCandle,
                candles: 1i32,
                lit: false,
                waterlogged: true,
            } => Ok(21995u32),
            CandleBlock {
                block_type: CandleBlockType::RedCandle,
                candles: 1i32,
                lit: false,
                waterlogged: false,
            } => Ok(21996u32),
            CandleBlock {
                block_type: CandleBlockType::RedCandle,
                candles: 2i32,
                lit: true,
                waterlogged: true,
            } => Ok(21997u32),
            CandleBlock {
                block_type: CandleBlockType::RedCandle,
                candles: 2i32,
                lit: true,
                waterlogged: false,
            } => Ok(21998u32),
            CandleBlock {
                block_type: CandleBlockType::RedCandle,
                candles: 2i32,
                lit: false,
                waterlogged: true,
            } => Ok(21999u32),
            CandleBlock {
                block_type: CandleBlockType::RedCandle,
                candles: 2i32,
                lit: false,
                waterlogged: false,
            } => Ok(22000u32),
            CandleBlock {
                block_type: CandleBlockType::RedCandle,
                candles: 3i32,
                lit: true,
                waterlogged: true,
            } => Ok(22001u32),
            CandleBlock {
                block_type: CandleBlockType::RedCandle,
                candles: 3i32,
                lit: true,
                waterlogged: false,
            } => Ok(22002u32),
            CandleBlock {
                block_type: CandleBlockType::RedCandle,
                candles: 3i32,
                lit: false,
                waterlogged: true,
            } => Ok(22003u32),
            CandleBlock {
                block_type: CandleBlockType::RedCandle,
                candles: 3i32,
                lit: false,
                waterlogged: false,
            } => Ok(22004u32),
            CandleBlock {
                block_type: CandleBlockType::RedCandle,
                candles: 4i32,
                lit: true,
                waterlogged: true,
            } => Ok(22005u32),
            CandleBlock {
                block_type: CandleBlockType::RedCandle,
                candles: 4i32,
                lit: true,
                waterlogged: false,
            } => Ok(22006u32),
            CandleBlock {
                block_type: CandleBlockType::RedCandle,
                candles: 4i32,
                lit: false,
                waterlogged: true,
            } => Ok(22007u32),
            CandleBlock {
                block_type: CandleBlockType::RedCandle,
                candles: 4i32,
                lit: false,
                waterlogged: false,
            } => Ok(22008u32),
            CandleBlock {
                block_type: CandleBlockType::WhiteCandle,
                candles: 1i32,
                lit: true,
                waterlogged: true,
            } => Ok(21769u32),
            CandleBlock {
                block_type: CandleBlockType::WhiteCandle,
                candles: 1i32,
                lit: true,
                waterlogged: false,
            } => Ok(21770u32),
            CandleBlock {
                block_type: CandleBlockType::WhiteCandle,
                candles: 1i32,
                lit: false,
                waterlogged: true,
            } => Ok(21771u32),
            CandleBlock {
                block_type: CandleBlockType::WhiteCandle,
                candles: 1i32,
                lit: false,
                waterlogged: false,
            } => Ok(21772u32),
            CandleBlock {
                block_type: CandleBlockType::WhiteCandle,
                candles: 2i32,
                lit: true,
                waterlogged: true,
            } => Ok(21773u32),
            CandleBlock {
                block_type: CandleBlockType::WhiteCandle,
                candles: 2i32,
                lit: true,
                waterlogged: false,
            } => Ok(21774u32),
            CandleBlock {
                block_type: CandleBlockType::WhiteCandle,
                candles: 2i32,
                lit: false,
                waterlogged: true,
            } => Ok(21775u32),
            CandleBlock {
                block_type: CandleBlockType::WhiteCandle,
                candles: 2i32,
                lit: false,
                waterlogged: false,
            } => Ok(21776u32),
            CandleBlock {
                block_type: CandleBlockType::WhiteCandle,
                candles: 3i32,
                lit: true,
                waterlogged: true,
            } => Ok(21777u32),
            CandleBlock {
                block_type: CandleBlockType::WhiteCandle,
                candles: 3i32,
                lit: true,
                waterlogged: false,
            } => Ok(21778u32),
            CandleBlock {
                block_type: CandleBlockType::WhiteCandle,
                candles: 3i32,
                lit: false,
                waterlogged: true,
            } => Ok(21779u32),
            CandleBlock {
                block_type: CandleBlockType::WhiteCandle,
                candles: 3i32,
                lit: false,
                waterlogged: false,
            } => Ok(21780u32),
            CandleBlock {
                block_type: CandleBlockType::WhiteCandle,
                candles: 4i32,
                lit: true,
                waterlogged: true,
            } => Ok(21781u32),
            CandleBlock {
                block_type: CandleBlockType::WhiteCandle,
                candles: 4i32,
                lit: true,
                waterlogged: false,
            } => Ok(21782u32),
            CandleBlock {
                block_type: CandleBlockType::WhiteCandle,
                candles: 4i32,
                lit: false,
                waterlogged: true,
            } => Ok(21783u32),
            CandleBlock {
                block_type: CandleBlockType::WhiteCandle,
                candles: 4i32,
                lit: false,
                waterlogged: false,
            } => Ok(21784u32),
            CandleBlock {
                block_type: CandleBlockType::YellowCandle,
                candles: 1i32,
                lit: true,
                waterlogged: true,
            } => Ok(21833u32),
            CandleBlock {
                block_type: CandleBlockType::YellowCandle,
                candles: 1i32,
                lit: true,
                waterlogged: false,
            } => Ok(21834u32),
            CandleBlock {
                block_type: CandleBlockType::YellowCandle,
                candles: 1i32,
                lit: false,
                waterlogged: true,
            } => Ok(21835u32),
            CandleBlock {
                block_type: CandleBlockType::YellowCandle,
                candles: 1i32,
                lit: false,
                waterlogged: false,
            } => Ok(21836u32),
            CandleBlock {
                block_type: CandleBlockType::YellowCandle,
                candles: 2i32,
                lit: true,
                waterlogged: true,
            } => Ok(21837u32),
            CandleBlock {
                block_type: CandleBlockType::YellowCandle,
                candles: 2i32,
                lit: true,
                waterlogged: false,
            } => Ok(21838u32),
            CandleBlock {
                block_type: CandleBlockType::YellowCandle,
                candles: 2i32,
                lit: false,
                waterlogged: true,
            } => Ok(21839u32),
            CandleBlock {
                block_type: CandleBlockType::YellowCandle,
                candles: 2i32,
                lit: false,
                waterlogged: false,
            } => Ok(21840u32),
            CandleBlock {
                block_type: CandleBlockType::YellowCandle,
                candles: 3i32,
                lit: true,
                waterlogged: true,
            } => Ok(21841u32),
            CandleBlock {
                block_type: CandleBlockType::YellowCandle,
                candles: 3i32,
                lit: true,
                waterlogged: false,
            } => Ok(21842u32),
            CandleBlock {
                block_type: CandleBlockType::YellowCandle,
                candles: 3i32,
                lit: false,
                waterlogged: true,
            } => Ok(21843u32),
            CandleBlock {
                block_type: CandleBlockType::YellowCandle,
                candles: 3i32,
                lit: false,
                waterlogged: false,
            } => Ok(21844u32),
            CandleBlock {
                block_type: CandleBlockType::YellowCandle,
                candles: 4i32,
                lit: true,
                waterlogged: true,
            } => Ok(21845u32),
            CandleBlock {
                block_type: CandleBlockType::YellowCandle,
                candles: 4i32,
                lit: true,
                waterlogged: false,
            } => Ok(21846u32),
            CandleBlock {
                block_type: CandleBlockType::YellowCandle,
                candles: 4i32,
                lit: false,
                waterlogged: true,
            } => Ok(21847u32),
            CandleBlock {
                block_type: CandleBlockType::YellowCandle,
                candles: 4i32,
                lit: false,
                waterlogged: false,
            } => Ok(21848u32),
            _ => Err(()),
        }
    }
}
