#[allow(unused_imports)]
use ferrumc_block_properties::*;
#[allow(dead_code)]
#[derive(Clone, Debug)]
pub enum FenceGateBlockType {
    AcaciaFenceGate,
    BambooFenceGate,
    BirchFenceGate,
    CherryFenceGate,
    CrimsonFenceGate,
    DarkOakFenceGate,
    JungleFenceGate,
    MangroveFenceGate,
    OakFenceGate,
    PaleOakFenceGate,
    SpruceFenceGate,
    WarpedFenceGate,
}
#[allow(dead_code)]
#[derive(Clone, Debug)]
pub struct FenceGateBlock {
    pub block_type: FenceGateBlockType,
    pub facing: Direction,
    pub in_wall: bool,
    pub open: bool,
    pub powered: bool,
}
impl TryInto<u32> for FenceGateBlock {
    type Error = ();
    fn try_into(self) -> Result<u32, Self::Error> {
        #[allow(unreachable_patterns)]
        match self {
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12301u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12302u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12303u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12304u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12305u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12306u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12307u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12308u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12309u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12310u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12311u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12312u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12313u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12314u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12315u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12316u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12317u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12318u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12319u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12320u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12321u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12322u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12323u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12324u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12325u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12326u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12327u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12328u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12329u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12330u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12331u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::AcaciaFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12332u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12461u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12462u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12463u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12464u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12465u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12466u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12467u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12468u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12469u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12470u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12471u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12472u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12473u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12474u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12475u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12476u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12477u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12478u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12479u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12480u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12481u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12482u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12483u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12484u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12485u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12486u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12487u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12488u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12489u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12490u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12491u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BambooFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12492u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12237u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12238u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12239u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12240u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12241u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12242u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12243u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12244u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12245u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12246u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12247u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12248u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12249u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12250u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12251u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12252u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12253u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12254u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12255u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12256u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12257u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12258u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12259u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12260u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12261u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12262u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12263u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12264u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12265u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12266u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12267u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::BirchFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12268u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12333u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12334u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12335u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12336u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12337u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12338u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12339u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12340u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12341u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12342u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12343u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12344u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12345u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12346u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12347u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12348u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12349u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12350u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12351u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12352u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12353u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12354u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12355u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12356u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12357u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12358u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12359u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12360u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12361u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12362u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12363u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CherryFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12364u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(19899u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(19900u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(19901u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(19902u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(19903u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(19904u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(19905u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(19906u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(19907u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(19908u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(19909u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(19910u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(19911u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(19912u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(19913u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(19914u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(19915u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(19916u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(19917u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(19918u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(19919u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(19920u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(19921u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(19922u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(19923u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(19924u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(19925u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(19926u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(19927u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(19928u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(19929u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::CrimsonFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(19930u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12365u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12366u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12367u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12368u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12369u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12370u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12371u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12372u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12373u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12374u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12375u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12376u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12377u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12378u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12379u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12380u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12381u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12382u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12383u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12384u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12385u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12386u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12387u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12388u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12389u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12390u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12391u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12392u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12393u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12394u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12395u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::DarkOakFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12396u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12269u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12270u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12271u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12272u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12273u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12274u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12275u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12276u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12277u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12278u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12279u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12280u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12281u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12282u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12283u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12284u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12285u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12286u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12287u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12288u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12289u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12290u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12291u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12292u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12293u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12294u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12295u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12296u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12297u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12298u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12299u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::JungleFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12300u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12429u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12430u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12431u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12432u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12433u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12434u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12435u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12436u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12437u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12438u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12439u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12440u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12441u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12442u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12443u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12444u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12445u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12446u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12447u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12448u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12449u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12450u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12451u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12452u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12453u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12454u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12455u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12456u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12457u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12458u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12459u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::MangroveFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12460u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(7368u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(7369u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(7370u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(7371u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(7372u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(7373u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(7374u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(7375u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(7376u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(7377u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(7378u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(7379u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(7380u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(7381u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(7382u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(7383u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(7384u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(7385u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(7386u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(7387u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(7388u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(7389u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(7390u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(7391u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(7392u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(7393u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(7394u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(7395u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(7396u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(7397u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(7398u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::OakFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(7399u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12397u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12398u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12399u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12400u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12401u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12402u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12403u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12404u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12405u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12406u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12407u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12408u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12409u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12410u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12411u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12412u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12413u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12414u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12415u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12416u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12417u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12418u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12419u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12420u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12421u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12422u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12423u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12424u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12425u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12426u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12427u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::PaleOakFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12428u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12205u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12206u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12207u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12208u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12209u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12210u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12211u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12212u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12213u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12214u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12215u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12216u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12217u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12218u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12219u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12220u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12221u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12222u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12223u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12224u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12225u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12226u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12227u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12228u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(12229u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(12230u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(12231u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(12232u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(12233u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(12234u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(12235u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::SpruceFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(12236u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(19931u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(19932u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(19933u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::North,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(19934u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(19935u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(19936u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(19937u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::North,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(19938u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(19939u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(19940u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(19941u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::South,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(19942u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(19943u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(19944u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(19945u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::South,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(19946u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(19947u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(19948u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(19949u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::West,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(19950u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(19951u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(19952u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(19953u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::West,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(19954u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: true,
            } => Ok(19955u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: true,
                powered: false,
            } => Ok(19956u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: true,
            } => Ok(19957u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::East,
                in_wall: true,
                open: false,
                powered: false,
            } => Ok(19958u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: true,
            } => Ok(19959u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: true,
                powered: false,
            } => Ok(19960u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: true,
            } => Ok(19961u32),
            FenceGateBlock {
                block_type: FenceGateBlockType::WarpedFenceGate,
                facing: Direction::East,
                in_wall: false,
                open: false,
                powered: false,
            } => Ok(19962u32),
            _ => Err(()),
        }
    }
}
