#[allow(unused_imports)]
use ferrumc_block_properties::*;
#[allow(dead_code)]
pub enum GeneratedStruct89Type {
    ActivatorRail,
    DetectorRail,
    PoweredRail,
}
#[allow(dead_code)]
pub struct GeneratedStruct89 {
    pub block_type: GeneratedStruct89Type,
    pub powered: bool,
    pub shape: RailShape,
    pub waterlogged: bool,
}
impl TryFrom<u32> for GeneratedStruct89 {
    type Error = ();
    fn try_from(value: u32) -> Result<Self, Self::Error> {
        match value {
            10129u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::NorthSouth,
                waterlogged: true,
            }),
            10130u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::NorthSouth,
                waterlogged: false,
            }),
            10131u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::EastWest,
                waterlogged: true,
            }),
            10132u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::EastWest,
                waterlogged: false,
            }),
            10133u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::AscendingEast,
                waterlogged: true,
            }),
            10134u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::AscendingEast,
                waterlogged: false,
            }),
            10135u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::AscendingWest,
                waterlogged: true,
            }),
            10136u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::AscendingWest,
                waterlogged: false,
            }),
            10137u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::AscendingNorth,
                waterlogged: true,
            }),
            10138u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::AscendingNorth,
                waterlogged: false,
            }),
            10139u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::AscendingSouth,
                waterlogged: true,
            }),
            10140u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::AscendingSouth,
                waterlogged: false,
            }),
            10141u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::NorthSouth,
                waterlogged: true,
            }),
            10142u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::NorthSouth,
                waterlogged: false,
            }),
            10143u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::EastWest,
                waterlogged: true,
            }),
            10144u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::EastWest,
                waterlogged: false,
            }),
            10145u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::AscendingEast,
                waterlogged: true,
            }),
            10146u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::AscendingEast,
                waterlogged: false,
            }),
            10147u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::AscendingWest,
                waterlogged: true,
            }),
            10148u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::AscendingWest,
                waterlogged: false,
            }),
            10149u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::AscendingNorth,
                waterlogged: true,
            }),
            10150u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::AscendingNorth,
                waterlogged: false,
            }),
            10151u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::AscendingSouth,
                waterlogged: true,
            }),
            10152u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::AscendingSouth,
                waterlogged: false,
            }),
            2011u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::NorthSouth,
                waterlogged: true,
            }),
            2012u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::NorthSouth,
                waterlogged: false,
            }),
            2013u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::EastWest,
                waterlogged: true,
            }),
            2014u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::EastWest,
                waterlogged: false,
            }),
            2015u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::AscendingEast,
                waterlogged: true,
            }),
            2016u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::AscendingEast,
                waterlogged: false,
            }),
            2017u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::AscendingWest,
                waterlogged: true,
            }),
            2018u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::AscendingWest,
                waterlogged: false,
            }),
            2019u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::AscendingNorth,
                waterlogged: true,
            }),
            2020u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::AscendingNorth,
                waterlogged: false,
            }),
            2021u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::AscendingSouth,
                waterlogged: true,
            }),
            2022u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::AscendingSouth,
                waterlogged: false,
            }),
            2023u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::NorthSouth,
                waterlogged: true,
            }),
            2024u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::NorthSouth,
                waterlogged: false,
            }),
            2025u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::EastWest,
                waterlogged: true,
            }),
            2026u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::EastWest,
                waterlogged: false,
            }),
            2027u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::AscendingEast,
                waterlogged: true,
            }),
            2028u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::AscendingEast,
                waterlogged: false,
            }),
            2029u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::AscendingWest,
                waterlogged: true,
            }),
            2030u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::AscendingWest,
                waterlogged: false,
            }),
            2031u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::AscendingNorth,
                waterlogged: true,
            }),
            2032u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::AscendingNorth,
                waterlogged: false,
            }),
            2033u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::AscendingSouth,
                waterlogged: true,
            }),
            2034u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::AscendingSouth,
                waterlogged: false,
            }),
            1987u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::NorthSouth,
                waterlogged: true,
            }),
            1988u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::NorthSouth,
                waterlogged: false,
            }),
            1989u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::EastWest,
                waterlogged: true,
            }),
            1990u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::EastWest,
                waterlogged: false,
            }),
            1991u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::AscendingEast,
                waterlogged: true,
            }),
            1992u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::AscendingEast,
                waterlogged: false,
            }),
            1993u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::AscendingWest,
                waterlogged: true,
            }),
            1994u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::AscendingWest,
                waterlogged: false,
            }),
            1995u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::AscendingNorth,
                waterlogged: true,
            }),
            1996u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::AscendingNorth,
                waterlogged: false,
            }),
            1997u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::AscendingSouth,
                waterlogged: true,
            }),
            1998u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::AscendingSouth,
                waterlogged: false,
            }),
            1999u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::NorthSouth,
                waterlogged: true,
            }),
            2000u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::NorthSouth,
                waterlogged: false,
            }),
            2001u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::EastWest,
                waterlogged: true,
            }),
            2002u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::EastWest,
                waterlogged: false,
            }),
            2003u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::AscendingEast,
                waterlogged: true,
            }),
            2004u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::AscendingEast,
                waterlogged: false,
            }),
            2005u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::AscendingWest,
                waterlogged: true,
            }),
            2006u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::AscendingWest,
                waterlogged: false,
            }),
            2007u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::AscendingNorth,
                waterlogged: true,
            }),
            2008u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::AscendingNorth,
                waterlogged: false,
            }),
            2009u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::AscendingSouth,
                waterlogged: true,
            }),
            2010u32 => Ok(GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::AscendingSouth,
                waterlogged: false,
            }),
            _ => Err(()),
        }
    }
}
impl TryInto<u32> for GeneratedStruct89 {
    type Error = ();
    fn try_into(self) -> Result<u32, Self::Error> {
        #[allow(unreachable_patterns)]
        match self {
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::NorthSouth,
                waterlogged: true,
            } => Ok(10129u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::NorthSouth,
                waterlogged: false,
            } => Ok(10130u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::EastWest,
                waterlogged: true,
            } => Ok(10131u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::EastWest,
                waterlogged: false,
            } => Ok(10132u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::AscendingEast,
                waterlogged: true,
            } => Ok(10133u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::AscendingEast,
                waterlogged: false,
            } => Ok(10134u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::AscendingWest,
                waterlogged: true,
            } => Ok(10135u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::AscendingWest,
                waterlogged: false,
            } => Ok(10136u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::AscendingNorth,
                waterlogged: true,
            } => Ok(10137u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::AscendingNorth,
                waterlogged: false,
            } => Ok(10138u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::AscendingSouth,
                waterlogged: true,
            } => Ok(10139u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: true,
                shape: RailShape::AscendingSouth,
                waterlogged: false,
            } => Ok(10140u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::NorthSouth,
                waterlogged: true,
            } => Ok(10141u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::NorthSouth,
                waterlogged: false,
            } => Ok(10142u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::EastWest,
                waterlogged: true,
            } => Ok(10143u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::EastWest,
                waterlogged: false,
            } => Ok(10144u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::AscendingEast,
                waterlogged: true,
            } => Ok(10145u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::AscendingEast,
                waterlogged: false,
            } => Ok(10146u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::AscendingWest,
                waterlogged: true,
            } => Ok(10147u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::AscendingWest,
                waterlogged: false,
            } => Ok(10148u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::AscendingNorth,
                waterlogged: true,
            } => Ok(10149u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::AscendingNorth,
                waterlogged: false,
            } => Ok(10150u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::AscendingSouth,
                waterlogged: true,
            } => Ok(10151u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::ActivatorRail,
                powered: false,
                shape: RailShape::AscendingSouth,
                waterlogged: false,
            } => Ok(10152u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::NorthSouth,
                waterlogged: true,
            } => Ok(2011u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::NorthSouth,
                waterlogged: false,
            } => Ok(2012u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::EastWest,
                waterlogged: true,
            } => Ok(2013u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::EastWest,
                waterlogged: false,
            } => Ok(2014u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::AscendingEast,
                waterlogged: true,
            } => Ok(2015u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::AscendingEast,
                waterlogged: false,
            } => Ok(2016u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::AscendingWest,
                waterlogged: true,
            } => Ok(2017u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::AscendingWest,
                waterlogged: false,
            } => Ok(2018u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::AscendingNorth,
                waterlogged: true,
            } => Ok(2019u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::AscendingNorth,
                waterlogged: false,
            } => Ok(2020u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::AscendingSouth,
                waterlogged: true,
            } => Ok(2021u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: true,
                shape: RailShape::AscendingSouth,
                waterlogged: false,
            } => Ok(2022u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::NorthSouth,
                waterlogged: true,
            } => Ok(2023u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::NorthSouth,
                waterlogged: false,
            } => Ok(2024u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::EastWest,
                waterlogged: true,
            } => Ok(2025u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::EastWest,
                waterlogged: false,
            } => Ok(2026u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::AscendingEast,
                waterlogged: true,
            } => Ok(2027u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::AscendingEast,
                waterlogged: false,
            } => Ok(2028u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::AscendingWest,
                waterlogged: true,
            } => Ok(2029u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::AscendingWest,
                waterlogged: false,
            } => Ok(2030u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::AscendingNorth,
                waterlogged: true,
            } => Ok(2031u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::AscendingNorth,
                waterlogged: false,
            } => Ok(2032u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::AscendingSouth,
                waterlogged: true,
            } => Ok(2033u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::DetectorRail,
                powered: false,
                shape: RailShape::AscendingSouth,
                waterlogged: false,
            } => Ok(2034u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::NorthSouth,
                waterlogged: true,
            } => Ok(1987u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::NorthSouth,
                waterlogged: false,
            } => Ok(1988u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::EastWest,
                waterlogged: true,
            } => Ok(1989u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::EastWest,
                waterlogged: false,
            } => Ok(1990u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::AscendingEast,
                waterlogged: true,
            } => Ok(1991u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::AscendingEast,
                waterlogged: false,
            } => Ok(1992u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::AscendingWest,
                waterlogged: true,
            } => Ok(1993u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::AscendingWest,
                waterlogged: false,
            } => Ok(1994u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::AscendingNorth,
                waterlogged: true,
            } => Ok(1995u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::AscendingNorth,
                waterlogged: false,
            } => Ok(1996u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::AscendingSouth,
                waterlogged: true,
            } => Ok(1997u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: true,
                shape: RailShape::AscendingSouth,
                waterlogged: false,
            } => Ok(1998u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::NorthSouth,
                waterlogged: true,
            } => Ok(1999u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::NorthSouth,
                waterlogged: false,
            } => Ok(2000u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::EastWest,
                waterlogged: true,
            } => Ok(2001u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::EastWest,
                waterlogged: false,
            } => Ok(2002u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::AscendingEast,
                waterlogged: true,
            } => Ok(2003u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::AscendingEast,
                waterlogged: false,
            } => Ok(2004u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::AscendingWest,
                waterlogged: true,
            } => Ok(2005u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::AscendingWest,
                waterlogged: false,
            } => Ok(2006u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::AscendingNorth,
                waterlogged: true,
            } => Ok(2007u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::AscendingNorth,
                waterlogged: false,
            } => Ok(2008u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::AscendingSouth,
                waterlogged: true,
            } => Ok(2009u32),
            GeneratedStruct89 {
                block_type: GeneratedStruct89Type::PoweredRail,
                powered: false,
                shape: RailShape::AscendingSouth,
                waterlogged: false,
            } => Ok(2010u32),
            _ => Err(()),
        }
    }
}
