#[allow(unused_imports)]
use ferrumc_block_properties::*;
#[allow(dead_code)]
#[derive(Clone, Debug)]
pub struct GeneratedStruct25 {
    pub delay: i32,
    pub facing: Direction,
    pub locked: bool,
    pub powered: bool,
}
impl TryInto<u32> for GeneratedStruct25 {
    type Error = ();
    fn try_into(self) -> Result<u32, Self::Error> {
        #[allow(unreachable_patterns)]
        match self {
            GeneratedStruct25 {
                delay: 1i32,
                facing: Direction::North,
                locked: true,
                powered: true,
            } => Ok(6060u32),
            GeneratedStruct25 {
                delay: 1i32,
                facing: Direction::North,
                locked: true,
                powered: false,
            } => Ok(6061u32),
            GeneratedStruct25 {
                delay: 1i32,
                facing: Direction::North,
                locked: false,
                powered: true,
            } => Ok(6062u32),
            GeneratedStruct25 {
                delay: 1i32,
                facing: Direction::North,
                locked: false,
                powered: false,
            } => Ok(6063u32),
            GeneratedStruct25 {
                delay: 1i32,
                facing: Direction::South,
                locked: true,
                powered: true,
            } => Ok(6064u32),
            GeneratedStruct25 {
                delay: 1i32,
                facing: Direction::South,
                locked: true,
                powered: false,
            } => Ok(6065u32),
            GeneratedStruct25 {
                delay: 1i32,
                facing: Direction::South,
                locked: false,
                powered: true,
            } => Ok(6066u32),
            GeneratedStruct25 {
                delay: 1i32,
                facing: Direction::South,
                locked: false,
                powered: false,
            } => Ok(6067u32),
            GeneratedStruct25 {
                delay: 1i32,
                facing: Direction::West,
                locked: true,
                powered: true,
            } => Ok(6068u32),
            GeneratedStruct25 {
                delay: 1i32,
                facing: Direction::West,
                locked: true,
                powered: false,
            } => Ok(6069u32),
            GeneratedStruct25 {
                delay: 1i32,
                facing: Direction::West,
                locked: false,
                powered: true,
            } => Ok(6070u32),
            GeneratedStruct25 {
                delay: 1i32,
                facing: Direction::West,
                locked: false,
                powered: false,
            } => Ok(6071u32),
            GeneratedStruct25 {
                delay: 1i32,
                facing: Direction::East,
                locked: true,
                powered: true,
            } => Ok(6072u32),
            GeneratedStruct25 {
                delay: 1i32,
                facing: Direction::East,
                locked: true,
                powered: false,
            } => Ok(6073u32),
            GeneratedStruct25 {
                delay: 1i32,
                facing: Direction::East,
                locked: false,
                powered: true,
            } => Ok(6074u32),
            GeneratedStruct25 {
                delay: 1i32,
                facing: Direction::East,
                locked: false,
                powered: false,
            } => Ok(6075u32),
            GeneratedStruct25 {
                delay: 2i32,
                facing: Direction::North,
                locked: true,
                powered: true,
            } => Ok(6076u32),
            GeneratedStruct25 {
                delay: 2i32,
                facing: Direction::North,
                locked: true,
                powered: false,
            } => Ok(6077u32),
            GeneratedStruct25 {
                delay: 2i32,
                facing: Direction::North,
                locked: false,
                powered: true,
            } => Ok(6078u32),
            GeneratedStruct25 {
                delay: 2i32,
                facing: Direction::North,
                locked: false,
                powered: false,
            } => Ok(6079u32),
            GeneratedStruct25 {
                delay: 2i32,
                facing: Direction::South,
                locked: true,
                powered: true,
            } => Ok(6080u32),
            GeneratedStruct25 {
                delay: 2i32,
                facing: Direction::South,
                locked: true,
                powered: false,
            } => Ok(6081u32),
            GeneratedStruct25 {
                delay: 2i32,
                facing: Direction::South,
                locked: false,
                powered: true,
            } => Ok(6082u32),
            GeneratedStruct25 {
                delay: 2i32,
                facing: Direction::South,
                locked: false,
                powered: false,
            } => Ok(6083u32),
            GeneratedStruct25 {
                delay: 2i32,
                facing: Direction::West,
                locked: true,
                powered: true,
            } => Ok(6084u32),
            GeneratedStruct25 {
                delay: 2i32,
                facing: Direction::West,
                locked: true,
                powered: false,
            } => Ok(6085u32),
            GeneratedStruct25 {
                delay: 2i32,
                facing: Direction::West,
                locked: false,
                powered: true,
            } => Ok(6086u32),
            GeneratedStruct25 {
                delay: 2i32,
                facing: Direction::West,
                locked: false,
                powered: false,
            } => Ok(6087u32),
            GeneratedStruct25 {
                delay: 2i32,
                facing: Direction::East,
                locked: true,
                powered: true,
            } => Ok(6088u32),
            GeneratedStruct25 {
                delay: 2i32,
                facing: Direction::East,
                locked: true,
                powered: false,
            } => Ok(6089u32),
            GeneratedStruct25 {
                delay: 2i32,
                facing: Direction::East,
                locked: false,
                powered: true,
            } => Ok(6090u32),
            GeneratedStruct25 {
                delay: 2i32,
                facing: Direction::East,
                locked: false,
                powered: false,
            } => Ok(6091u32),
            GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::North,
                locked: true,
                powered: true,
            } => Ok(6092u32),
            GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::North,
                locked: true,
                powered: false,
            } => Ok(6093u32),
            GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::North,
                locked: false,
                powered: true,
            } => Ok(6094u32),
            GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::North,
                locked: false,
                powered: false,
            } => Ok(6095u32),
            GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::South,
                locked: true,
                powered: true,
            } => Ok(6096u32),
            GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::South,
                locked: true,
                powered: false,
            } => Ok(6097u32),
            GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::South,
                locked: false,
                powered: true,
            } => Ok(6098u32),
            GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::South,
                locked: false,
                powered: false,
            } => Ok(6099u32),
            GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::West,
                locked: true,
                powered: true,
            } => Ok(6100u32),
            GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::West,
                locked: true,
                powered: false,
            } => Ok(6101u32),
            GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::West,
                locked: false,
                powered: true,
            } => Ok(6102u32),
            GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::West,
                locked: false,
                powered: false,
            } => Ok(6103u32),
            GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::East,
                locked: true,
                powered: true,
            } => Ok(6104u32),
            GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::East,
                locked: true,
                powered: false,
            } => Ok(6105u32),
            GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::East,
                locked: false,
                powered: true,
            } => Ok(6106u32),
            GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::East,
                locked: false,
                powered: false,
            } => Ok(6107u32),
            GeneratedStruct25 {
                delay: 4i32,
                facing: Direction::North,
                locked: true,
                powered: true,
            } => Ok(6108u32),
            GeneratedStruct25 {
                delay: 4i32,
                facing: Direction::North,
                locked: true,
                powered: false,
            } => Ok(6109u32),
            GeneratedStruct25 {
                delay: 4i32,
                facing: Direction::North,
                locked: false,
                powered: true,
            } => Ok(6110u32),
            GeneratedStruct25 {
                delay: 4i32,
                facing: Direction::North,
                locked: false,
                powered: false,
            } => Ok(6111u32),
            GeneratedStruct25 {
                delay: 4i32,
                facing: Direction::South,
                locked: true,
                powered: true,
            } => Ok(6112u32),
            GeneratedStruct25 {
                delay: 4i32,
                facing: Direction::South,
                locked: true,
                powered: false,
            } => Ok(6113u32),
            GeneratedStruct25 {
                delay: 4i32,
                facing: Direction::South,
                locked: false,
                powered: true,
            } => Ok(6114u32),
            GeneratedStruct25 {
                delay: 4i32,
                facing: Direction::South,
                locked: false,
                powered: false,
            } => Ok(6115u32),
            GeneratedStruct25 {
                delay: 4i32,
                facing: Direction::West,
                locked: true,
                powered: true,
            } => Ok(6116u32),
            GeneratedStruct25 {
                delay: 4i32,
                facing: Direction::West,
                locked: true,
                powered: false,
            } => Ok(6117u32),
            GeneratedStruct25 {
                delay: 4i32,
                facing: Direction::West,
                locked: false,
                powered: true,
            } => Ok(6118u32),
            GeneratedStruct25 {
                delay: 4i32,
                facing: Direction::West,
                locked: false,
                powered: false,
            } => Ok(6119u32),
            GeneratedStruct25 {
                delay: 4i32,
                facing: Direction::East,
                locked: true,
                powered: true,
            } => Ok(6120u32),
            GeneratedStruct25 {
                delay: 4i32,
                facing: Direction::East,
                locked: true,
                powered: false,
            } => Ok(6121u32),
            GeneratedStruct25 {
                delay: 4i32,
                facing: Direction::East,
                locked: false,
                powered: true,
            } => Ok(6122u32),
            GeneratedStruct25 {
                delay: 4i32,
                facing: Direction::East,
                locked: false,
                powered: false,
            } => Ok(6123u32),
            _ => Err(()),
        }
    }
}
