#[allow(unused_imports)]
use ferrumc_block_properties::*;
#[allow(dead_code)]
#[derive(Clone, Debug)]
pub struct GeneratedStruct18 {
    pub bottom: bool,
    pub east: WallSide,
    pub north: WallSide,
    pub south: WallSide,
    pub west: WallSide,
}
impl TryInto<u32> for GeneratedStruct18 {
    type Error = ();
    fn try_into(self) -> Result<u32, Self::Error> {
        #[allow(unreachable_patterns)]
        match self {
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::None,
                south: WallSide::None,
                west: WallSide::None,
            } => Ok(27745u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::None,
                south: WallSide::None,
                west: WallSide::Low,
            } => Ok(27746u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::None,
                south: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27747u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::None,
            } => Ok(27748u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::Low,
            } => Ok(27749u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::Tall,
            } => Ok(27750u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::None,
                south: WallSide::Tall,
                west: WallSide::None,
            } => Ok(27751u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::None,
                south: WallSide::Tall,
                west: WallSide::Low,
            } => Ok(27752u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::None,
                south: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27753u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::None,
            } => Ok(27754u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::Low,
            } => Ok(27755u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27756u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::None,
            } => Ok(27757u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::Low,
            } => Ok(27758u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::Tall,
            } => Ok(27759u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::None,
            } => Ok(27760u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::Low,
            } => Ok(27761u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27762u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::None,
            } => Ok(27763u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::Low,
            } => Ok(27764u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27765u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::Tall,
                south: WallSide::Low,
                west: WallSide::None,
            } => Ok(27766u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::Tall,
                south: WallSide::Low,
                west: WallSide::Low,
            } => Ok(27767u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::Tall,
                south: WallSide::Low,
                west: WallSide::Tall,
            } => Ok(27768u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::None,
            } => Ok(27769u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::Low,
            } => Ok(27770u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                north: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27771u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::None,
                south: WallSide::None,
                west: WallSide::None,
            } => Ok(27772u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::None,
                south: WallSide::None,
                west: WallSide::Low,
            } => Ok(27773u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::None,
                south: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27774u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::None,
            } => Ok(27775u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::Low,
            } => Ok(27776u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::Tall,
            } => Ok(27777u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::None,
                south: WallSide::Tall,
                west: WallSide::None,
            } => Ok(27778u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::None,
                south: WallSide::Tall,
                west: WallSide::Low,
            } => Ok(27779u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::None,
                south: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27780u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::None,
            } => Ok(27781u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::Low,
            } => Ok(27782u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27783u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::None,
            } => Ok(27784u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::Low,
            } => Ok(27785u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::Tall,
            } => Ok(27786u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::None,
            } => Ok(27787u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::Low,
            } => Ok(27788u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27789u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::None,
            } => Ok(27790u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::Low,
            } => Ok(27791u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27792u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::Tall,
                south: WallSide::Low,
                west: WallSide::None,
            } => Ok(27793u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::Tall,
                south: WallSide::Low,
                west: WallSide::Low,
            } => Ok(27794u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::Tall,
                south: WallSide::Low,
                west: WallSide::Tall,
            } => Ok(27795u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::None,
            } => Ok(27796u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::Low,
            } => Ok(27797u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27798u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::None,
                south: WallSide::None,
                west: WallSide::None,
            } => Ok(27799u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::None,
                south: WallSide::None,
                west: WallSide::Low,
            } => Ok(27800u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::None,
                south: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27801u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::None,
            } => Ok(27802u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::Low,
            } => Ok(27803u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::Tall,
            } => Ok(27804u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::None,
                south: WallSide::Tall,
                west: WallSide::None,
            } => Ok(27805u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::None,
                south: WallSide::Tall,
                west: WallSide::Low,
            } => Ok(27806u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::None,
                south: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27807u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::None,
            } => Ok(27808u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::Low,
            } => Ok(27809u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27810u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::None,
            } => Ok(27811u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::Low,
            } => Ok(27812u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::Tall,
            } => Ok(27813u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::None,
            } => Ok(27814u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::Low,
            } => Ok(27815u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27816u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::None,
            } => Ok(27817u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::Low,
            } => Ok(27818u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27819u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::Low,
                west: WallSide::None,
            } => Ok(27820u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::Low,
                west: WallSide::Low,
            } => Ok(27821u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::Low,
                west: WallSide::Tall,
            } => Ok(27822u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::None,
            } => Ok(27823u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::Low,
            } => Ok(27824u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27825u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::None,
                south: WallSide::None,
                west: WallSide::None,
            } => Ok(27826u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::None,
                south: WallSide::None,
                west: WallSide::Low,
            } => Ok(27827u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::None,
                south: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27828u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::None,
            } => Ok(27829u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::Low,
            } => Ok(27830u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::Tall,
            } => Ok(27831u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::None,
                south: WallSide::Tall,
                west: WallSide::None,
            } => Ok(27832u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::None,
                south: WallSide::Tall,
                west: WallSide::Low,
            } => Ok(27833u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::None,
                south: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27834u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::None,
            } => Ok(27835u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::Low,
            } => Ok(27836u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27837u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::None,
            } => Ok(27838u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::Low,
            } => Ok(27839u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::Tall,
            } => Ok(27840u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::None,
            } => Ok(27841u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::Low,
            } => Ok(27842u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27843u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::None,
            } => Ok(27844u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::Low,
            } => Ok(27845u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27846u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::Tall,
                south: WallSide::Low,
                west: WallSide::None,
            } => Ok(27847u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::Tall,
                south: WallSide::Low,
                west: WallSide::Low,
            } => Ok(27848u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::Tall,
                south: WallSide::Low,
                west: WallSide::Tall,
            } => Ok(27849u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::None,
            } => Ok(27850u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::Low,
            } => Ok(27851u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27852u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::None,
                south: WallSide::None,
                west: WallSide::None,
            } => Ok(27853u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::None,
                south: WallSide::None,
                west: WallSide::Low,
            } => Ok(27854u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::None,
                south: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27855u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::None,
            } => Ok(27856u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::Low,
            } => Ok(27857u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::Tall,
            } => Ok(27858u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::None,
                south: WallSide::Tall,
                west: WallSide::None,
            } => Ok(27859u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::None,
                south: WallSide::Tall,
                west: WallSide::Low,
            } => Ok(27860u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::None,
                south: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27861u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::None,
            } => Ok(27862u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::Low,
            } => Ok(27863u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27864u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::None,
            } => Ok(27865u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::Low,
            } => Ok(27866u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::Tall,
            } => Ok(27867u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::None,
            } => Ok(27868u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::Low,
            } => Ok(27869u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27870u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::None,
            } => Ok(27871u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::Low,
            } => Ok(27872u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27873u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::Tall,
                south: WallSide::Low,
                west: WallSide::None,
            } => Ok(27874u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::Tall,
                south: WallSide::Low,
                west: WallSide::Low,
            } => Ok(27875u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::Tall,
                south: WallSide::Low,
                west: WallSide::Tall,
            } => Ok(27876u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::None,
            } => Ok(27877u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::Low,
            } => Ok(27878u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                north: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27879u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::None,
                south: WallSide::None,
                west: WallSide::None,
            } => Ok(27880u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::None,
                south: WallSide::None,
                west: WallSide::Low,
            } => Ok(27881u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::None,
                south: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27882u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::None,
            } => Ok(27883u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::Low,
            } => Ok(27884u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::Tall,
            } => Ok(27885u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::None,
                south: WallSide::Tall,
                west: WallSide::None,
            } => Ok(27886u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::None,
                south: WallSide::Tall,
                west: WallSide::Low,
            } => Ok(27887u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::None,
                south: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27888u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::None,
            } => Ok(27889u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::Low,
            } => Ok(27890u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27891u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::None,
            } => Ok(27892u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::Low,
            } => Ok(27893u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::Tall,
            } => Ok(27894u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::None,
            } => Ok(27895u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::Low,
            } => Ok(27896u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27897u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::None,
            } => Ok(27898u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::Low,
            } => Ok(27899u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27900u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::Low,
                west: WallSide::None,
            } => Ok(27901u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::Low,
                west: WallSide::Low,
            } => Ok(27902u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::Low,
                west: WallSide::Tall,
            } => Ok(27903u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::None,
            } => Ok(27904u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::Low,
            } => Ok(27905u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27906u32),
            _ => Err(()),
        }
    }
}
