#[allow(unused_imports)]
use ferrumc_block_properties::*;
#[allow(dead_code)]
#[derive(Clone, Debug)]
pub struct GeneratedStruct56 {
    pub facing: Direction,
    pub power: i32,
    pub sculk_sensor_phase: SculkSensorPhase,
    pub waterlogged: bool,
}
impl TryInto<u32> for GeneratedStruct56 {
    type Error = ();
    fn try_into(self) -> Result<u32, Self::Error> {
        #[allow(unreachable_patterns)]
        match self {
            GeneratedStruct56 {
                facing: Direction::North,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23443u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23444u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23445u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23446u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23447u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23448u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23449u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23450u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23451u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23452u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23453u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23454u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23455u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23456u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23457u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23458u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23459u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23460u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23461u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23462u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23463u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23464u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23465u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23466u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23467u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23468u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23469u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23470u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23471u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23472u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23473u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23474u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23475u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23476u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23477u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23478u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23479u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23480u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23481u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23482u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23483u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23484u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23485u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23486u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23487u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23488u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23489u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23490u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23491u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23492u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23493u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23494u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23495u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23496u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23497u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23498u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23499u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23500u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23501u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23502u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23503u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23504u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23505u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23506u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23507u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23508u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23509u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23510u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23511u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23512u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23513u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23514u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23515u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23516u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23517u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23518u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23519u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23520u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23521u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23522u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23523u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23524u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23525u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23526u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23527u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23528u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23529u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23530u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23531u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23532u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23533u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23534u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23535u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23536u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23537u32),
            GeneratedStruct56 {
                facing: Direction::North,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23538u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23539u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23540u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23541u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23542u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23543u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23544u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23545u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23546u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23547u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23548u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23549u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23550u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23551u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23552u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23553u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23554u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23555u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23556u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23557u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23558u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23559u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23560u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23561u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23562u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23563u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23564u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23565u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23566u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23567u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23568u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23569u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23570u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23571u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23572u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23573u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23574u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23575u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23576u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23577u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23578u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23579u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23580u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23581u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23582u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23583u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23584u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23585u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23586u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23587u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23588u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23589u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23590u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23591u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23592u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23593u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23594u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23595u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23596u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23597u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23598u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23599u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23600u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23601u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23602u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23603u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23604u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23605u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23606u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23607u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23608u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23609u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23610u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23611u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23612u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23613u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23614u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23615u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23616u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23617u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23618u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23619u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23620u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23621u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23622u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23623u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23624u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23625u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23626u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23627u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23628u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23629u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23630u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23631u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23632u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23633u32),
            GeneratedStruct56 {
                facing: Direction::South,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23634u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23635u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23636u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23637u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23638u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23639u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23640u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23641u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23642u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23643u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23644u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23645u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23646u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23647u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23648u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23649u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23650u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23651u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23652u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23653u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23654u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23655u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23656u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23657u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23658u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23659u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23660u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23661u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23662u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23663u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23664u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23665u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23666u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23667u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23668u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23669u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23670u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23671u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23672u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23673u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23674u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23675u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23676u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23677u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23678u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23679u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23680u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23681u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23682u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23683u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23684u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23685u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23686u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23687u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23688u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23689u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23690u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23691u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23692u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23693u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23694u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23695u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23696u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23697u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23698u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23699u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23700u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23701u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23702u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23703u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23704u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23705u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23706u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23707u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23708u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23709u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23710u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23711u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23712u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23713u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23714u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23715u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23716u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23717u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23718u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23719u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23720u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23721u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23722u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23723u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23724u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23725u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23726u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23727u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23728u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23729u32),
            GeneratedStruct56 {
                facing: Direction::West,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23730u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23731u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23732u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23733u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23734u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23735u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 0i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23736u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23737u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23738u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23739u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23740u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23741u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 1i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23742u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23743u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23744u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23745u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23746u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23747u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 2i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23748u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23749u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23750u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23751u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23752u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23753u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 3i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23754u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23755u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23756u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23757u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23758u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23759u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 4i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23760u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23761u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23762u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23763u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23764u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23765u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 5i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23766u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23767u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23768u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23769u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23770u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23771u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 6i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23772u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23773u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23774u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23775u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23776u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23777u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 7i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23778u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23779u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23780u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23781u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23782u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23783u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 8i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23784u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23785u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23786u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23787u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23788u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23789u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 9i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23790u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23791u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23792u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23793u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23794u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23795u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 10i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23796u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23797u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23798u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23799u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23800u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23801u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 11i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23802u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23803u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23804u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23805u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23806u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23807u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 12i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23808u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23809u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23810u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23811u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23812u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23813u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 13i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23814u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23815u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23816u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23817u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23818u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23819u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 14i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23820u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: true,
            } => Ok(23821u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Inactive,
                waterlogged: false,
            } => Ok(23822u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: true,
            } => Ok(23823u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Active,
                waterlogged: false,
            } => Ok(23824u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: true,
            } => Ok(23825u32),
            GeneratedStruct56 {
                facing: Direction::East,
                power: 15i32,
                sculk_sensor_phase: SculkSensorPhase::Cooldown,
                waterlogged: false,
            } => Ok(23826u32),
            _ => Err(()),
        }
    }
}
