#[allow(unused_imports)]
use ferrumc_block_properties::*;
#[allow(dead_code)]
pub struct GeneratedStruct18 {
    pub bottom: bool,
    pub east: WallSide,
    pub north: WallSide,
    pub south: WallSide,
    pub west: WallSide,
}
impl TryFrom<u32> for GeneratedStruct18 {
    type Error = ();
    fn try_from(value: u32) -> Result<Self, Self::Error> {
        match value {
            27745u32 => Ok(GeneratedStruct18 {
                east: WallSide::None,
                south: WallSide::None,
                west: WallSide::None,
                bottom: true,
                north: WallSide::None,
            }),
            27746u32 => Ok(GeneratedStruct18 {
                north: WallSide::None,
                bottom: true,
                east: WallSide::None,
                south: WallSide::None,
                west: WallSide::Low,
            }),
            27747u32 => Ok(GeneratedStruct18 {
                south: WallSide::None,
                north: WallSide::None,
                west: WallSide::Tall,
                bottom: true,
                east: WallSide::None,
            }),
            27748u32 => Ok(GeneratedStruct18 {
                east: WallSide::None,
                bottom: true,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::None,
            }),
            27749u32 => Ok(GeneratedStruct18 {
                north: WallSide::None,
                bottom: true,
                east: WallSide::None,
                south: WallSide::Low,
                west: WallSide::Low,
            }),
            27750u32 => Ok(GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                south: WallSide::Low,
                north: WallSide::None,
                west: WallSide::Tall,
            }),
            27751u32 => Ok(GeneratedStruct18 {
                east: WallSide::None,
                bottom: true,
                north: WallSide::None,
                west: WallSide::None,
                south: WallSide::Tall,
            }),
            27752u32 => Ok(GeneratedStruct18 {
                west: WallSide::Low,
                east: WallSide::None,
                bottom: true,
                south: WallSide::Tall,
                north: WallSide::None,
            }),
            27753u32 => Ok(GeneratedStruct18 {
                bottom: true,
                north: WallSide::None,
                west: WallSide::Tall,
                south: WallSide::Tall,
                east: WallSide::None,
            }),
            27754u32 => Ok(GeneratedStruct18 {
                bottom: true,
                north: WallSide::Low,
                east: WallSide::None,
                south: WallSide::None,
                west: WallSide::None,
            }),
            27755u32 => Ok(GeneratedStruct18 {
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::Low,
                bottom: true,
                east: WallSide::None,
            }),
            27756u32 => Ok(GeneratedStruct18 {
                north: WallSide::Low,
                bottom: true,
                east: WallSide::None,
                south: WallSide::None,
                west: WallSide::Tall,
            }),
            27757u32 => Ok(GeneratedStruct18 {
                west: WallSide::None,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::Low,
                bottom: true,
            }),
            27758u32 => Ok(GeneratedStruct18 {
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::Low,
                bottom: true,
            }),
            27759u32 => Ok(GeneratedStruct18 {
                bottom: true,
                west: WallSide::Tall,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::Low,
            }),
            27760u32 => Ok(GeneratedStruct18 {
                north: WallSide::Low,
                east: WallSide::None,
                south: WallSide::Tall,
                west: WallSide::None,
                bottom: true,
            }),
            27761u32 => Ok(GeneratedStruct18 {
                bottom: true,
                south: WallSide::Tall,
                north: WallSide::Low,
                west: WallSide::Low,
                east: WallSide::None,
            }),
            27762u32 => Ok(GeneratedStruct18 {
                south: WallSide::Tall,
                east: WallSide::None,
                west: WallSide::Tall,
                north: WallSide::Low,
                bottom: true,
            }),
            27763u32 => Ok(GeneratedStruct18 {
                bottom: true,
                west: WallSide::None,
                east: WallSide::None,
                north: WallSide::Tall,
                south: WallSide::None,
            }),
            27764u32 => Ok(GeneratedStruct18 {
                bottom: true,
                south: WallSide::None,
                north: WallSide::Tall,
                west: WallSide::Low,
                east: WallSide::None,
            }),
            27765u32 => Ok(GeneratedStruct18 {
                bottom: true,
                west: WallSide::Tall,
                east: WallSide::None,
                north: WallSide::Tall,
                south: WallSide::None,
            }),
            27766u32 => Ok(GeneratedStruct18 {
                east: WallSide::None,
                south: WallSide::Low,
                bottom: true,
                west: WallSide::None,
                north: WallSide::Tall,
            }),
            27767u32 => Ok(GeneratedStruct18 {
                south: WallSide::Low,
                north: WallSide::Tall,
                west: WallSide::Low,
                bottom: true,
                east: WallSide::None,
            }),
            27768u32 => Ok(GeneratedStruct18 {
                south: WallSide::Low,
                east: WallSide::None,
                north: WallSide::Tall,
                west: WallSide::Tall,
                bottom: true,
            }),
            27769u32 => Ok(GeneratedStruct18 {
                north: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::None,
                east: WallSide::None,
                bottom: true,
            }),
            27770u32 => Ok(GeneratedStruct18 {
                bottom: true,
                south: WallSide::Tall,
                east: WallSide::None,
                west: WallSide::Low,
                north: WallSide::Tall,
            }),
            27771u32 => Ok(GeneratedStruct18 {
                bottom: true,
                south: WallSide::Tall,
                north: WallSide::Tall,
                west: WallSide::Tall,
                east: WallSide::None,
            }),
            27772u32 => Ok(GeneratedStruct18 {
                bottom: true,
                west: WallSide::None,
                south: WallSide::None,
                north: WallSide::None,
                east: WallSide::Low,
            }),
            27773u32 => Ok(GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                south: WallSide::None,
                north: WallSide::None,
                west: WallSide::Low,
            }),
            27774u32 => Ok(GeneratedStruct18 {
                bottom: true,
                south: WallSide::None,
                east: WallSide::Low,
                north: WallSide::None,
                west: WallSide::Tall,
            }),
            27775u32 => Ok(GeneratedStruct18 {
                bottom: true,
                south: WallSide::Low,
                west: WallSide::None,
                east: WallSide::Low,
                north: WallSide::None,
            }),
            27776u32 => Ok(GeneratedStruct18 {
                bottom: true,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::Low,
                east: WallSide::Low,
            }),
            27777u32 => Ok(GeneratedStruct18 {
                north: WallSide::None,
                west: WallSide::Tall,
                bottom: true,
                east: WallSide::Low,
                south: WallSide::Low,
            }),
            27778u32 => Ok(GeneratedStruct18 {
                north: WallSide::None,
                east: WallSide::Low,
                west: WallSide::None,
                bottom: true,
                south: WallSide::Tall,
            }),
            27779u32 => Ok(GeneratedStruct18 {
                south: WallSide::Tall,
                west: WallSide::Low,
                bottom: true,
                east: WallSide::Low,
                north: WallSide::None,
            }),
            27780u32 => Ok(GeneratedStruct18 {
                bottom: true,
                north: WallSide::None,
                south: WallSide::Tall,
                east: WallSide::Low,
                west: WallSide::Tall,
            }),
            27781u32 => Ok(GeneratedStruct18 {
                west: WallSide::None,
                bottom: true,
                east: WallSide::Low,
                north: WallSide::Low,
                south: WallSide::None,
            }),
            27782u32 => Ok(GeneratedStruct18 {
                east: WallSide::Low,
                north: WallSide::Low,
                south: WallSide::None,
                bottom: true,
                west: WallSide::Low,
            }),
            27783u32 => Ok(GeneratedStruct18 {
                south: WallSide::None,
                east: WallSide::Low,
                north: WallSide::Low,
                west: WallSide::Tall,
                bottom: true,
            }),
            27784u32 => Ok(GeneratedStruct18 {
                bottom: true,
                north: WallSide::Low,
                west: WallSide::None,
                south: WallSide::Low,
                east: WallSide::Low,
            }),
            27785u32 => Ok(GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::Low,
                west: WallSide::Low,
                south: WallSide::Low,
            }),
            27786u32 => Ok(GeneratedStruct18 {
                south: WallSide::Low,
                bottom: true,
                west: WallSide::Tall,
                east: WallSide::Low,
                north: WallSide::Low,
            }),
            27787u32 => Ok(GeneratedStruct18 {
                north: WallSide::Low,
                bottom: true,
                east: WallSide::Low,
                west: WallSide::None,
                south: WallSide::Tall,
            }),
            27788u32 => Ok(GeneratedStruct18 {
                bottom: true,
                north: WallSide::Low,
                west: WallSide::Low,
                east: WallSide::Low,
                south: WallSide::Tall,
            }),
            27789u32 => Ok(GeneratedStruct18 {
                west: WallSide::Tall,
                south: WallSide::Tall,
                east: WallSide::Low,
                north: WallSide::Low,
                bottom: true,
            }),
            27790u32 => Ok(GeneratedStruct18 {
                south: WallSide::None,
                north: WallSide::Tall,
                west: WallSide::None,
                bottom: true,
                east: WallSide::Low,
            }),
            27791u32 => Ok(GeneratedStruct18 {
                north: WallSide::Tall,
                south: WallSide::None,
                bottom: true,
                west: WallSide::Low,
                east: WallSide::Low,
            }),
            27792u32 => Ok(GeneratedStruct18 {
                north: WallSide::Tall,
                east: WallSide::Low,
                bottom: true,
                south: WallSide::None,
                west: WallSide::Tall,
            }),
            27793u32 => Ok(GeneratedStruct18 {
                south: WallSide::Low,
                west: WallSide::None,
                east: WallSide::Low,
                bottom: true,
                north: WallSide::Tall,
            }),
            27794u32 => Ok(GeneratedStruct18 {
                north: WallSide::Tall,
                south: WallSide::Low,
                west: WallSide::Low,
                east: WallSide::Low,
                bottom: true,
            }),
            27795u32 => Ok(GeneratedStruct18 {
                bottom: true,
                south: WallSide::Low,
                west: WallSide::Tall,
                east: WallSide::Low,
                north: WallSide::Tall,
            }),
            27796u32 => Ok(GeneratedStruct18 {
                west: WallSide::None,
                south: WallSide::Tall,
                east: WallSide::Low,
                bottom: true,
                north: WallSide::Tall,
            }),
            27797u32 => Ok(GeneratedStruct18 {
                west: WallSide::Low,
                east: WallSide::Low,
                bottom: true,
                north: WallSide::Tall,
                south: WallSide::Tall,
            }),
            27798u32 => Ok(GeneratedStruct18 {
                north: WallSide::Tall,
                east: WallSide::Low,
                south: WallSide::Tall,
                bottom: true,
                west: WallSide::Tall,
            }),
            27799u32 => Ok(GeneratedStruct18 {
                bottom: true,
                south: WallSide::None,
                west: WallSide::None,
                east: WallSide::Tall,
                north: WallSide::None,
            }),
            27800u32 => Ok(GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::None,
                south: WallSide::None,
                west: WallSide::Low,
            }),
            27801u32 => Ok(GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::None,
                west: WallSide::Tall,
                south: WallSide::None,
            }),
            27802u32 => Ok(GeneratedStruct18 {
                north: WallSide::None,
                bottom: true,
                west: WallSide::None,
                east: WallSide::Tall,
                south: WallSide::Low,
            }),
            27803u32 => Ok(GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                south: WallSide::Low,
                west: WallSide::Low,
                north: WallSide::None,
            }),
            27804u32 => Ok(GeneratedStruct18 {
                north: WallSide::None,
                bottom: true,
                west: WallSide::Tall,
                south: WallSide::Low,
                east: WallSide::Tall,
            }),
            27805u32 => Ok(GeneratedStruct18 {
                east: WallSide::Tall,
                north: WallSide::None,
                bottom: true,
                south: WallSide::Tall,
                west: WallSide::None,
            }),
            27806u32 => Ok(GeneratedStruct18 {
                bottom: true,
                north: WallSide::None,
                west: WallSide::Low,
                south: WallSide::Tall,
                east: WallSide::Tall,
            }),
            27807u32 => Ok(GeneratedStruct18 {
                north: WallSide::None,
                bottom: true,
                east: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::Tall,
            }),
            27808u32 => Ok(GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::None,
            }),
            27809u32 => Ok(GeneratedStruct18 {
                north: WallSide::Low,
                bottom: true,
                east: WallSide::Tall,
                west: WallSide::Low,
                south: WallSide::None,
            }),
            27810u32 => Ok(GeneratedStruct18 {
                bottom: true,
                north: WallSide::Low,
                south: WallSide::None,
                east: WallSide::Tall,
                west: WallSide::Tall,
            }),
            27811u32 => Ok(GeneratedStruct18 {
                bottom: true,
                west: WallSide::None,
                north: WallSide::Low,
                south: WallSide::Low,
                east: WallSide::Tall,
            }),
            27812u32 => Ok(GeneratedStruct18 {
                east: WallSide::Tall,
                west: WallSide::Low,
                south: WallSide::Low,
                north: WallSide::Low,
                bottom: true,
            }),
            27813u32 => Ok(GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                south: WallSide::Low,
                north: WallSide::Low,
                west: WallSide::Tall,
            }),
            27814u32 => Ok(GeneratedStruct18 {
                west: WallSide::None,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::Tall,
                bottom: true,
            }),
            27815u32 => Ok(GeneratedStruct18 {
                east: WallSide::Tall,
                north: WallSide::Low,
                bottom: true,
                south: WallSide::Tall,
                west: WallSide::Low,
            }),
            27816u32 => Ok(GeneratedStruct18 {
                east: WallSide::Tall,
                bottom: true,
                north: WallSide::Low,
                west: WallSide::Tall,
                south: WallSide::Tall,
            }),
            27817u32 => Ok(GeneratedStruct18 {
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::None,
                bottom: true,
            }),
            27818u32 => Ok(GeneratedStruct18 {
                north: WallSide::Tall,
                south: WallSide::None,
                bottom: true,
                west: WallSide::Low,
                east: WallSide::Tall,
            }),
            27819u32 => Ok(GeneratedStruct18 {
                south: WallSide::None,
                bottom: true,
                west: WallSide::Tall,
                east: WallSide::Tall,
                north: WallSide::Tall,
            }),
            27820u32 => Ok(GeneratedStruct18 {
                bottom: true,
                south: WallSide::Low,
                east: WallSide::Tall,
                west: WallSide::None,
                north: WallSide::Tall,
            }),
            27821u32 => Ok(GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                west: WallSide::Low,
                north: WallSide::Tall,
                south: WallSide::Low,
            }),
            27822u32 => Ok(GeneratedStruct18 {
                south: WallSide::Low,
                north: WallSide::Tall,
                bottom: true,
                east: WallSide::Tall,
                west: WallSide::Tall,
            }),
            27823u32 => Ok(GeneratedStruct18 {
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::Tall,
                bottom: true,
                west: WallSide::None,
            }),
            27824u32 => Ok(GeneratedStruct18 {
                east: WallSide::Tall,
                bottom: true,
                north: WallSide::Tall,
                west: WallSide::Low,
                south: WallSide::Tall,
            }),
            27825u32 => Ok(GeneratedStruct18 {
                north: WallSide::Tall,
                bottom: true,
                south: WallSide::Tall,
                west: WallSide::Tall,
                east: WallSide::Tall,
            }),
            27826u32 => Ok(GeneratedStruct18 {
                bottom: false,
                west: WallSide::None,
                south: WallSide::None,
                east: WallSide::None,
                north: WallSide::None,
            }),
            27827u32 => Ok(GeneratedStruct18 {
                east: WallSide::None,
                south: WallSide::None,
                bottom: false,
                north: WallSide::None,
                west: WallSide::Low,
            }),
            27828u32 => Ok(GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                south: WallSide::None,
                west: WallSide::Tall,
                north: WallSide::None,
            }),
            27829u32 => Ok(GeneratedStruct18 {
                east: WallSide::None,
                bottom: false,
                north: WallSide::None,
                west: WallSide::None,
                south: WallSide::Low,
            }),
            27830u32 => Ok(GeneratedStruct18 {
                bottom: false,
                north: WallSide::None,
                south: WallSide::Low,
                east: WallSide::None,
                west: WallSide::Low,
            }),
            27831u32 => Ok(GeneratedStruct18 {
                west: WallSide::Tall,
                bottom: false,
                east: WallSide::None,
                north: WallSide::None,
                south: WallSide::Low,
            }),
            27832u32 => Ok(GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::None,
                south: WallSide::Tall,
                west: WallSide::None,
            }),
            27833u32 => Ok(GeneratedStruct18 {
                south: WallSide::Tall,
                east: WallSide::None,
                bottom: false,
                north: WallSide::None,
                west: WallSide::Low,
            }),
            27834u32 => Ok(GeneratedStruct18 {
                south: WallSide::Tall,
                west: WallSide::Tall,
                east: WallSide::None,
                bottom: false,
                north: WallSide::None,
            }),
            27835u32 => Ok(GeneratedStruct18 {
                south: WallSide::None,
                north: WallSide::Low,
                east: WallSide::None,
                bottom: false,
                west: WallSide::None,
            }),
            27836u32 => Ok(GeneratedStruct18 {
                bottom: false,
                south: WallSide::None,
                north: WallSide::Low,
                west: WallSide::Low,
                east: WallSide::None,
            }),
            27837u32 => Ok(GeneratedStruct18 {
                south: WallSide::None,
                west: WallSide::Tall,
                bottom: false,
                north: WallSide::Low,
                east: WallSide::None,
            }),
            27838u32 => Ok(GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::None,
            }),
            27839u32 => Ok(GeneratedStruct18 {
                bottom: false,
                south: WallSide::Low,
                east: WallSide::None,
                west: WallSide::Low,
                north: WallSide::Low,
            }),
            27840u32 => Ok(GeneratedStruct18 {
                bottom: false,
                west: WallSide::Tall,
                north: WallSide::Low,
                east: WallSide::None,
                south: WallSide::Low,
            }),
            27841u32 => Ok(GeneratedStruct18 {
                south: WallSide::Tall,
                west: WallSide::None,
                east: WallSide::None,
                bottom: false,
                north: WallSide::Low,
            }),
            27842u32 => Ok(GeneratedStruct18 {
                bottom: false,
                north: WallSide::Low,
                east: WallSide::None,
                west: WallSide::Low,
                south: WallSide::Tall,
            }),
            27843u32 => Ok(GeneratedStruct18 {
                south: WallSide::Tall,
                west: WallSide::Tall,
                east: WallSide::None,
                bottom: false,
                north: WallSide::Low,
            }),
            27844u32 => Ok(GeneratedStruct18 {
                east: WallSide::None,
                bottom: false,
                north: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::None,
            }),
            27845u32 => Ok(GeneratedStruct18 {
                east: WallSide::None,
                north: WallSide::Tall,
                west: WallSide::Low,
                bottom: false,
                south: WallSide::None,
            }),
            27846u32 => Ok(GeneratedStruct18 {
                east: WallSide::None,
                south: WallSide::None,
                north: WallSide::Tall,
                bottom: false,
                west: WallSide::Tall,
            }),
            27847u32 => Ok(GeneratedStruct18 {
                east: WallSide::None,
                west: WallSide::None,
                south: WallSide::Low,
                bottom: false,
                north: WallSide::Tall,
            }),
            27848u32 => Ok(GeneratedStruct18 {
                north: WallSide::Tall,
                south: WallSide::Low,
                east: WallSide::None,
                bottom: false,
                west: WallSide::Low,
            }),
            27849u32 => Ok(GeneratedStruct18 {
                south: WallSide::Low,
                east: WallSide::None,
                north: WallSide::Tall,
                bottom: false,
                west: WallSide::Tall,
            }),
            27850u32 => Ok(GeneratedStruct18 {
                west: WallSide::None,
                bottom: false,
                north: WallSide::Tall,
                east: WallSide::None,
                south: WallSide::Tall,
            }),
            27851u32 => Ok(GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::Tall,
                west: WallSide::Low,
                south: WallSide::Tall,
            }),
            27852u32 => Ok(GeneratedStruct18 {
                north: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::Tall,
                bottom: false,
                east: WallSide::None,
            }),
            27853u32 => Ok(GeneratedStruct18 {
                bottom: false,
                west: WallSide::None,
                east: WallSide::Low,
                north: WallSide::None,
                south: WallSide::None,
            }),
            27854u32 => Ok(GeneratedStruct18 {
                north: WallSide::None,
                west: WallSide::Low,
                bottom: false,
                east: WallSide::Low,
                south: WallSide::None,
            }),
            27855u32 => Ok(GeneratedStruct18 {
                west: WallSide::Tall,
                east: WallSide::Low,
                north: WallSide::None,
                south: WallSide::None,
                bottom: false,
            }),
            27856u32 => Ok(GeneratedStruct18 {
                west: WallSide::None,
                bottom: false,
                south: WallSide::Low,
                east: WallSide::Low,
                north: WallSide::None,
            }),
            27857u32 => Ok(GeneratedStruct18 {
                south: WallSide::Low,
                north: WallSide::None,
                west: WallSide::Low,
                bottom: false,
                east: WallSide::Low,
            }),
            27858u32 => Ok(GeneratedStruct18 {
                south: WallSide::Low,
                east: WallSide::Low,
                north: WallSide::None,
                bottom: false,
                west: WallSide::Tall,
            }),
            27859u32 => Ok(GeneratedStruct18 {
                south: WallSide::Tall,
                bottom: false,
                east: WallSide::Low,
                west: WallSide::None,
                north: WallSide::None,
            }),
            27860u32 => Ok(GeneratedStruct18 {
                east: WallSide::Low,
                south: WallSide::Tall,
                bottom: false,
                west: WallSide::Low,
                north: WallSide::None,
            }),
            27861u32 => Ok(GeneratedStruct18 {
                south: WallSide::Tall,
                west: WallSide::Tall,
                north: WallSide::None,
                bottom: false,
                east: WallSide::Low,
            }),
            27862u32 => Ok(GeneratedStruct18 {
                west: WallSide::None,
                east: WallSide::Low,
                bottom: false,
                south: WallSide::None,
                north: WallSide::Low,
            }),
            27863u32 => Ok(GeneratedStruct18 {
                west: WallSide::Low,
                north: WallSide::Low,
                bottom: false,
                east: WallSide::Low,
                south: WallSide::None,
            }),
            27864u32 => Ok(GeneratedStruct18 {
                bottom: false,
                south: WallSide::None,
                north: WallSide::Low,
                west: WallSide::Tall,
                east: WallSide::Low,
            }),
            27865u32 => Ok(GeneratedStruct18 {
                south: WallSide::Low,
                west: WallSide::None,
                bottom: false,
                east: WallSide::Low,
                north: WallSide::Low,
            }),
            27866u32 => Ok(GeneratedStruct18 {
                east: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::Low,
                north: WallSide::Low,
                bottom: false,
            }),
            27867u32 => Ok(GeneratedStruct18 {
                north: WallSide::Low,
                east: WallSide::Low,
                bottom: false,
                south: WallSide::Low,
                west: WallSide::Tall,
            }),
            27868u32 => Ok(GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::None,
                north: WallSide::Low,
            }),
            27869u32 => Ok(GeneratedStruct18 {
                north: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::Low,
                east: WallSide::Low,
                bottom: false,
            }),
            27870u32 => Ok(GeneratedStruct18 {
                east: WallSide::Low,
                bottom: false,
                north: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::Tall,
            }),
            27871u32 => Ok(GeneratedStruct18 {
                south: WallSide::None,
                bottom: false,
                east: WallSide::Low,
                west: WallSide::None,
                north: WallSide::Tall,
            }),
            27872u32 => Ok(GeneratedStruct18 {
                west: WallSide::Low,
                north: WallSide::Tall,
                east: WallSide::Low,
                bottom: false,
                south: WallSide::None,
            }),
            27873u32 => Ok(GeneratedStruct18 {
                east: WallSide::Low,
                bottom: false,
                west: WallSide::Tall,
                south: WallSide::None,
                north: WallSide::Tall,
            }),
            27874u32 => Ok(GeneratedStruct18 {
                west: WallSide::None,
                south: WallSide::Low,
                east: WallSide::Low,
                bottom: false,
                north: WallSide::Tall,
            }),
            27875u32 => Ok(GeneratedStruct18 {
                west: WallSide::Low,
                east: WallSide::Low,
                bottom: false,
                north: WallSide::Tall,
                south: WallSide::Low,
            }),
            27876u32 => Ok(GeneratedStruct18 {
                west: WallSide::Tall,
                south: WallSide::Low,
                bottom: false,
                east: WallSide::Low,
                north: WallSide::Tall,
            }),
            27877u32 => Ok(GeneratedStruct18 {
                east: WallSide::Low,
                north: WallSide::Tall,
                bottom: false,
                south: WallSide::Tall,
                west: WallSide::None,
            }),
            27878u32 => Ok(GeneratedStruct18 {
                east: WallSide::Low,
                west: WallSide::Low,
                bottom: false,
                south: WallSide::Tall,
                north: WallSide::Tall,
            }),
            27879u32 => Ok(GeneratedStruct18 {
                bottom: false,
                south: WallSide::Tall,
                west: WallSide::Tall,
                east: WallSide::Low,
                north: WallSide::Tall,
            }),
            27880u32 => Ok(GeneratedStruct18 {
                north: WallSide::None,
                west: WallSide::None,
                bottom: false,
                east: WallSide::Tall,
                south: WallSide::None,
            }),
            27881u32 => Ok(GeneratedStruct18 {
                north: WallSide::None,
                bottom: false,
                south: WallSide::None,
                east: WallSide::Tall,
                west: WallSide::Low,
            }),
            27882u32 => Ok(GeneratedStruct18 {
                north: WallSide::None,
                bottom: false,
                east: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::Tall,
            }),
            27883u32 => Ok(GeneratedStruct18 {
                east: WallSide::Tall,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::None,
                bottom: false,
            }),
            27884u32 => Ok(GeneratedStruct18 {
                west: WallSide::Low,
                north: WallSide::None,
                east: WallSide::Tall,
                bottom: false,
                south: WallSide::Low,
            }),
            27885u32 => Ok(GeneratedStruct18 {
                north: WallSide::None,
                bottom: false,
                south: WallSide::Low,
                west: WallSide::Tall,
                east: WallSide::Tall,
            }),
            27886u32 => Ok(GeneratedStruct18 {
                bottom: false,
                north: WallSide::None,
                west: WallSide::None,
                south: WallSide::Tall,
                east: WallSide::Tall,
            }),
            27887u32 => Ok(GeneratedStruct18 {
                west: WallSide::Low,
                east: WallSide::Tall,
                bottom: false,
                north: WallSide::None,
                south: WallSide::Tall,
            }),
            27888u32 => Ok(GeneratedStruct18 {
                north: WallSide::None,
                bottom: false,
                east: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::Tall,
            }),
            27889u32 => Ok(GeneratedStruct18 {
                south: WallSide::None,
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Low,
                west: WallSide::None,
            }),
            27890u32 => Ok(GeneratedStruct18 {
                east: WallSide::Tall,
                bottom: false,
                south: WallSide::None,
                west: WallSide::Low,
                north: WallSide::Low,
            }),
            27891u32 => Ok(GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::Tall,
            }),
            27892u32 => Ok(GeneratedStruct18 {
                west: WallSide::None,
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::Low,
            }),
            27893u32 => Ok(GeneratedStruct18 {
                west: WallSide::Low,
                south: WallSide::Low,
                east: WallSide::Tall,
                bottom: false,
                north: WallSide::Low,
            }),
            27894u32 => Ok(GeneratedStruct18 {
                bottom: false,
                west: WallSide::Tall,
                east: WallSide::Tall,
                south: WallSide::Low,
                north: WallSide::Low,
            }),
            27895u32 => Ok(GeneratedStruct18 {
                east: WallSide::Tall,
                north: WallSide::Low,
                bottom: false,
                south: WallSide::Tall,
                west: WallSide::None,
            }),
            27896u32 => Ok(GeneratedStruct18 {
                bottom: false,
                west: WallSide::Low,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::Tall,
            }),
            27897u32 => Ok(GeneratedStruct18 {
                east: WallSide::Tall,
                bottom: false,
                south: WallSide::Tall,
                west: WallSide::Tall,
                north: WallSide::Low,
            }),
            27898u32 => Ok(GeneratedStruct18 {
                east: WallSide::Tall,
                north: WallSide::Tall,
                bottom: false,
                south: WallSide::None,
                west: WallSide::None,
            }),
            27899u32 => Ok(GeneratedStruct18 {
                south: WallSide::None,
                north: WallSide::Tall,
                west: WallSide::Low,
                east: WallSide::Tall,
                bottom: false,
            }),
            27900u32 => Ok(GeneratedStruct18 {
                north: WallSide::Tall,
                west: WallSide::Tall,
                east: WallSide::Tall,
                bottom: false,
                south: WallSide::None,
            }),
            27901u32 => Ok(GeneratedStruct18 {
                bottom: false,
                south: WallSide::Low,
                east: WallSide::Tall,
                north: WallSide::Tall,
                west: WallSide::None,
            }),
            27902u32 => Ok(GeneratedStruct18 {
                south: WallSide::Low,
                west: WallSide::Low,
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Tall,
            }),
            27903u32 => Ok(GeneratedStruct18 {
                bottom: false,
                west: WallSide::Tall,
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::Low,
            }),
            27904u32 => Ok(GeneratedStruct18 {
                west: WallSide::None,
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::Tall,
                bottom: false,
            }),
            27905u32 => Ok(GeneratedStruct18 {
                bottom: false,
                west: WallSide::Low,
                north: WallSide::Tall,
                east: WallSide::Tall,
                south: WallSide::Tall,
            }),
            27906u32 => Ok(GeneratedStruct18 {
                east: WallSide::Tall,
                north: WallSide::Tall,
                bottom: false,
                south: WallSide::Tall,
                west: WallSide::Tall,
            }),
            _ => Err(()),
        }
    }
}
impl TryInto<u32> for GeneratedStruct18 {
    type Error = ();
    fn try_into(self) -> Result<u32, Self::Error> {
        #[allow(unreachable_patterns)]
        match self {
            GeneratedStruct18 {
                east: WallSide::None,
                south: WallSide::None,
                west: WallSide::None,
                bottom: true,
                north: WallSide::None,
            } => Ok(27745u32),
            GeneratedStruct18 {
                north: WallSide::None,
                bottom: true,
                east: WallSide::None,
                south: WallSide::None,
                west: WallSide::Low,
            } => Ok(27746u32),
            GeneratedStruct18 {
                south: WallSide::None,
                north: WallSide::None,
                west: WallSide::Tall,
                bottom: true,
                east: WallSide::None,
            } => Ok(27747u32),
            GeneratedStruct18 {
                east: WallSide::None,
                bottom: true,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::None,
            } => Ok(27748u32),
            GeneratedStruct18 {
                north: WallSide::None,
                bottom: true,
                east: WallSide::None,
                south: WallSide::Low,
                west: WallSide::Low,
            } => Ok(27749u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::None,
                south: WallSide::Low,
                north: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27750u32),
            GeneratedStruct18 {
                east: WallSide::None,
                bottom: true,
                north: WallSide::None,
                west: WallSide::None,
                south: WallSide::Tall,
            } => Ok(27751u32),
            GeneratedStruct18 {
                west: WallSide::Low,
                east: WallSide::None,
                bottom: true,
                south: WallSide::Tall,
                north: WallSide::None,
            } => Ok(27752u32),
            GeneratedStruct18 {
                bottom: true,
                north: WallSide::None,
                west: WallSide::Tall,
                south: WallSide::Tall,
                east: WallSide::None,
            } => Ok(27753u32),
            GeneratedStruct18 {
                bottom: true,
                north: WallSide::Low,
                east: WallSide::None,
                south: WallSide::None,
                west: WallSide::None,
            } => Ok(27754u32),
            GeneratedStruct18 {
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::Low,
                bottom: true,
                east: WallSide::None,
            } => Ok(27755u32),
            GeneratedStruct18 {
                north: WallSide::Low,
                bottom: true,
                east: WallSide::None,
                south: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27756u32),
            GeneratedStruct18 {
                west: WallSide::None,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::Low,
                bottom: true,
            } => Ok(27757u32),
            GeneratedStruct18 {
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::Low,
                bottom: true,
            } => Ok(27758u32),
            GeneratedStruct18 {
                bottom: true,
                west: WallSide::Tall,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::Low,
            } => Ok(27759u32),
            GeneratedStruct18 {
                north: WallSide::Low,
                east: WallSide::None,
                south: WallSide::Tall,
                west: WallSide::None,
                bottom: true,
            } => Ok(27760u32),
            GeneratedStruct18 {
                bottom: true,
                south: WallSide::Tall,
                north: WallSide::Low,
                west: WallSide::Low,
                east: WallSide::None,
            } => Ok(27761u32),
            GeneratedStruct18 {
                south: WallSide::Tall,
                east: WallSide::None,
                west: WallSide::Tall,
                north: WallSide::Low,
                bottom: true,
            } => Ok(27762u32),
            GeneratedStruct18 {
                bottom: true,
                west: WallSide::None,
                east: WallSide::None,
                north: WallSide::Tall,
                south: WallSide::None,
            } => Ok(27763u32),
            GeneratedStruct18 {
                bottom: true,
                south: WallSide::None,
                north: WallSide::Tall,
                west: WallSide::Low,
                east: WallSide::None,
            } => Ok(27764u32),
            GeneratedStruct18 {
                bottom: true,
                west: WallSide::Tall,
                east: WallSide::None,
                north: WallSide::Tall,
                south: WallSide::None,
            } => Ok(27765u32),
            GeneratedStruct18 {
                east: WallSide::None,
                south: WallSide::Low,
                bottom: true,
                west: WallSide::None,
                north: WallSide::Tall,
            } => Ok(27766u32),
            GeneratedStruct18 {
                south: WallSide::Low,
                north: WallSide::Tall,
                west: WallSide::Low,
                bottom: true,
                east: WallSide::None,
            } => Ok(27767u32),
            GeneratedStruct18 {
                south: WallSide::Low,
                east: WallSide::None,
                north: WallSide::Tall,
                west: WallSide::Tall,
                bottom: true,
            } => Ok(27768u32),
            GeneratedStruct18 {
                north: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::None,
                east: WallSide::None,
                bottom: true,
            } => Ok(27769u32),
            GeneratedStruct18 {
                bottom: true,
                south: WallSide::Tall,
                east: WallSide::None,
                west: WallSide::Low,
                north: WallSide::Tall,
            } => Ok(27770u32),
            GeneratedStruct18 {
                bottom: true,
                south: WallSide::Tall,
                north: WallSide::Tall,
                west: WallSide::Tall,
                east: WallSide::None,
            } => Ok(27771u32),
            GeneratedStruct18 {
                bottom: true,
                west: WallSide::None,
                south: WallSide::None,
                north: WallSide::None,
                east: WallSide::Low,
            } => Ok(27772u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                south: WallSide::None,
                north: WallSide::None,
                west: WallSide::Low,
            } => Ok(27773u32),
            GeneratedStruct18 {
                bottom: true,
                south: WallSide::None,
                east: WallSide::Low,
                north: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27774u32),
            GeneratedStruct18 {
                bottom: true,
                south: WallSide::Low,
                west: WallSide::None,
                east: WallSide::Low,
                north: WallSide::None,
            } => Ok(27775u32),
            GeneratedStruct18 {
                bottom: true,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::Low,
                east: WallSide::Low,
            } => Ok(27776u32),
            GeneratedStruct18 {
                north: WallSide::None,
                west: WallSide::Tall,
                bottom: true,
                east: WallSide::Low,
                south: WallSide::Low,
            } => Ok(27777u32),
            GeneratedStruct18 {
                north: WallSide::None,
                east: WallSide::Low,
                west: WallSide::None,
                bottom: true,
                south: WallSide::Tall,
            } => Ok(27778u32),
            GeneratedStruct18 {
                south: WallSide::Tall,
                west: WallSide::Low,
                bottom: true,
                east: WallSide::Low,
                north: WallSide::None,
            } => Ok(27779u32),
            GeneratedStruct18 {
                bottom: true,
                north: WallSide::None,
                south: WallSide::Tall,
                east: WallSide::Low,
                west: WallSide::Tall,
            } => Ok(27780u32),
            GeneratedStruct18 {
                west: WallSide::None,
                bottom: true,
                east: WallSide::Low,
                north: WallSide::Low,
                south: WallSide::None,
            } => Ok(27781u32),
            GeneratedStruct18 {
                east: WallSide::Low,
                north: WallSide::Low,
                south: WallSide::None,
                bottom: true,
                west: WallSide::Low,
            } => Ok(27782u32),
            GeneratedStruct18 {
                south: WallSide::None,
                east: WallSide::Low,
                north: WallSide::Low,
                west: WallSide::Tall,
                bottom: true,
            } => Ok(27783u32),
            GeneratedStruct18 {
                bottom: true,
                north: WallSide::Low,
                west: WallSide::None,
                south: WallSide::Low,
                east: WallSide::Low,
            } => Ok(27784u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Low,
                north: WallSide::Low,
                west: WallSide::Low,
                south: WallSide::Low,
            } => Ok(27785u32),
            GeneratedStruct18 {
                south: WallSide::Low,
                bottom: true,
                west: WallSide::Tall,
                east: WallSide::Low,
                north: WallSide::Low,
            } => Ok(27786u32),
            GeneratedStruct18 {
                north: WallSide::Low,
                bottom: true,
                east: WallSide::Low,
                west: WallSide::None,
                south: WallSide::Tall,
            } => Ok(27787u32),
            GeneratedStruct18 {
                bottom: true,
                north: WallSide::Low,
                west: WallSide::Low,
                east: WallSide::Low,
                south: WallSide::Tall,
            } => Ok(27788u32),
            GeneratedStruct18 {
                west: WallSide::Tall,
                south: WallSide::Tall,
                east: WallSide::Low,
                north: WallSide::Low,
                bottom: true,
            } => Ok(27789u32),
            GeneratedStruct18 {
                south: WallSide::None,
                north: WallSide::Tall,
                west: WallSide::None,
                bottom: true,
                east: WallSide::Low,
            } => Ok(27790u32),
            GeneratedStruct18 {
                north: WallSide::Tall,
                south: WallSide::None,
                bottom: true,
                west: WallSide::Low,
                east: WallSide::Low,
            } => Ok(27791u32),
            GeneratedStruct18 {
                north: WallSide::Tall,
                east: WallSide::Low,
                bottom: true,
                south: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27792u32),
            GeneratedStruct18 {
                south: WallSide::Low,
                west: WallSide::None,
                east: WallSide::Low,
                bottom: true,
                north: WallSide::Tall,
            } => Ok(27793u32),
            GeneratedStruct18 {
                north: WallSide::Tall,
                south: WallSide::Low,
                west: WallSide::Low,
                east: WallSide::Low,
                bottom: true,
            } => Ok(27794u32),
            GeneratedStruct18 {
                bottom: true,
                south: WallSide::Low,
                west: WallSide::Tall,
                east: WallSide::Low,
                north: WallSide::Tall,
            } => Ok(27795u32),
            GeneratedStruct18 {
                west: WallSide::None,
                south: WallSide::Tall,
                east: WallSide::Low,
                bottom: true,
                north: WallSide::Tall,
            } => Ok(27796u32),
            GeneratedStruct18 {
                west: WallSide::Low,
                east: WallSide::Low,
                bottom: true,
                north: WallSide::Tall,
                south: WallSide::Tall,
            } => Ok(27797u32),
            GeneratedStruct18 {
                north: WallSide::Tall,
                east: WallSide::Low,
                south: WallSide::Tall,
                bottom: true,
                west: WallSide::Tall,
            } => Ok(27798u32),
            GeneratedStruct18 {
                bottom: true,
                south: WallSide::None,
                west: WallSide::None,
                east: WallSide::Tall,
                north: WallSide::None,
            } => Ok(27799u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::None,
                south: WallSide::None,
                west: WallSide::Low,
            } => Ok(27800u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::None,
                west: WallSide::Tall,
                south: WallSide::None,
            } => Ok(27801u32),
            GeneratedStruct18 {
                north: WallSide::None,
                bottom: true,
                west: WallSide::None,
                east: WallSide::Tall,
                south: WallSide::Low,
            } => Ok(27802u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                south: WallSide::Low,
                west: WallSide::Low,
                north: WallSide::None,
            } => Ok(27803u32),
            GeneratedStruct18 {
                north: WallSide::None,
                bottom: true,
                west: WallSide::Tall,
                south: WallSide::Low,
                east: WallSide::Tall,
            } => Ok(27804u32),
            GeneratedStruct18 {
                east: WallSide::Tall,
                north: WallSide::None,
                bottom: true,
                south: WallSide::Tall,
                west: WallSide::None,
            } => Ok(27805u32),
            GeneratedStruct18 {
                bottom: true,
                north: WallSide::None,
                west: WallSide::Low,
                south: WallSide::Tall,
                east: WallSide::Tall,
            } => Ok(27806u32),
            GeneratedStruct18 {
                north: WallSide::None,
                bottom: true,
                east: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27807u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::None,
            } => Ok(27808u32),
            GeneratedStruct18 {
                north: WallSide::Low,
                bottom: true,
                east: WallSide::Tall,
                west: WallSide::Low,
                south: WallSide::None,
            } => Ok(27809u32),
            GeneratedStruct18 {
                bottom: true,
                north: WallSide::Low,
                south: WallSide::None,
                east: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27810u32),
            GeneratedStruct18 {
                bottom: true,
                west: WallSide::None,
                north: WallSide::Low,
                south: WallSide::Low,
                east: WallSide::Tall,
            } => Ok(27811u32),
            GeneratedStruct18 {
                east: WallSide::Tall,
                west: WallSide::Low,
                south: WallSide::Low,
                north: WallSide::Low,
                bottom: true,
            } => Ok(27812u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                south: WallSide::Low,
                north: WallSide::Low,
                west: WallSide::Tall,
            } => Ok(27813u32),
            GeneratedStruct18 {
                west: WallSide::None,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::Tall,
                bottom: true,
            } => Ok(27814u32),
            GeneratedStruct18 {
                east: WallSide::Tall,
                north: WallSide::Low,
                bottom: true,
                south: WallSide::Tall,
                west: WallSide::Low,
            } => Ok(27815u32),
            GeneratedStruct18 {
                east: WallSide::Tall,
                bottom: true,
                north: WallSide::Low,
                west: WallSide::Tall,
                south: WallSide::Tall,
            } => Ok(27816u32),
            GeneratedStruct18 {
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::None,
                bottom: true,
            } => Ok(27817u32),
            GeneratedStruct18 {
                north: WallSide::Tall,
                south: WallSide::None,
                bottom: true,
                west: WallSide::Low,
                east: WallSide::Tall,
            } => Ok(27818u32),
            GeneratedStruct18 {
                south: WallSide::None,
                bottom: true,
                west: WallSide::Tall,
                east: WallSide::Tall,
                north: WallSide::Tall,
            } => Ok(27819u32),
            GeneratedStruct18 {
                bottom: true,
                south: WallSide::Low,
                east: WallSide::Tall,
                west: WallSide::None,
                north: WallSide::Tall,
            } => Ok(27820u32),
            GeneratedStruct18 {
                bottom: true,
                east: WallSide::Tall,
                west: WallSide::Low,
                north: WallSide::Tall,
                south: WallSide::Low,
            } => Ok(27821u32),
            GeneratedStruct18 {
                south: WallSide::Low,
                north: WallSide::Tall,
                bottom: true,
                east: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27822u32),
            GeneratedStruct18 {
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::Tall,
                bottom: true,
                west: WallSide::None,
            } => Ok(27823u32),
            GeneratedStruct18 {
                east: WallSide::Tall,
                bottom: true,
                north: WallSide::Tall,
                west: WallSide::Low,
                south: WallSide::Tall,
            } => Ok(27824u32),
            GeneratedStruct18 {
                north: WallSide::Tall,
                bottom: true,
                south: WallSide::Tall,
                west: WallSide::Tall,
                east: WallSide::Tall,
            } => Ok(27825u32),
            GeneratedStruct18 {
                bottom: false,
                west: WallSide::None,
                south: WallSide::None,
                east: WallSide::None,
                north: WallSide::None,
            } => Ok(27826u32),
            GeneratedStruct18 {
                east: WallSide::None,
                south: WallSide::None,
                bottom: false,
                north: WallSide::None,
                west: WallSide::Low,
            } => Ok(27827u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                south: WallSide::None,
                west: WallSide::Tall,
                north: WallSide::None,
            } => Ok(27828u32),
            GeneratedStruct18 {
                east: WallSide::None,
                bottom: false,
                north: WallSide::None,
                west: WallSide::None,
                south: WallSide::Low,
            } => Ok(27829u32),
            GeneratedStruct18 {
                bottom: false,
                north: WallSide::None,
                south: WallSide::Low,
                east: WallSide::None,
                west: WallSide::Low,
            } => Ok(27830u32),
            GeneratedStruct18 {
                west: WallSide::Tall,
                bottom: false,
                east: WallSide::None,
                north: WallSide::None,
                south: WallSide::Low,
            } => Ok(27831u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::None,
                south: WallSide::Tall,
                west: WallSide::None,
            } => Ok(27832u32),
            GeneratedStruct18 {
                south: WallSide::Tall,
                east: WallSide::None,
                bottom: false,
                north: WallSide::None,
                west: WallSide::Low,
            } => Ok(27833u32),
            GeneratedStruct18 {
                south: WallSide::Tall,
                west: WallSide::Tall,
                east: WallSide::None,
                bottom: false,
                north: WallSide::None,
            } => Ok(27834u32),
            GeneratedStruct18 {
                south: WallSide::None,
                north: WallSide::Low,
                east: WallSide::None,
                bottom: false,
                west: WallSide::None,
            } => Ok(27835u32),
            GeneratedStruct18 {
                bottom: false,
                south: WallSide::None,
                north: WallSide::Low,
                west: WallSide::Low,
                east: WallSide::None,
            } => Ok(27836u32),
            GeneratedStruct18 {
                south: WallSide::None,
                west: WallSide::Tall,
                bottom: false,
                north: WallSide::Low,
                east: WallSide::None,
            } => Ok(27837u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::None,
            } => Ok(27838u32),
            GeneratedStruct18 {
                bottom: false,
                south: WallSide::Low,
                east: WallSide::None,
                west: WallSide::Low,
                north: WallSide::Low,
            } => Ok(27839u32),
            GeneratedStruct18 {
                bottom: false,
                west: WallSide::Tall,
                north: WallSide::Low,
                east: WallSide::None,
                south: WallSide::Low,
            } => Ok(27840u32),
            GeneratedStruct18 {
                south: WallSide::Tall,
                west: WallSide::None,
                east: WallSide::None,
                bottom: false,
                north: WallSide::Low,
            } => Ok(27841u32),
            GeneratedStruct18 {
                bottom: false,
                north: WallSide::Low,
                east: WallSide::None,
                west: WallSide::Low,
                south: WallSide::Tall,
            } => Ok(27842u32),
            GeneratedStruct18 {
                south: WallSide::Tall,
                west: WallSide::Tall,
                east: WallSide::None,
                bottom: false,
                north: WallSide::Low,
            } => Ok(27843u32),
            GeneratedStruct18 {
                east: WallSide::None,
                bottom: false,
                north: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::None,
            } => Ok(27844u32),
            GeneratedStruct18 {
                east: WallSide::None,
                north: WallSide::Tall,
                west: WallSide::Low,
                bottom: false,
                south: WallSide::None,
            } => Ok(27845u32),
            GeneratedStruct18 {
                east: WallSide::None,
                south: WallSide::None,
                north: WallSide::Tall,
                bottom: false,
                west: WallSide::Tall,
            } => Ok(27846u32),
            GeneratedStruct18 {
                east: WallSide::None,
                west: WallSide::None,
                south: WallSide::Low,
                bottom: false,
                north: WallSide::Tall,
            } => Ok(27847u32),
            GeneratedStruct18 {
                north: WallSide::Tall,
                south: WallSide::Low,
                east: WallSide::None,
                bottom: false,
                west: WallSide::Low,
            } => Ok(27848u32),
            GeneratedStruct18 {
                south: WallSide::Low,
                east: WallSide::None,
                north: WallSide::Tall,
                bottom: false,
                west: WallSide::Tall,
            } => Ok(27849u32),
            GeneratedStruct18 {
                west: WallSide::None,
                bottom: false,
                north: WallSide::Tall,
                east: WallSide::None,
                south: WallSide::Tall,
            } => Ok(27850u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::None,
                north: WallSide::Tall,
                west: WallSide::Low,
                south: WallSide::Tall,
            } => Ok(27851u32),
            GeneratedStruct18 {
                north: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::Tall,
                bottom: false,
                east: WallSide::None,
            } => Ok(27852u32),
            GeneratedStruct18 {
                bottom: false,
                west: WallSide::None,
                east: WallSide::Low,
                north: WallSide::None,
                south: WallSide::None,
            } => Ok(27853u32),
            GeneratedStruct18 {
                north: WallSide::None,
                west: WallSide::Low,
                bottom: false,
                east: WallSide::Low,
                south: WallSide::None,
            } => Ok(27854u32),
            GeneratedStruct18 {
                west: WallSide::Tall,
                east: WallSide::Low,
                north: WallSide::None,
                south: WallSide::None,
                bottom: false,
            } => Ok(27855u32),
            GeneratedStruct18 {
                west: WallSide::None,
                bottom: false,
                south: WallSide::Low,
                east: WallSide::Low,
                north: WallSide::None,
            } => Ok(27856u32),
            GeneratedStruct18 {
                south: WallSide::Low,
                north: WallSide::None,
                west: WallSide::Low,
                bottom: false,
                east: WallSide::Low,
            } => Ok(27857u32),
            GeneratedStruct18 {
                south: WallSide::Low,
                east: WallSide::Low,
                north: WallSide::None,
                bottom: false,
                west: WallSide::Tall,
            } => Ok(27858u32),
            GeneratedStruct18 {
                south: WallSide::Tall,
                bottom: false,
                east: WallSide::Low,
                west: WallSide::None,
                north: WallSide::None,
            } => Ok(27859u32),
            GeneratedStruct18 {
                east: WallSide::Low,
                south: WallSide::Tall,
                bottom: false,
                west: WallSide::Low,
                north: WallSide::None,
            } => Ok(27860u32),
            GeneratedStruct18 {
                south: WallSide::Tall,
                west: WallSide::Tall,
                north: WallSide::None,
                bottom: false,
                east: WallSide::Low,
            } => Ok(27861u32),
            GeneratedStruct18 {
                west: WallSide::None,
                east: WallSide::Low,
                bottom: false,
                south: WallSide::None,
                north: WallSide::Low,
            } => Ok(27862u32),
            GeneratedStruct18 {
                west: WallSide::Low,
                north: WallSide::Low,
                bottom: false,
                east: WallSide::Low,
                south: WallSide::None,
            } => Ok(27863u32),
            GeneratedStruct18 {
                bottom: false,
                south: WallSide::None,
                north: WallSide::Low,
                west: WallSide::Tall,
                east: WallSide::Low,
            } => Ok(27864u32),
            GeneratedStruct18 {
                south: WallSide::Low,
                west: WallSide::None,
                bottom: false,
                east: WallSide::Low,
                north: WallSide::Low,
            } => Ok(27865u32),
            GeneratedStruct18 {
                east: WallSide::Low,
                south: WallSide::Low,
                west: WallSide::Low,
                north: WallSide::Low,
                bottom: false,
            } => Ok(27866u32),
            GeneratedStruct18 {
                north: WallSide::Low,
                east: WallSide::Low,
                bottom: false,
                south: WallSide::Low,
                west: WallSide::Tall,
            } => Ok(27867u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::None,
                north: WallSide::Low,
            } => Ok(27868u32),
            GeneratedStruct18 {
                north: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::Low,
                east: WallSide::Low,
                bottom: false,
            } => Ok(27869u32),
            GeneratedStruct18 {
                east: WallSide::Low,
                bottom: false,
                north: WallSide::Low,
                south: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27870u32),
            GeneratedStruct18 {
                south: WallSide::None,
                bottom: false,
                east: WallSide::Low,
                west: WallSide::None,
                north: WallSide::Tall,
            } => Ok(27871u32),
            GeneratedStruct18 {
                west: WallSide::Low,
                north: WallSide::Tall,
                east: WallSide::Low,
                bottom: false,
                south: WallSide::None,
            } => Ok(27872u32),
            GeneratedStruct18 {
                east: WallSide::Low,
                bottom: false,
                west: WallSide::Tall,
                south: WallSide::None,
                north: WallSide::Tall,
            } => Ok(27873u32),
            GeneratedStruct18 {
                west: WallSide::None,
                south: WallSide::Low,
                east: WallSide::Low,
                bottom: false,
                north: WallSide::Tall,
            } => Ok(27874u32),
            GeneratedStruct18 {
                west: WallSide::Low,
                east: WallSide::Low,
                bottom: false,
                north: WallSide::Tall,
                south: WallSide::Low,
            } => Ok(27875u32),
            GeneratedStruct18 {
                west: WallSide::Tall,
                south: WallSide::Low,
                bottom: false,
                east: WallSide::Low,
                north: WallSide::Tall,
            } => Ok(27876u32),
            GeneratedStruct18 {
                east: WallSide::Low,
                north: WallSide::Tall,
                bottom: false,
                south: WallSide::Tall,
                west: WallSide::None,
            } => Ok(27877u32),
            GeneratedStruct18 {
                east: WallSide::Low,
                west: WallSide::Low,
                bottom: false,
                south: WallSide::Tall,
                north: WallSide::Tall,
            } => Ok(27878u32),
            GeneratedStruct18 {
                bottom: false,
                south: WallSide::Tall,
                west: WallSide::Tall,
                east: WallSide::Low,
                north: WallSide::Tall,
            } => Ok(27879u32),
            GeneratedStruct18 {
                north: WallSide::None,
                west: WallSide::None,
                bottom: false,
                east: WallSide::Tall,
                south: WallSide::None,
            } => Ok(27880u32),
            GeneratedStruct18 {
                north: WallSide::None,
                bottom: false,
                south: WallSide::None,
                east: WallSide::Tall,
                west: WallSide::Low,
            } => Ok(27881u32),
            GeneratedStruct18 {
                north: WallSide::None,
                bottom: false,
                east: WallSide::Tall,
                south: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27882u32),
            GeneratedStruct18 {
                east: WallSide::Tall,
                north: WallSide::None,
                south: WallSide::Low,
                west: WallSide::None,
                bottom: false,
            } => Ok(27883u32),
            GeneratedStruct18 {
                west: WallSide::Low,
                north: WallSide::None,
                east: WallSide::Tall,
                bottom: false,
                south: WallSide::Low,
            } => Ok(27884u32),
            GeneratedStruct18 {
                north: WallSide::None,
                bottom: false,
                south: WallSide::Low,
                west: WallSide::Tall,
                east: WallSide::Tall,
            } => Ok(27885u32),
            GeneratedStruct18 {
                bottom: false,
                north: WallSide::None,
                west: WallSide::None,
                south: WallSide::Tall,
                east: WallSide::Tall,
            } => Ok(27886u32),
            GeneratedStruct18 {
                west: WallSide::Low,
                east: WallSide::Tall,
                bottom: false,
                north: WallSide::None,
                south: WallSide::Tall,
            } => Ok(27887u32),
            GeneratedStruct18 {
                north: WallSide::None,
                bottom: false,
                east: WallSide::Tall,
                south: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27888u32),
            GeneratedStruct18 {
                south: WallSide::None,
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Low,
                west: WallSide::None,
            } => Ok(27889u32),
            GeneratedStruct18 {
                east: WallSide::Tall,
                bottom: false,
                south: WallSide::None,
                west: WallSide::Low,
                north: WallSide::Low,
            } => Ok(27890u32),
            GeneratedStruct18 {
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::None,
                west: WallSide::Tall,
            } => Ok(27891u32),
            GeneratedStruct18 {
                west: WallSide::None,
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::Low,
            } => Ok(27892u32),
            GeneratedStruct18 {
                west: WallSide::Low,
                south: WallSide::Low,
                east: WallSide::Tall,
                bottom: false,
                north: WallSide::Low,
            } => Ok(27893u32),
            GeneratedStruct18 {
                bottom: false,
                west: WallSide::Tall,
                east: WallSide::Tall,
                south: WallSide::Low,
                north: WallSide::Low,
            } => Ok(27894u32),
            GeneratedStruct18 {
                east: WallSide::Tall,
                north: WallSide::Low,
                bottom: false,
                south: WallSide::Tall,
                west: WallSide::None,
            } => Ok(27895u32),
            GeneratedStruct18 {
                bottom: false,
                west: WallSide::Low,
                east: WallSide::Tall,
                north: WallSide::Low,
                south: WallSide::Tall,
            } => Ok(27896u32),
            GeneratedStruct18 {
                east: WallSide::Tall,
                bottom: false,
                south: WallSide::Tall,
                west: WallSide::Tall,
                north: WallSide::Low,
            } => Ok(27897u32),
            GeneratedStruct18 {
                east: WallSide::Tall,
                north: WallSide::Tall,
                bottom: false,
                south: WallSide::None,
                west: WallSide::None,
            } => Ok(27898u32),
            GeneratedStruct18 {
                south: WallSide::None,
                north: WallSide::Tall,
                west: WallSide::Low,
                east: WallSide::Tall,
                bottom: false,
            } => Ok(27899u32),
            GeneratedStruct18 {
                north: WallSide::Tall,
                west: WallSide::Tall,
                east: WallSide::Tall,
                bottom: false,
                south: WallSide::None,
            } => Ok(27900u32),
            GeneratedStruct18 {
                bottom: false,
                south: WallSide::Low,
                east: WallSide::Tall,
                north: WallSide::Tall,
                west: WallSide::None,
            } => Ok(27901u32),
            GeneratedStruct18 {
                south: WallSide::Low,
                west: WallSide::Low,
                bottom: false,
                east: WallSide::Tall,
                north: WallSide::Tall,
            } => Ok(27902u32),
            GeneratedStruct18 {
                bottom: false,
                west: WallSide::Tall,
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::Low,
            } => Ok(27903u32),
            GeneratedStruct18 {
                west: WallSide::None,
                east: WallSide::Tall,
                north: WallSide::Tall,
                south: WallSide::Tall,
                bottom: false,
            } => Ok(27904u32),
            GeneratedStruct18 {
                bottom: false,
                west: WallSide::Low,
                north: WallSide::Tall,
                east: WallSide::Tall,
                south: WallSide::Tall,
            } => Ok(27905u32),
            GeneratedStruct18 {
                east: WallSide::Tall,
                north: WallSide::Tall,
                bottom: false,
                south: WallSide::Tall,
                west: WallSide::Tall,
            } => Ok(27906u32),
            _ => Err(()),
        }
    }
}
