#[allow(unused_imports)]
use ferrumc_block_properties::*;
#[allow(dead_code)]
pub struct GeneratedStruct7 {
    pub attached: bool,
    pub disarmed: bool,
    pub east: bool,
    pub north: bool,
    pub powered: bool,
    pub south: bool,
    pub west: bool,
}
impl TryFrom<u32> for GeneratedStruct7 {
    type Error = ();
    fn try_from(value: u32) -> Result<Self, Self::Error> {
        match value {
            8321u32 => Ok(GeneratedStruct7 {
                attached: true,
                north: true,
                south: true,
                west: true,
                disarmed: true,
                east: true,
                powered: true,
            }),
            8322u32 => Ok(GeneratedStruct7 {
                powered: true,
                disarmed: true,
                attached: true,
                east: true,
                south: true,
                west: false,
                north: true,
            }),
            8323u32 => Ok(GeneratedStruct7 {
                north: true,
                powered: true,
                south: false,
                west: true,
                attached: true,
                disarmed: true,
                east: true,
            }),
            8324u32 => Ok(GeneratedStruct7 {
                attached: true,
                east: true,
                disarmed: true,
                north: true,
                powered: true,
                south: false,
                west: false,
            }),
            8325u32 => Ok(GeneratedStruct7 {
                powered: false,
                east: true,
                west: true,
                attached: true,
                north: true,
                south: true,
                disarmed: true,
            }),
            8326u32 => Ok(GeneratedStruct7 {
                south: true,
                west: false,
                attached: true,
                north: true,
                powered: false,
                east: true,
                disarmed: true,
            }),
            8327u32 => Ok(GeneratedStruct7 {
                north: true,
                east: true,
                disarmed: true,
                south: false,
                west: true,
                attached: true,
                powered: false,
            }),
            8328u32 => Ok(GeneratedStruct7 {
                south: false,
                west: false,
                east: true,
                attached: true,
                disarmed: true,
                north: true,
                powered: false,
            }),
            8329u32 => Ok(GeneratedStruct7 {
                west: true,
                east: true,
                powered: true,
                disarmed: true,
                south: true,
                north: false,
                attached: true,
            }),
            8330u32 => Ok(GeneratedStruct7 {
                attached: true,
                disarmed: true,
                east: true,
                north: false,
                south: true,
                west: false,
                powered: true,
            }),
            8331u32 => Ok(GeneratedStruct7 {
                west: true,
                south: false,
                disarmed: true,
                attached: true,
                east: true,
                north: false,
                powered: true,
            }),
            8332u32 => Ok(GeneratedStruct7 {
                west: false,
                north: false,
                attached: true,
                south: false,
                east: true,
                powered: true,
                disarmed: true,
            }),
            8333u32 => Ok(GeneratedStruct7 {
                west: true,
                disarmed: true,
                east: true,
                powered: false,
                south: true,
                north: false,
                attached: true,
            }),
            8334u32 => Ok(GeneratedStruct7 {
                north: false,
                west: false,
                attached: true,
                disarmed: true,
                east: true,
                powered: false,
                south: true,
            }),
            8335u32 => Ok(GeneratedStruct7 {
                powered: false,
                attached: true,
                east: true,
                north: false,
                west: true,
                disarmed: true,
                south: false,
            }),
            8336u32 => Ok(GeneratedStruct7 {
                north: false,
                east: true,
                attached: true,
                south: false,
                powered: false,
                disarmed: true,
                west: false,
            }),
            8337u32 => Ok(GeneratedStruct7 {
                powered: true,
                west: true,
                disarmed: true,
                east: false,
                attached: true,
                south: true,
                north: true,
            }),
            8338u32 => Ok(GeneratedStruct7 {
                attached: true,
                south: true,
                west: false,
                east: false,
                north: true,
                disarmed: true,
                powered: true,
            }),
            8339u32 => Ok(GeneratedStruct7 {
                north: true,
                powered: true,
                east: false,
                south: false,
                west: true,
                disarmed: true,
                attached: true,
            }),
            8340u32 => Ok(GeneratedStruct7 {
                disarmed: true,
                east: false,
                attached: true,
                powered: true,
                south: false,
                north: true,
                west: false,
            }),
            8341u32 => Ok(GeneratedStruct7 {
                east: false,
                attached: true,
                disarmed: true,
                south: true,
                north: true,
                west: true,
                powered: false,
            }),
            8342u32 => Ok(GeneratedStruct7 {
                attached: true,
                disarmed: true,
                east: false,
                north: true,
                powered: false,
                south: true,
                west: false,
            }),
            8343u32 => Ok(GeneratedStruct7 {
                attached: true,
                south: false,
                north: true,
                powered: false,
                disarmed: true,
                west: true,
                east: false,
            }),
            8344u32 => Ok(GeneratedStruct7 {
                west: false,
                east: false,
                south: false,
                north: true,
                powered: false,
                attached: true,
                disarmed: true,
            }),
            8345u32 => Ok(GeneratedStruct7 {
                attached: true,
                north: false,
                powered: true,
                east: false,
                disarmed: true,
                south: true,
                west: true,
            }),
            8346u32 => Ok(GeneratedStruct7 {
                east: false,
                south: true,
                disarmed: true,
                powered: true,
                west: false,
                north: false,
                attached: true,
            }),
            8347u32 => Ok(GeneratedStruct7 {
                south: false,
                north: false,
                west: true,
                disarmed: true,
                attached: true,
                east: false,
                powered: true,
            }),
            8348u32 => Ok(GeneratedStruct7 {
                attached: true,
                north: false,
                west: false,
                disarmed: true,
                east: false,
                powered: true,
                south: false,
            }),
            8349u32 => Ok(GeneratedStruct7 {
                north: false,
                powered: false,
                disarmed: true,
                attached: true,
                west: true,
                south: true,
                east: false,
            }),
            8350u32 => Ok(GeneratedStruct7 {
                attached: true,
                north: false,
                powered: false,
                west: false,
                disarmed: true,
                east: false,
                south: true,
            }),
            8351u32 => Ok(GeneratedStruct7 {
                north: false,
                east: false,
                powered: false,
                south: false,
                attached: true,
                west: true,
                disarmed: true,
            }),
            8352u32 => Ok(GeneratedStruct7 {
                powered: false,
                disarmed: true,
                south: false,
                west: false,
                north: false,
                east: false,
                attached: true,
            }),
            8353u32 => Ok(GeneratedStruct7 {
                east: true,
                powered: true,
                west: true,
                attached: true,
                disarmed: false,
                north: true,
                south: true,
            }),
            8354u32 => Ok(GeneratedStruct7 {
                north: true,
                south: true,
                west: false,
                disarmed: false,
                powered: true,
                east: true,
                attached: true,
            }),
            8355u32 => Ok(GeneratedStruct7 {
                attached: true,
                disarmed: false,
                east: true,
                powered: true,
                north: true,
                south: false,
                west: true,
            }),
            8356u32 => Ok(GeneratedStruct7 {
                south: false,
                attached: true,
                disarmed: false,
                east: true,
                north: true,
                powered: true,
                west: false,
            }),
            8357u32 => Ok(GeneratedStruct7 {
                north: true,
                east: true,
                west: true,
                attached: true,
                powered: false,
                south: true,
                disarmed: false,
            }),
            8358u32 => Ok(GeneratedStruct7 {
                north: true,
                powered: false,
                west: false,
                east: true,
                south: true,
                attached: true,
                disarmed: false,
            }),
            8359u32 => Ok(GeneratedStruct7 {
                disarmed: false,
                attached: true,
                powered: false,
                north: true,
                south: false,
                west: true,
                east: true,
            }),
            8360u32 => Ok(GeneratedStruct7 {
                disarmed: false,
                attached: true,
                north: true,
                powered: false,
                south: false,
                west: false,
                east: true,
            }),
            8361u32 => Ok(GeneratedStruct7 {
                east: true,
                powered: true,
                north: false,
                disarmed: false,
                south: true,
                attached: true,
                west: true,
            }),
            8362u32 => Ok(GeneratedStruct7 {
                powered: true,
                west: false,
                east: true,
                disarmed: false,
                north: false,
                attached: true,
                south: true,
            }),
            8363u32 => Ok(GeneratedStruct7 {
                east: true,
                powered: true,
                attached: true,
                south: false,
                north: false,
                west: true,
                disarmed: false,
            }),
            8364u32 => Ok(GeneratedStruct7 {
                south: false,
                disarmed: false,
                north: false,
                west: false,
                east: true,
                powered: true,
                attached: true,
            }),
            8365u32 => Ok(GeneratedStruct7 {
                south: true,
                powered: false,
                attached: true,
                west: true,
                north: false,
                east: true,
                disarmed: false,
            }),
            8366u32 => Ok(GeneratedStruct7 {
                attached: true,
                south: true,
                disarmed: false,
                north: false,
                powered: false,
                west: false,
                east: true,
            }),
            8367u32 => Ok(GeneratedStruct7 {
                attached: true,
                east: true,
                north: false,
                powered: false,
                disarmed: false,
                south: false,
                west: true,
            }),
            8368u32 => Ok(GeneratedStruct7 {
                attached: true,
                east: true,
                north: false,
                powered: false,
                west: false,
                south: false,
                disarmed: false,
            }),
            8369u32 => Ok(GeneratedStruct7 {
                attached: true,
                south: true,
                west: true,
                east: false,
                north: true,
                powered: true,
                disarmed: false,
            }),
            8370u32 => Ok(GeneratedStruct7 {
                attached: true,
                disarmed: false,
                south: true,
                west: false,
                powered: true,
                east: false,
                north: true,
            }),
            8371u32 => Ok(GeneratedStruct7 {
                north: true,
                attached: true,
                powered: true,
                east: false,
                disarmed: false,
                west: true,
                south: false,
            }),
            8372u32 => Ok(GeneratedStruct7 {
                east: false,
                south: false,
                north: true,
                disarmed: false,
                west: false,
                attached: true,
                powered: true,
            }),
            8373u32 => Ok(GeneratedStruct7 {
                powered: false,
                attached: true,
                disarmed: false,
                north: true,
                south: true,
                west: true,
                east: false,
            }),
            8374u32 => Ok(GeneratedStruct7 {
                north: true,
                disarmed: false,
                south: true,
                powered: false,
                east: false,
                west: false,
                attached: true,
            }),
            8375u32 => Ok(GeneratedStruct7 {
                powered: false,
                disarmed: false,
                east: false,
                attached: true,
                north: true,
                south: false,
                west: true,
            }),
            8376u32 => Ok(GeneratedStruct7 {
                east: false,
                west: false,
                attached: true,
                north: true,
                disarmed: false,
                powered: false,
                south: false,
            }),
            8377u32 => Ok(GeneratedStruct7 {
                attached: true,
                north: false,
                disarmed: false,
                east: false,
                powered: true,
                south: true,
                west: true,
            }),
            8378u32 => Ok(GeneratedStruct7 {
                attached: true,
                disarmed: false,
                east: false,
                powered: true,
                south: true,
                west: false,
                north: false,
            }),
            8379u32 => Ok(GeneratedStruct7 {
                north: false,
                west: true,
                south: false,
                powered: true,
                east: false,
                attached: true,
                disarmed: false,
            }),
            8380u32 => Ok(GeneratedStruct7 {
                east: false,
                attached: true,
                north: false,
                powered: true,
                disarmed: false,
                south: false,
                west: false,
            }),
            8381u32 => Ok(GeneratedStruct7 {
                east: false,
                attached: true,
                south: true,
                powered: false,
                west: true,
                north: false,
                disarmed: false,
            }),
            8382u32 => Ok(GeneratedStruct7 {
                disarmed: false,
                west: false,
                south: true,
                attached: true,
                north: false,
                powered: false,
                east: false,
            }),
            8383u32 => Ok(GeneratedStruct7 {
                west: true,
                north: false,
                east: false,
                powered: false,
                attached: true,
                disarmed: false,
                south: false,
            }),
            8384u32 => Ok(GeneratedStruct7 {
                west: false,
                disarmed: false,
                attached: true,
                powered: false,
                east: false,
                north: false,
                south: false,
            }),
            8385u32 => Ok(GeneratedStruct7 {
                powered: true,
                attached: false,
                disarmed: true,
                east: true,
                north: true,
                south: true,
                west: true,
            }),
            8386u32 => Ok(GeneratedStruct7 {
                north: true,
                powered: true,
                south: true,
                west: false,
                attached: false,
                disarmed: true,
                east: true,
            }),
            8387u32 => Ok(GeneratedStruct7 {
                north: true,
                south: false,
                west: true,
                east: true,
                powered: true,
                attached: false,
                disarmed: true,
            }),
            8388u32 => Ok(GeneratedStruct7 {
                east: true,
                north: true,
                attached: false,
                powered: true,
                south: false,
                west: false,
                disarmed: true,
            }),
            8389u32 => Ok(GeneratedStruct7 {
                powered: false,
                east: true,
                north: true,
                attached: false,
                south: true,
                disarmed: true,
                west: true,
            }),
            8390u32 => Ok(GeneratedStruct7 {
                attached: false,
                disarmed: true,
                north: true,
                south: true,
                west: false,
                powered: false,
                east: true,
            }),
            8391u32 => Ok(GeneratedStruct7 {
                north: true,
                disarmed: true,
                powered: false,
                south: false,
                east: true,
                attached: false,
                west: true,
            }),
            8392u32 => Ok(GeneratedStruct7 {
                attached: false,
                disarmed: true,
                east: true,
                north: true,
                powered: false,
                south: false,
                west: false,
            }),
            8393u32 => Ok(GeneratedStruct7 {
                disarmed: true,
                east: true,
                west: true,
                north: false,
                attached: false,
                powered: true,
                south: true,
            }),
            8394u32 => Ok(GeneratedStruct7 {
                disarmed: true,
                north: false,
                east: true,
                powered: true,
                south: true,
                west: false,
                attached: false,
            }),
            8395u32 => Ok(GeneratedStruct7 {
                south: false,
                attached: false,
                west: true,
                powered: true,
                disarmed: true,
                north: false,
                east: true,
            }),
            8396u32 => Ok(GeneratedStruct7 {
                attached: false,
                south: false,
                east: true,
                disarmed: true,
                west: false,
                north: false,
                powered: true,
            }),
            8397u32 => Ok(GeneratedStruct7 {
                north: false,
                powered: false,
                east: true,
                west: true,
                attached: false,
                disarmed: true,
                south: true,
            }),
            8398u32 => Ok(GeneratedStruct7 {
                north: false,
                south: true,
                disarmed: true,
                west: false,
                powered: false,
                east: true,
                attached: false,
            }),
            8399u32 => Ok(GeneratedStruct7 {
                powered: false,
                west: true,
                east: true,
                south: false,
                north: false,
                disarmed: true,
                attached: false,
            }),
            8400u32 => Ok(GeneratedStruct7 {
                powered: false,
                south: false,
                attached: false,
                west: false,
                north: false,
                disarmed: true,
                east: true,
            }),
            8401u32 => Ok(GeneratedStruct7 {
                west: true,
                east: false,
                attached: false,
                south: true,
                disarmed: true,
                north: true,
                powered: true,
            }),
            8402u32 => Ok(GeneratedStruct7 {
                disarmed: true,
                attached: false,
                east: false,
                powered: true,
                south: true,
                north: true,
                west: false,
            }),
            8403u32 => Ok(GeneratedStruct7 {
                powered: true,
                west: true,
                east: false,
                attached: false,
                north: true,
                south: false,
                disarmed: true,
            }),
            8404u32 => Ok(GeneratedStruct7 {
                west: false,
                powered: true,
                north: true,
                south: false,
                attached: false,
                east: false,
                disarmed: true,
            }),
            8405u32 => Ok(GeneratedStruct7 {
                attached: false,
                powered: false,
                south: true,
                west: true,
                east: false,
                disarmed: true,
                north: true,
            }),
            8406u32 => Ok(GeneratedStruct7 {
                west: false,
                south: true,
                attached: false,
                disarmed: true,
                north: true,
                east: false,
                powered: false,
            }),
            8407u32 => Ok(GeneratedStruct7 {
                east: false,
                north: true,
                powered: false,
                west: true,
                attached: false,
                disarmed: true,
                south: false,
            }),
            8408u32 => Ok(GeneratedStruct7 {
                north: true,
                powered: false,
                disarmed: true,
                south: false,
                east: false,
                west: false,
                attached: false,
            }),
            8409u32 => Ok(GeneratedStruct7 {
                west: true,
                disarmed: true,
                attached: false,
                north: false,
                powered: true,
                east: false,
                south: true,
            }),
            8410u32 => Ok(GeneratedStruct7 {
                powered: true,
                west: false,
                attached: false,
                north: false,
                disarmed: true,
                east: false,
                south: true,
            }),
            8411u32 => Ok(GeneratedStruct7 {
                disarmed: true,
                north: false,
                powered: true,
                south: false,
                west: true,
                east: false,
                attached: false,
            }),
            8412u32 => Ok(GeneratedStruct7 {
                north: false,
                powered: true,
                west: false,
                attached: false,
                south: false,
                east: false,
                disarmed: true,
            }),
            8413u32 => Ok(GeneratedStruct7 {
                attached: false,
                east: false,
                west: true,
                disarmed: true,
                north: false,
                south: true,
                powered: false,
            }),
            8414u32 => Ok(GeneratedStruct7 {
                east: false,
                north: false,
                powered: false,
                attached: false,
                disarmed: true,
                south: true,
                west: false,
            }),
            8415u32 => Ok(GeneratedStruct7 {
                attached: false,
                north: false,
                powered: false,
                south: false,
                west: true,
                east: false,
                disarmed: true,
            }),
            8416u32 => Ok(GeneratedStruct7 {
                east: false,
                south: false,
                attached: false,
                disarmed: true,
                west: false,
                north: false,
                powered: false,
            }),
            8417u32 => Ok(GeneratedStruct7 {
                attached: false,
                east: true,
                powered: true,
                north: true,
                south: true,
                disarmed: false,
                west: true,
            }),
            8418u32 => Ok(GeneratedStruct7 {
                east: true,
                attached: false,
                south: true,
                disarmed: false,
                powered: true,
                north: true,
                west: false,
            }),
            8419u32 => Ok(GeneratedStruct7 {
                attached: false,
                east: true,
                south: false,
                west: true,
                disarmed: false,
                north: true,
                powered: true,
            }),
            8420u32 => Ok(GeneratedStruct7 {
                south: false,
                north: true,
                powered: true,
                west: false,
                attached: false,
                disarmed: false,
                east: true,
            }),
            8421u32 => Ok(GeneratedStruct7 {
                powered: false,
                west: true,
                north: true,
                south: true,
                attached: false,
                disarmed: false,
                east: true,
            }),
            8422u32 => Ok(GeneratedStruct7 {
                east: true,
                north: true,
                west: false,
                attached: false,
                powered: false,
                disarmed: false,
                south: true,
            }),
            8423u32 => Ok(GeneratedStruct7 {
                east: true,
                north: true,
                powered: false,
                south: false,
                west: true,
                attached: false,
                disarmed: false,
            }),
            8424u32 => Ok(GeneratedStruct7 {
                attached: false,
                west: false,
                north: true,
                south: false,
                disarmed: false,
                east: true,
                powered: false,
            }),
            8425u32 => Ok(GeneratedStruct7 {
                powered: true,
                disarmed: false,
                attached: false,
                south: true,
                west: true,
                north: false,
                east: true,
            }),
            8426u32 => Ok(GeneratedStruct7 {
                east: true,
                north: false,
                west: false,
                attached: false,
                disarmed: false,
                powered: true,
                south: true,
            }),
            8427u32 => Ok(GeneratedStruct7 {
                powered: true,
                west: true,
                disarmed: false,
                attached: false,
                east: true,
                north: false,
                south: false,
            }),
            8428u32 => Ok(GeneratedStruct7 {
                east: true,
                south: false,
                north: false,
                west: false,
                disarmed: false,
                powered: true,
                attached: false,
            }),
            8429u32 => Ok(GeneratedStruct7 {
                west: true,
                attached: false,
                east: true,
                north: false,
                powered: false,
                south: true,
                disarmed: false,
            }),
            8430u32 => Ok(GeneratedStruct7 {
                south: true,
                powered: false,
                disarmed: false,
                west: false,
                attached: false,
                north: false,
                east: true,
            }),
            8431u32 => Ok(GeneratedStruct7 {
                north: false,
                east: true,
                powered: false,
                south: false,
                west: true,
                disarmed: false,
                attached: false,
            }),
            8432u32 => Ok(GeneratedStruct7 {
                north: false,
                disarmed: false,
                powered: false,
                south: false,
                attached: false,
                east: true,
                west: false,
            }),
            8433u32 => Ok(GeneratedStruct7 {
                south: true,
                disarmed: false,
                east: false,
                north: true,
                attached: false,
                powered: true,
                west: true,
            }),
            8434u32 => Ok(GeneratedStruct7 {
                powered: true,
                disarmed: false,
                attached: false,
                south: true,
                east: false,
                north: true,
                west: false,
            }),
            8435u32 => Ok(GeneratedStruct7 {
                attached: false,
                south: false,
                disarmed: false,
                west: true,
                powered: true,
                north: true,
                east: false,
            }),
            8436u32 => Ok(GeneratedStruct7 {
                attached: false,
                powered: true,
                south: false,
                east: false,
                west: false,
                disarmed: false,
                north: true,
            }),
            8437u32 => Ok(GeneratedStruct7 {
                disarmed: false,
                east: false,
                north: true,
                powered: false,
                south: true,
                west: true,
                attached: false,
            }),
            8438u32 => Ok(GeneratedStruct7 {
                west: false,
                south: true,
                disarmed: false,
                east: false,
                north: true,
                attached: false,
                powered: false,
            }),
            8439u32 => Ok(GeneratedStruct7 {
                south: false,
                west: true,
                north: true,
                powered: false,
                east: false,
                attached: false,
                disarmed: false,
            }),
            8440u32 => Ok(GeneratedStruct7 {
                north: true,
                disarmed: false,
                west: false,
                powered: false,
                south: false,
                attached: false,
                east: false,
            }),
            8441u32 => Ok(GeneratedStruct7 {
                disarmed: false,
                east: false,
                north: false,
                south: true,
                west: true,
                powered: true,
                attached: false,
            }),
            8442u32 => Ok(GeneratedStruct7 {
                south: true,
                attached: false,
                disarmed: false,
                north: false,
                powered: true,
                east: false,
                west: false,
            }),
            8443u32 => Ok(GeneratedStruct7 {
                north: false,
                powered: true,
                west: true,
                east: false,
                south: false,
                disarmed: false,
                attached: false,
            }),
            8444u32 => Ok(GeneratedStruct7 {
                north: false,
                east: false,
                disarmed: false,
                powered: true,
                south: false,
                attached: false,
                west: false,
            }),
            8445u32 => Ok(GeneratedStruct7 {
                east: false,
                disarmed: false,
                south: true,
                attached: false,
                powered: false,
                west: true,
                north: false,
            }),
            8446u32 => Ok(GeneratedStruct7 {
                attached: false,
                west: false,
                south: true,
                east: false,
                disarmed: false,
                north: false,
                powered: false,
            }),
            8447u32 => Ok(GeneratedStruct7 {
                east: false,
                powered: false,
                south: false,
                attached: false,
                disarmed: false,
                west: true,
                north: false,
            }),
            8448u32 => Ok(GeneratedStruct7 {
                east: false,
                south: false,
                disarmed: false,
                north: false,
                west: false,
                attached: false,
                powered: false,
            }),
            _ => Err(()),
        }
    }
}
impl TryInto<u32> for GeneratedStruct7 {
    type Error = ();
    fn try_into(self) -> Result<u32, Self::Error> {
        #[allow(unreachable_patterns)]
        match self {
            GeneratedStruct7 {
                attached: true,
                north: true,
                south: true,
                west: true,
                disarmed: true,
                east: true,
                powered: true,
            } => Ok(8321u32),
            GeneratedStruct7 {
                powered: true,
                disarmed: true,
                attached: true,
                east: true,
                south: true,
                west: false,
                north: true,
            } => Ok(8322u32),
            GeneratedStruct7 {
                north: true,
                powered: true,
                south: false,
                west: true,
                attached: true,
                disarmed: true,
                east: true,
            } => Ok(8323u32),
            GeneratedStruct7 {
                attached: true,
                east: true,
                disarmed: true,
                north: true,
                powered: true,
                south: false,
                west: false,
            } => Ok(8324u32),
            GeneratedStruct7 {
                powered: false,
                east: true,
                west: true,
                attached: true,
                north: true,
                south: true,
                disarmed: true,
            } => Ok(8325u32),
            GeneratedStruct7 {
                south: true,
                west: false,
                attached: true,
                north: true,
                powered: false,
                east: true,
                disarmed: true,
            } => Ok(8326u32),
            GeneratedStruct7 {
                north: true,
                east: true,
                disarmed: true,
                south: false,
                west: true,
                attached: true,
                powered: false,
            } => Ok(8327u32),
            GeneratedStruct7 {
                south: false,
                west: false,
                east: true,
                attached: true,
                disarmed: true,
                north: true,
                powered: false,
            } => Ok(8328u32),
            GeneratedStruct7 {
                west: true,
                east: true,
                powered: true,
                disarmed: true,
                south: true,
                north: false,
                attached: true,
            } => Ok(8329u32),
            GeneratedStruct7 {
                attached: true,
                disarmed: true,
                east: true,
                north: false,
                south: true,
                west: false,
                powered: true,
            } => Ok(8330u32),
            GeneratedStruct7 {
                west: true,
                south: false,
                disarmed: true,
                attached: true,
                east: true,
                north: false,
                powered: true,
            } => Ok(8331u32),
            GeneratedStruct7 {
                west: false,
                north: false,
                attached: true,
                south: false,
                east: true,
                powered: true,
                disarmed: true,
            } => Ok(8332u32),
            GeneratedStruct7 {
                west: true,
                disarmed: true,
                east: true,
                powered: false,
                south: true,
                north: false,
                attached: true,
            } => Ok(8333u32),
            GeneratedStruct7 {
                north: false,
                west: false,
                attached: true,
                disarmed: true,
                east: true,
                powered: false,
                south: true,
            } => Ok(8334u32),
            GeneratedStruct7 {
                powered: false,
                attached: true,
                east: true,
                north: false,
                west: true,
                disarmed: true,
                south: false,
            } => Ok(8335u32),
            GeneratedStruct7 {
                north: false,
                east: true,
                attached: true,
                south: false,
                powered: false,
                disarmed: true,
                west: false,
            } => Ok(8336u32),
            GeneratedStruct7 {
                powered: true,
                west: true,
                disarmed: true,
                east: false,
                attached: true,
                south: true,
                north: true,
            } => Ok(8337u32),
            GeneratedStruct7 {
                attached: true,
                south: true,
                west: false,
                east: false,
                north: true,
                disarmed: true,
                powered: true,
            } => Ok(8338u32),
            GeneratedStruct7 {
                north: true,
                powered: true,
                east: false,
                south: false,
                west: true,
                disarmed: true,
                attached: true,
            } => Ok(8339u32),
            GeneratedStruct7 {
                disarmed: true,
                east: false,
                attached: true,
                powered: true,
                south: false,
                north: true,
                west: false,
            } => Ok(8340u32),
            GeneratedStruct7 {
                east: false,
                attached: true,
                disarmed: true,
                south: true,
                north: true,
                west: true,
                powered: false,
            } => Ok(8341u32),
            GeneratedStruct7 {
                attached: true,
                disarmed: true,
                east: false,
                north: true,
                powered: false,
                south: true,
                west: false,
            } => Ok(8342u32),
            GeneratedStruct7 {
                attached: true,
                south: false,
                north: true,
                powered: false,
                disarmed: true,
                west: true,
                east: false,
            } => Ok(8343u32),
            GeneratedStruct7 {
                west: false,
                east: false,
                south: false,
                north: true,
                powered: false,
                attached: true,
                disarmed: true,
            } => Ok(8344u32),
            GeneratedStruct7 {
                attached: true,
                north: false,
                powered: true,
                east: false,
                disarmed: true,
                south: true,
                west: true,
            } => Ok(8345u32),
            GeneratedStruct7 {
                east: false,
                south: true,
                disarmed: true,
                powered: true,
                west: false,
                north: false,
                attached: true,
            } => Ok(8346u32),
            GeneratedStruct7 {
                south: false,
                north: false,
                west: true,
                disarmed: true,
                attached: true,
                east: false,
                powered: true,
            } => Ok(8347u32),
            GeneratedStruct7 {
                attached: true,
                north: false,
                west: false,
                disarmed: true,
                east: false,
                powered: true,
                south: false,
            } => Ok(8348u32),
            GeneratedStruct7 {
                north: false,
                powered: false,
                disarmed: true,
                attached: true,
                west: true,
                south: true,
                east: false,
            } => Ok(8349u32),
            GeneratedStruct7 {
                attached: true,
                north: false,
                powered: false,
                west: false,
                disarmed: true,
                east: false,
                south: true,
            } => Ok(8350u32),
            GeneratedStruct7 {
                north: false,
                east: false,
                powered: false,
                south: false,
                attached: true,
                west: true,
                disarmed: true,
            } => Ok(8351u32),
            GeneratedStruct7 {
                powered: false,
                disarmed: true,
                south: false,
                west: false,
                north: false,
                east: false,
                attached: true,
            } => Ok(8352u32),
            GeneratedStruct7 {
                east: true,
                powered: true,
                west: true,
                attached: true,
                disarmed: false,
                north: true,
                south: true,
            } => Ok(8353u32),
            GeneratedStruct7 {
                north: true,
                south: true,
                west: false,
                disarmed: false,
                powered: true,
                east: true,
                attached: true,
            } => Ok(8354u32),
            GeneratedStruct7 {
                attached: true,
                disarmed: false,
                east: true,
                powered: true,
                north: true,
                south: false,
                west: true,
            } => Ok(8355u32),
            GeneratedStruct7 {
                south: false,
                attached: true,
                disarmed: false,
                east: true,
                north: true,
                powered: true,
                west: false,
            } => Ok(8356u32),
            GeneratedStruct7 {
                north: true,
                east: true,
                west: true,
                attached: true,
                powered: false,
                south: true,
                disarmed: false,
            } => Ok(8357u32),
            GeneratedStruct7 {
                north: true,
                powered: false,
                west: false,
                east: true,
                south: true,
                attached: true,
                disarmed: false,
            } => Ok(8358u32),
            GeneratedStruct7 {
                disarmed: false,
                attached: true,
                powered: false,
                north: true,
                south: false,
                west: true,
                east: true,
            } => Ok(8359u32),
            GeneratedStruct7 {
                disarmed: false,
                attached: true,
                north: true,
                powered: false,
                south: false,
                west: false,
                east: true,
            } => Ok(8360u32),
            GeneratedStruct7 {
                east: true,
                powered: true,
                north: false,
                disarmed: false,
                south: true,
                attached: true,
                west: true,
            } => Ok(8361u32),
            GeneratedStruct7 {
                powered: true,
                west: false,
                east: true,
                disarmed: false,
                north: false,
                attached: true,
                south: true,
            } => Ok(8362u32),
            GeneratedStruct7 {
                east: true,
                powered: true,
                attached: true,
                south: false,
                north: false,
                west: true,
                disarmed: false,
            } => Ok(8363u32),
            GeneratedStruct7 {
                south: false,
                disarmed: false,
                north: false,
                west: false,
                east: true,
                powered: true,
                attached: true,
            } => Ok(8364u32),
            GeneratedStruct7 {
                south: true,
                powered: false,
                attached: true,
                west: true,
                north: false,
                east: true,
                disarmed: false,
            } => Ok(8365u32),
            GeneratedStruct7 {
                attached: true,
                south: true,
                disarmed: false,
                north: false,
                powered: false,
                west: false,
                east: true,
            } => Ok(8366u32),
            GeneratedStruct7 {
                attached: true,
                east: true,
                north: false,
                powered: false,
                disarmed: false,
                south: false,
                west: true,
            } => Ok(8367u32),
            GeneratedStruct7 {
                attached: true,
                east: true,
                north: false,
                powered: false,
                west: false,
                south: false,
                disarmed: false,
            } => Ok(8368u32),
            GeneratedStruct7 {
                attached: true,
                south: true,
                west: true,
                east: false,
                north: true,
                powered: true,
                disarmed: false,
            } => Ok(8369u32),
            GeneratedStruct7 {
                attached: true,
                disarmed: false,
                south: true,
                west: false,
                powered: true,
                east: false,
                north: true,
            } => Ok(8370u32),
            GeneratedStruct7 {
                north: true,
                attached: true,
                powered: true,
                east: false,
                disarmed: false,
                west: true,
                south: false,
            } => Ok(8371u32),
            GeneratedStruct7 {
                east: false,
                south: false,
                north: true,
                disarmed: false,
                west: false,
                attached: true,
                powered: true,
            } => Ok(8372u32),
            GeneratedStruct7 {
                powered: false,
                attached: true,
                disarmed: false,
                north: true,
                south: true,
                west: true,
                east: false,
            } => Ok(8373u32),
            GeneratedStruct7 {
                north: true,
                disarmed: false,
                south: true,
                powered: false,
                east: false,
                west: false,
                attached: true,
            } => Ok(8374u32),
            GeneratedStruct7 {
                powered: false,
                disarmed: false,
                east: false,
                attached: true,
                north: true,
                south: false,
                west: true,
            } => Ok(8375u32),
            GeneratedStruct7 {
                east: false,
                west: false,
                attached: true,
                north: true,
                disarmed: false,
                powered: false,
                south: false,
            } => Ok(8376u32),
            GeneratedStruct7 {
                attached: true,
                north: false,
                disarmed: false,
                east: false,
                powered: true,
                south: true,
                west: true,
            } => Ok(8377u32),
            GeneratedStruct7 {
                attached: true,
                disarmed: false,
                east: false,
                powered: true,
                south: true,
                west: false,
                north: false,
            } => Ok(8378u32),
            GeneratedStruct7 {
                north: false,
                west: true,
                south: false,
                powered: true,
                east: false,
                attached: true,
                disarmed: false,
            } => Ok(8379u32),
            GeneratedStruct7 {
                east: false,
                attached: true,
                north: false,
                powered: true,
                disarmed: false,
                south: false,
                west: false,
            } => Ok(8380u32),
            GeneratedStruct7 {
                east: false,
                attached: true,
                south: true,
                powered: false,
                west: true,
                north: false,
                disarmed: false,
            } => Ok(8381u32),
            GeneratedStruct7 {
                disarmed: false,
                west: false,
                south: true,
                attached: true,
                north: false,
                powered: false,
                east: false,
            } => Ok(8382u32),
            GeneratedStruct7 {
                west: true,
                north: false,
                east: false,
                powered: false,
                attached: true,
                disarmed: false,
                south: false,
            } => Ok(8383u32),
            GeneratedStruct7 {
                west: false,
                disarmed: false,
                attached: true,
                powered: false,
                east: false,
                north: false,
                south: false,
            } => Ok(8384u32),
            GeneratedStruct7 {
                powered: true,
                attached: false,
                disarmed: true,
                east: true,
                north: true,
                south: true,
                west: true,
            } => Ok(8385u32),
            GeneratedStruct7 {
                north: true,
                powered: true,
                south: true,
                west: false,
                attached: false,
                disarmed: true,
                east: true,
            } => Ok(8386u32),
            GeneratedStruct7 {
                north: true,
                south: false,
                west: true,
                east: true,
                powered: true,
                attached: false,
                disarmed: true,
            } => Ok(8387u32),
            GeneratedStruct7 {
                east: true,
                north: true,
                attached: false,
                powered: true,
                south: false,
                west: false,
                disarmed: true,
            } => Ok(8388u32),
            GeneratedStruct7 {
                powered: false,
                east: true,
                north: true,
                attached: false,
                south: true,
                disarmed: true,
                west: true,
            } => Ok(8389u32),
            GeneratedStruct7 {
                attached: false,
                disarmed: true,
                north: true,
                south: true,
                west: false,
                powered: false,
                east: true,
            } => Ok(8390u32),
            GeneratedStruct7 {
                north: true,
                disarmed: true,
                powered: false,
                south: false,
                east: true,
                attached: false,
                west: true,
            } => Ok(8391u32),
            GeneratedStruct7 {
                attached: false,
                disarmed: true,
                east: true,
                north: true,
                powered: false,
                south: false,
                west: false,
            } => Ok(8392u32),
            GeneratedStruct7 {
                disarmed: true,
                east: true,
                west: true,
                north: false,
                attached: false,
                powered: true,
                south: true,
            } => Ok(8393u32),
            GeneratedStruct7 {
                disarmed: true,
                north: false,
                east: true,
                powered: true,
                south: true,
                west: false,
                attached: false,
            } => Ok(8394u32),
            GeneratedStruct7 {
                south: false,
                attached: false,
                west: true,
                powered: true,
                disarmed: true,
                north: false,
                east: true,
            } => Ok(8395u32),
            GeneratedStruct7 {
                attached: false,
                south: false,
                east: true,
                disarmed: true,
                west: false,
                north: false,
                powered: true,
            } => Ok(8396u32),
            GeneratedStruct7 {
                north: false,
                powered: false,
                east: true,
                west: true,
                attached: false,
                disarmed: true,
                south: true,
            } => Ok(8397u32),
            GeneratedStruct7 {
                north: false,
                south: true,
                disarmed: true,
                west: false,
                powered: false,
                east: true,
                attached: false,
            } => Ok(8398u32),
            GeneratedStruct7 {
                powered: false,
                west: true,
                east: true,
                south: false,
                north: false,
                disarmed: true,
                attached: false,
            } => Ok(8399u32),
            GeneratedStruct7 {
                powered: false,
                south: false,
                attached: false,
                west: false,
                north: false,
                disarmed: true,
                east: true,
            } => Ok(8400u32),
            GeneratedStruct7 {
                west: true,
                east: false,
                attached: false,
                south: true,
                disarmed: true,
                north: true,
                powered: true,
            } => Ok(8401u32),
            GeneratedStruct7 {
                disarmed: true,
                attached: false,
                east: false,
                powered: true,
                south: true,
                north: true,
                west: false,
            } => Ok(8402u32),
            GeneratedStruct7 {
                powered: true,
                west: true,
                east: false,
                attached: false,
                north: true,
                south: false,
                disarmed: true,
            } => Ok(8403u32),
            GeneratedStruct7 {
                west: false,
                powered: true,
                north: true,
                south: false,
                attached: false,
                east: false,
                disarmed: true,
            } => Ok(8404u32),
            GeneratedStruct7 {
                attached: false,
                powered: false,
                south: true,
                west: true,
                east: false,
                disarmed: true,
                north: true,
            } => Ok(8405u32),
            GeneratedStruct7 {
                west: false,
                south: true,
                attached: false,
                disarmed: true,
                north: true,
                east: false,
                powered: false,
            } => Ok(8406u32),
            GeneratedStruct7 {
                east: false,
                north: true,
                powered: false,
                west: true,
                attached: false,
                disarmed: true,
                south: false,
            } => Ok(8407u32),
            GeneratedStruct7 {
                north: true,
                powered: false,
                disarmed: true,
                south: false,
                east: false,
                west: false,
                attached: false,
            } => Ok(8408u32),
            GeneratedStruct7 {
                west: true,
                disarmed: true,
                attached: false,
                north: false,
                powered: true,
                east: false,
                south: true,
            } => Ok(8409u32),
            GeneratedStruct7 {
                powered: true,
                west: false,
                attached: false,
                north: false,
                disarmed: true,
                east: false,
                south: true,
            } => Ok(8410u32),
            GeneratedStruct7 {
                disarmed: true,
                north: false,
                powered: true,
                south: false,
                west: true,
                east: false,
                attached: false,
            } => Ok(8411u32),
            GeneratedStruct7 {
                north: false,
                powered: true,
                west: false,
                attached: false,
                south: false,
                east: false,
                disarmed: true,
            } => Ok(8412u32),
            GeneratedStruct7 {
                attached: false,
                east: false,
                west: true,
                disarmed: true,
                north: false,
                south: true,
                powered: false,
            } => Ok(8413u32),
            GeneratedStruct7 {
                east: false,
                north: false,
                powered: false,
                attached: false,
                disarmed: true,
                south: true,
                west: false,
            } => Ok(8414u32),
            GeneratedStruct7 {
                attached: false,
                north: false,
                powered: false,
                south: false,
                west: true,
                east: false,
                disarmed: true,
            } => Ok(8415u32),
            GeneratedStruct7 {
                east: false,
                south: false,
                attached: false,
                disarmed: true,
                west: false,
                north: false,
                powered: false,
            } => Ok(8416u32),
            GeneratedStruct7 {
                attached: false,
                east: true,
                powered: true,
                north: true,
                south: true,
                disarmed: false,
                west: true,
            } => Ok(8417u32),
            GeneratedStruct7 {
                east: true,
                attached: false,
                south: true,
                disarmed: false,
                powered: true,
                north: true,
                west: false,
            } => Ok(8418u32),
            GeneratedStruct7 {
                attached: false,
                east: true,
                south: false,
                west: true,
                disarmed: false,
                north: true,
                powered: true,
            } => Ok(8419u32),
            GeneratedStruct7 {
                south: false,
                north: true,
                powered: true,
                west: false,
                attached: false,
                disarmed: false,
                east: true,
            } => Ok(8420u32),
            GeneratedStruct7 {
                powered: false,
                west: true,
                north: true,
                south: true,
                attached: false,
                disarmed: false,
                east: true,
            } => Ok(8421u32),
            GeneratedStruct7 {
                east: true,
                north: true,
                west: false,
                attached: false,
                powered: false,
                disarmed: false,
                south: true,
            } => Ok(8422u32),
            GeneratedStruct7 {
                east: true,
                north: true,
                powered: false,
                south: false,
                west: true,
                attached: false,
                disarmed: false,
            } => Ok(8423u32),
            GeneratedStruct7 {
                attached: false,
                west: false,
                north: true,
                south: false,
                disarmed: false,
                east: true,
                powered: false,
            } => Ok(8424u32),
            GeneratedStruct7 {
                powered: true,
                disarmed: false,
                attached: false,
                south: true,
                west: true,
                north: false,
                east: true,
            } => Ok(8425u32),
            GeneratedStruct7 {
                east: true,
                north: false,
                west: false,
                attached: false,
                disarmed: false,
                powered: true,
                south: true,
            } => Ok(8426u32),
            GeneratedStruct7 {
                powered: true,
                west: true,
                disarmed: false,
                attached: false,
                east: true,
                north: false,
                south: false,
            } => Ok(8427u32),
            GeneratedStruct7 {
                east: true,
                south: false,
                north: false,
                west: false,
                disarmed: false,
                powered: true,
                attached: false,
            } => Ok(8428u32),
            GeneratedStruct7 {
                west: true,
                attached: false,
                east: true,
                north: false,
                powered: false,
                south: true,
                disarmed: false,
            } => Ok(8429u32),
            GeneratedStruct7 {
                south: true,
                powered: false,
                disarmed: false,
                west: false,
                attached: false,
                north: false,
                east: true,
            } => Ok(8430u32),
            GeneratedStruct7 {
                north: false,
                east: true,
                powered: false,
                south: false,
                west: true,
                disarmed: false,
                attached: false,
            } => Ok(8431u32),
            GeneratedStruct7 {
                north: false,
                disarmed: false,
                powered: false,
                south: false,
                attached: false,
                east: true,
                west: false,
            } => Ok(8432u32),
            GeneratedStruct7 {
                south: true,
                disarmed: false,
                east: false,
                north: true,
                attached: false,
                powered: true,
                west: true,
            } => Ok(8433u32),
            GeneratedStruct7 {
                powered: true,
                disarmed: false,
                attached: false,
                south: true,
                east: false,
                north: true,
                west: false,
            } => Ok(8434u32),
            GeneratedStruct7 {
                attached: false,
                south: false,
                disarmed: false,
                west: true,
                powered: true,
                north: true,
                east: false,
            } => Ok(8435u32),
            GeneratedStruct7 {
                attached: false,
                powered: true,
                south: false,
                east: false,
                west: false,
                disarmed: false,
                north: true,
            } => Ok(8436u32),
            GeneratedStruct7 {
                disarmed: false,
                east: false,
                north: true,
                powered: false,
                south: true,
                west: true,
                attached: false,
            } => Ok(8437u32),
            GeneratedStruct7 {
                west: false,
                south: true,
                disarmed: false,
                east: false,
                north: true,
                attached: false,
                powered: false,
            } => Ok(8438u32),
            GeneratedStruct7 {
                south: false,
                west: true,
                north: true,
                powered: false,
                east: false,
                attached: false,
                disarmed: false,
            } => Ok(8439u32),
            GeneratedStruct7 {
                north: true,
                disarmed: false,
                west: false,
                powered: false,
                south: false,
                attached: false,
                east: false,
            } => Ok(8440u32),
            GeneratedStruct7 {
                disarmed: false,
                east: false,
                north: false,
                south: true,
                west: true,
                powered: true,
                attached: false,
            } => Ok(8441u32),
            GeneratedStruct7 {
                south: true,
                attached: false,
                disarmed: false,
                north: false,
                powered: true,
                east: false,
                west: false,
            } => Ok(8442u32),
            GeneratedStruct7 {
                north: false,
                powered: true,
                west: true,
                east: false,
                south: false,
                disarmed: false,
                attached: false,
            } => Ok(8443u32),
            GeneratedStruct7 {
                north: false,
                east: false,
                disarmed: false,
                powered: true,
                south: false,
                attached: false,
                west: false,
            } => Ok(8444u32),
            GeneratedStruct7 {
                east: false,
                disarmed: false,
                south: true,
                attached: false,
                powered: false,
                west: true,
                north: false,
            } => Ok(8445u32),
            GeneratedStruct7 {
                attached: false,
                west: false,
                south: true,
                east: false,
                disarmed: false,
                north: false,
                powered: false,
            } => Ok(8446u32),
            GeneratedStruct7 {
                east: false,
                powered: false,
                south: false,
                attached: false,
                disarmed: false,
                west: true,
                north: false,
            } => Ok(8447u32),
            GeneratedStruct7 {
                east: false,
                south: false,
                disarmed: false,
                north: false,
                west: false,
                attached: false,
                powered: false,
            } => Ok(8448u32),
            _ => Err(()),
        }
    }
}
