#[allow(unused_imports)]
use ferrumc_block_properties::*;
#[allow(dead_code)]
pub enum GeneratedStruct51Type {
    Campfire,
    SoulCampfire,
}
#[allow(dead_code)]
pub struct GeneratedStruct51 {
    pub block_type: GeneratedStruct51Type,
    pub facing: Direction,
    pub lit: bool,
    pub signal_fire: bool,
    pub waterlogged: bool,
}
impl TryFrom<u32> for GeneratedStruct51 {
    type Error = ();
    fn try_from(value: u32) -> Result<Self, Self::Error> {
        match value {
            19534u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                lit: true,
                signal_fire: true,
                facing: Direction::North,
                waterlogged: true,
            }),
            19535u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                signal_fire: true,
                lit: true,
                facing: Direction::North,
                waterlogged: false,
            }),
            19536u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                signal_fire: false,
                waterlogged: true,
                facing: Direction::North,
                lit: true,
            }),
            19537u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                facing: Direction::North,
                lit: true,
                signal_fire: false,
                waterlogged: false,
            }),
            19538u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                facing: Direction::North,
                signal_fire: true,
                waterlogged: true,
                lit: false,
            }),
            19539u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                lit: false,
                facing: Direction::North,
                signal_fire: true,
                waterlogged: false,
            }),
            19540u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                waterlogged: true,
                lit: false,
                facing: Direction::North,
                signal_fire: false,
            }),
            19541u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                waterlogged: false,
                facing: Direction::North,
                lit: false,
                signal_fire: false,
            }),
            19542u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                lit: true,
                signal_fire: true,
                waterlogged: true,
                facing: Direction::South,
            }),
            19543u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                waterlogged: false,
                lit: true,
                signal_fire: true,
                facing: Direction::South,
            }),
            19544u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                lit: true,
                facing: Direction::South,
                signal_fire: false,
                waterlogged: true,
            }),
            19545u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                facing: Direction::South,
                signal_fire: false,
                waterlogged: false,
                lit: true,
            }),
            19546u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                lit: false,
                facing: Direction::South,
                waterlogged: true,
                signal_fire: true,
            }),
            19547u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                lit: false,
                facing: Direction::South,
                signal_fire: true,
                waterlogged: false,
            }),
            19548u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                lit: false,
                signal_fire: false,
                waterlogged: true,
                facing: Direction::South,
            }),
            19549u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                signal_fire: false,
                lit: false,
                waterlogged: false,
                facing: Direction::South,
            }),
            19550u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                facing: Direction::West,
                lit: true,
                waterlogged: true,
                signal_fire: true,
            }),
            19551u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                waterlogged: false,
                facing: Direction::West,
                lit: true,
                signal_fire: true,
            }),
            19552u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                waterlogged: true,
                facing: Direction::West,
                signal_fire: false,
                lit: true,
            }),
            19553u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                lit: true,
                waterlogged: false,
                signal_fire: false,
                facing: Direction::West,
            }),
            19554u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                lit: false,
                signal_fire: true,
                facing: Direction::West,
                waterlogged: true,
            }),
            19555u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                signal_fire: true,
                lit: false,
                facing: Direction::West,
                waterlogged: false,
            }),
            19556u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                signal_fire: false,
                lit: false,
                waterlogged: true,
                facing: Direction::West,
            }),
            19557u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                lit: false,
                signal_fire: false,
                facing: Direction::West,
                waterlogged: false,
            }),
            19558u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                waterlogged: true,
                lit: true,
                facing: Direction::East,
                signal_fire: true,
            }),
            19559u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                signal_fire: true,
                lit: true,
                facing: Direction::East,
                waterlogged: false,
            }),
            19560u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                waterlogged: true,
                facing: Direction::East,
                lit: true,
                signal_fire: false,
            }),
            19561u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                waterlogged: false,
                lit: true,
                signal_fire: false,
                facing: Direction::East,
            }),
            19562u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                signal_fire: true,
                facing: Direction::East,
                lit: false,
                waterlogged: true,
            }),
            19563u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                lit: false,
                waterlogged: false,
                signal_fire: true,
                facing: Direction::East,
            }),
            19564u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                signal_fire: false,
                lit: false,
                waterlogged: true,
                facing: Direction::East,
            }),
            19565u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                facing: Direction::East,
                waterlogged: false,
                signal_fire: false,
                lit: false,
            }),
            19566u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                facing: Direction::North,
                signal_fire: true,
                lit: true,
                waterlogged: true,
            }),
            19567u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                waterlogged: false,
                signal_fire: true,
                facing: Direction::North,
                lit: true,
            }),
            19568u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                facing: Direction::North,
                waterlogged: true,
                lit: true,
                signal_fire: false,
            }),
            19569u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                signal_fire: false,
                facing: Direction::North,
                waterlogged: false,
                lit: true,
            }),
            19570u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                lit: false,
                facing: Direction::North,
                waterlogged: true,
                signal_fire: true,
            }),
            19571u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                waterlogged: false,
                lit: false,
                facing: Direction::North,
                signal_fire: true,
            }),
            19572u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                lit: false,
                signal_fire: false,
                facing: Direction::North,
                waterlogged: true,
            }),
            19573u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                signal_fire: false,
                waterlogged: false,
                facing: Direction::North,
                lit: false,
            }),
            19574u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                lit: true,
                facing: Direction::South,
                signal_fire: true,
                waterlogged: true,
            }),
            19575u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                facing: Direction::South,
                lit: true,
                signal_fire: true,
                waterlogged: false,
            }),
            19576u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                waterlogged: true,
                signal_fire: false,
                facing: Direction::South,
                lit: true,
            }),
            19577u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                facing: Direction::South,
                signal_fire: false,
                lit: true,
                waterlogged: false,
            }),
            19578u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                facing: Direction::South,
                signal_fire: true,
                waterlogged: true,
                lit: false,
            }),
            19579u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                lit: false,
                signal_fire: true,
                facing: Direction::South,
                waterlogged: false,
            }),
            19580u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                lit: false,
                facing: Direction::South,
                signal_fire: false,
                waterlogged: true,
            }),
            19581u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                lit: false,
                signal_fire: false,
                facing: Direction::South,
                waterlogged: false,
            }),
            19582u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                facing: Direction::West,
                lit: true,
                waterlogged: true,
                signal_fire: true,
            }),
            19583u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                waterlogged: false,
                signal_fire: true,
                lit: true,
                facing: Direction::West,
            }),
            19584u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                lit: true,
                facing: Direction::West,
                signal_fire: false,
                waterlogged: true,
            }),
            19585u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                waterlogged: false,
                facing: Direction::West,
                signal_fire: false,
                lit: true,
            }),
            19586u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                facing: Direction::West,
                waterlogged: true,
                signal_fire: true,
                lit: false,
            }),
            19587u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                facing: Direction::West,
                lit: false,
                waterlogged: false,
                signal_fire: true,
            }),
            19588u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                waterlogged: true,
                lit: false,
                signal_fire: false,
                facing: Direction::West,
            }),
            19589u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                lit: false,
                waterlogged: false,
                signal_fire: false,
                facing: Direction::West,
            }),
            19590u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                facing: Direction::East,
                signal_fire: true,
                lit: true,
                waterlogged: true,
            }),
            19591u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                signal_fire: true,
                waterlogged: false,
                facing: Direction::East,
                lit: true,
            }),
            19592u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                signal_fire: false,
                facing: Direction::East,
                waterlogged: true,
                lit: true,
            }),
            19593u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                waterlogged: false,
                lit: true,
                signal_fire: false,
                facing: Direction::East,
            }),
            19594u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                lit: false,
                facing: Direction::East,
                waterlogged: true,
                signal_fire: true,
            }),
            19595u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                signal_fire: true,
                waterlogged: false,
                facing: Direction::East,
                lit: false,
            }),
            19596u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                lit: false,
                waterlogged: true,
                facing: Direction::East,
                signal_fire: false,
            }),
            19597u32 => Ok(GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                signal_fire: false,
                facing: Direction::East,
                waterlogged: false,
                lit: false,
            }),
            _ => Err(()),
        }
    }
}
impl TryInto<u32> for GeneratedStruct51 {
    type Error = ();
    fn try_into(self) -> Result<u32, Self::Error> {
        #[allow(unreachable_patterns)]
        match self {
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                lit: true,
                signal_fire: true,
                facing: Direction::North,
                waterlogged: true,
            } => Ok(19534u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                signal_fire: true,
                lit: true,
                facing: Direction::North,
                waterlogged: false,
            } => Ok(19535u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                signal_fire: false,
                waterlogged: true,
                facing: Direction::North,
                lit: true,
            } => Ok(19536u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                facing: Direction::North,
                lit: true,
                signal_fire: false,
                waterlogged: false,
            } => Ok(19537u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                facing: Direction::North,
                signal_fire: true,
                waterlogged: true,
                lit: false,
            } => Ok(19538u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                lit: false,
                facing: Direction::North,
                signal_fire: true,
                waterlogged: false,
            } => Ok(19539u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                waterlogged: true,
                lit: false,
                facing: Direction::North,
                signal_fire: false,
            } => Ok(19540u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                waterlogged: false,
                facing: Direction::North,
                lit: false,
                signal_fire: false,
            } => Ok(19541u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                lit: true,
                signal_fire: true,
                waterlogged: true,
                facing: Direction::South,
            } => Ok(19542u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                waterlogged: false,
                lit: true,
                signal_fire: true,
                facing: Direction::South,
            } => Ok(19543u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                lit: true,
                facing: Direction::South,
                signal_fire: false,
                waterlogged: true,
            } => Ok(19544u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                facing: Direction::South,
                signal_fire: false,
                waterlogged: false,
                lit: true,
            } => Ok(19545u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                lit: false,
                facing: Direction::South,
                waterlogged: true,
                signal_fire: true,
            } => Ok(19546u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                lit: false,
                facing: Direction::South,
                signal_fire: true,
                waterlogged: false,
            } => Ok(19547u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                lit: false,
                signal_fire: false,
                waterlogged: true,
                facing: Direction::South,
            } => Ok(19548u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                signal_fire: false,
                lit: false,
                waterlogged: false,
                facing: Direction::South,
            } => Ok(19549u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                facing: Direction::West,
                lit: true,
                waterlogged: true,
                signal_fire: true,
            } => Ok(19550u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                waterlogged: false,
                facing: Direction::West,
                lit: true,
                signal_fire: true,
            } => Ok(19551u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                waterlogged: true,
                facing: Direction::West,
                signal_fire: false,
                lit: true,
            } => Ok(19552u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                lit: true,
                waterlogged: false,
                signal_fire: false,
                facing: Direction::West,
            } => Ok(19553u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                lit: false,
                signal_fire: true,
                facing: Direction::West,
                waterlogged: true,
            } => Ok(19554u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                signal_fire: true,
                lit: false,
                facing: Direction::West,
                waterlogged: false,
            } => Ok(19555u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                signal_fire: false,
                lit: false,
                waterlogged: true,
                facing: Direction::West,
            } => Ok(19556u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                lit: false,
                signal_fire: false,
                facing: Direction::West,
                waterlogged: false,
            } => Ok(19557u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                waterlogged: true,
                lit: true,
                facing: Direction::East,
                signal_fire: true,
            } => Ok(19558u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                signal_fire: true,
                lit: true,
                facing: Direction::East,
                waterlogged: false,
            } => Ok(19559u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                waterlogged: true,
                facing: Direction::East,
                lit: true,
                signal_fire: false,
            } => Ok(19560u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                waterlogged: false,
                lit: true,
                signal_fire: false,
                facing: Direction::East,
            } => Ok(19561u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                signal_fire: true,
                facing: Direction::East,
                lit: false,
                waterlogged: true,
            } => Ok(19562u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                lit: false,
                waterlogged: false,
                signal_fire: true,
                facing: Direction::East,
            } => Ok(19563u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                signal_fire: false,
                lit: false,
                waterlogged: true,
                facing: Direction::East,
            } => Ok(19564u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::Campfire,
                facing: Direction::East,
                waterlogged: false,
                signal_fire: false,
                lit: false,
            } => Ok(19565u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                facing: Direction::North,
                signal_fire: true,
                lit: true,
                waterlogged: true,
            } => Ok(19566u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                waterlogged: false,
                signal_fire: true,
                facing: Direction::North,
                lit: true,
            } => Ok(19567u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                facing: Direction::North,
                waterlogged: true,
                lit: true,
                signal_fire: false,
            } => Ok(19568u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                signal_fire: false,
                facing: Direction::North,
                waterlogged: false,
                lit: true,
            } => Ok(19569u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                lit: false,
                facing: Direction::North,
                waterlogged: true,
                signal_fire: true,
            } => Ok(19570u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                waterlogged: false,
                lit: false,
                facing: Direction::North,
                signal_fire: true,
            } => Ok(19571u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                lit: false,
                signal_fire: false,
                facing: Direction::North,
                waterlogged: true,
            } => Ok(19572u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                signal_fire: false,
                waterlogged: false,
                facing: Direction::North,
                lit: false,
            } => Ok(19573u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                lit: true,
                facing: Direction::South,
                signal_fire: true,
                waterlogged: true,
            } => Ok(19574u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                facing: Direction::South,
                lit: true,
                signal_fire: true,
                waterlogged: false,
            } => Ok(19575u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                waterlogged: true,
                signal_fire: false,
                facing: Direction::South,
                lit: true,
            } => Ok(19576u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                facing: Direction::South,
                signal_fire: false,
                lit: true,
                waterlogged: false,
            } => Ok(19577u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                facing: Direction::South,
                signal_fire: true,
                waterlogged: true,
                lit: false,
            } => Ok(19578u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                lit: false,
                signal_fire: true,
                facing: Direction::South,
                waterlogged: false,
            } => Ok(19579u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                lit: false,
                facing: Direction::South,
                signal_fire: false,
                waterlogged: true,
            } => Ok(19580u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                lit: false,
                signal_fire: false,
                facing: Direction::South,
                waterlogged: false,
            } => Ok(19581u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                facing: Direction::West,
                lit: true,
                waterlogged: true,
                signal_fire: true,
            } => Ok(19582u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                waterlogged: false,
                signal_fire: true,
                lit: true,
                facing: Direction::West,
            } => Ok(19583u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                lit: true,
                facing: Direction::West,
                signal_fire: false,
                waterlogged: true,
            } => Ok(19584u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                waterlogged: false,
                facing: Direction::West,
                signal_fire: false,
                lit: true,
            } => Ok(19585u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                facing: Direction::West,
                waterlogged: true,
                signal_fire: true,
                lit: false,
            } => Ok(19586u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                facing: Direction::West,
                lit: false,
                waterlogged: false,
                signal_fire: true,
            } => Ok(19587u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                waterlogged: true,
                lit: false,
                signal_fire: false,
                facing: Direction::West,
            } => Ok(19588u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                lit: false,
                waterlogged: false,
                signal_fire: false,
                facing: Direction::West,
            } => Ok(19589u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                facing: Direction::East,
                signal_fire: true,
                lit: true,
                waterlogged: true,
            } => Ok(19590u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                signal_fire: true,
                waterlogged: false,
                facing: Direction::East,
                lit: true,
            } => Ok(19591u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                signal_fire: false,
                facing: Direction::East,
                waterlogged: true,
                lit: true,
            } => Ok(19592u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                waterlogged: false,
                lit: true,
                signal_fire: false,
                facing: Direction::East,
            } => Ok(19593u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                lit: false,
                facing: Direction::East,
                waterlogged: true,
                signal_fire: true,
            } => Ok(19594u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                signal_fire: true,
                waterlogged: false,
                facing: Direction::East,
                lit: false,
            } => Ok(19595u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                lit: false,
                waterlogged: true,
                facing: Direction::East,
                signal_fire: false,
            } => Ok(19596u32),
            GeneratedStruct51 {
                block_type: GeneratedStruct51Type::SoulCampfire,
                signal_fire: false,
                facing: Direction::East,
                waterlogged: false,
                lit: false,
            } => Ok(19597u32),
            _ => Err(()),
        }
    }
}
