#[allow(unused_imports)]
use ferrumc_block_properties::*;
#[allow(dead_code)]
pub struct GeneratedStruct5 {
    pub age: i32,
    pub hanging: bool,
    pub stage: i32,
    pub waterlogged: bool,
}
impl TryFrom<u32> for GeneratedStruct5 {
    type Error = ();
    fn try_from(value: u32) -> Result<Self, Self::Error> {
        match value {
            45u32 => Ok(GeneratedStruct5 {
                hanging: true,
                age: 0i32,
                waterlogged: true,
                stage: 0i32,
            }),
            46u32 => Ok(GeneratedStruct5 {
                waterlogged: false,
                age: 0i32,
                stage: 0i32,
                hanging: true,
            }),
            47u32 => Ok(GeneratedStruct5 {
                waterlogged: true,
                stage: 1i32,
                age: 0i32,
                hanging: true,
            }),
            48u32 => Ok(GeneratedStruct5 {
                hanging: true,
                waterlogged: false,
                age: 0i32,
                stage: 1i32,
            }),
            49u32 => Ok(GeneratedStruct5 {
                age: 0i32,
                stage: 0i32,
                waterlogged: true,
                hanging: false,
            }),
            50u32 => Ok(GeneratedStruct5 {
                age: 0i32,
                stage: 0i32,
                hanging: false,
                waterlogged: false,
            }),
            51u32 => Ok(GeneratedStruct5 {
                age: 0i32,
                waterlogged: true,
                hanging: false,
                stage: 1i32,
            }),
            52u32 => Ok(GeneratedStruct5 {
                hanging: false,
                waterlogged: false,
                stage: 1i32,
                age: 0i32,
            }),
            53u32 => Ok(GeneratedStruct5 {
                stage: 0i32,
                waterlogged: true,
                hanging: true,
                age: 1i32,
            }),
            54u32 => Ok(GeneratedStruct5 {
                waterlogged: false,
                age: 1i32,
                hanging: true,
                stage: 0i32,
            }),
            55u32 => Ok(GeneratedStruct5 {
                age: 1i32,
                hanging: true,
                stage: 1i32,
                waterlogged: true,
            }),
            56u32 => Ok(GeneratedStruct5 {
                age: 1i32,
                waterlogged: false,
                hanging: true,
                stage: 1i32,
            }),
            57u32 => Ok(GeneratedStruct5 {
                age: 1i32,
                hanging: false,
                waterlogged: true,
                stage: 0i32,
            }),
            58u32 => Ok(GeneratedStruct5 {
                hanging: false,
                stage: 0i32,
                age: 1i32,
                waterlogged: false,
            }),
            59u32 => Ok(GeneratedStruct5 {
                waterlogged: true,
                hanging: false,
                age: 1i32,
                stage: 1i32,
            }),
            60u32 => Ok(GeneratedStruct5 {
                age: 1i32,
                stage: 1i32,
                waterlogged: false,
                hanging: false,
            }),
            61u32 => Ok(GeneratedStruct5 {
                stage: 0i32,
                waterlogged: true,
                hanging: true,
                age: 2i32,
            }),
            62u32 => Ok(GeneratedStruct5 {
                stage: 0i32,
                age: 2i32,
                hanging: true,
                waterlogged: false,
            }),
            63u32 => Ok(GeneratedStruct5 {
                age: 2i32,
                stage: 1i32,
                hanging: true,
                waterlogged: true,
            }),
            64u32 => Ok(GeneratedStruct5 {
                hanging: true,
                age: 2i32,
                waterlogged: false,
                stage: 1i32,
            }),
            65u32 => Ok(GeneratedStruct5 {
                hanging: false,
                stage: 0i32,
                waterlogged: true,
                age: 2i32,
            }),
            66u32 => Ok(GeneratedStruct5 {
                hanging: false,
                stage: 0i32,
                waterlogged: false,
                age: 2i32,
            }),
            67u32 => Ok(GeneratedStruct5 {
                age: 2i32,
                waterlogged: true,
                hanging: false,
                stage: 1i32,
            }),
            68u32 => Ok(GeneratedStruct5 {
                age: 2i32,
                stage: 1i32,
                waterlogged: false,
                hanging: false,
            }),
            69u32 => Ok(GeneratedStruct5 {
                waterlogged: true,
                age: 3i32,
                stage: 0i32,
                hanging: true,
            }),
            70u32 => Ok(GeneratedStruct5 {
                waterlogged: false,
                stage: 0i32,
                hanging: true,
                age: 3i32,
            }),
            71u32 => Ok(GeneratedStruct5 {
                waterlogged: true,
                stage: 1i32,
                age: 3i32,
                hanging: true,
            }),
            72u32 => Ok(GeneratedStruct5 {
                stage: 1i32,
                waterlogged: false,
                age: 3i32,
                hanging: true,
            }),
            73u32 => Ok(GeneratedStruct5 {
                stage: 0i32,
                waterlogged: true,
                hanging: false,
                age: 3i32,
            }),
            74u32 => Ok(GeneratedStruct5 {
                hanging: false,
                stage: 0i32,
                waterlogged: false,
                age: 3i32,
            }),
            75u32 => Ok(GeneratedStruct5 {
                stage: 1i32,
                age: 3i32,
                hanging: false,
                waterlogged: true,
            }),
            76u32 => Ok(GeneratedStruct5 {
                age: 3i32,
                stage: 1i32,
                hanging: false,
                waterlogged: false,
            }),
            77u32 => Ok(GeneratedStruct5 {
                stage: 0i32,
                age: 4i32,
                waterlogged: true,
                hanging: true,
            }),
            78u32 => Ok(GeneratedStruct5 {
                age: 4i32,
                waterlogged: false,
                hanging: true,
                stage: 0i32,
            }),
            79u32 => Ok(GeneratedStruct5 {
                waterlogged: true,
                stage: 1i32,
                age: 4i32,
                hanging: true,
            }),
            80u32 => Ok(GeneratedStruct5 {
                stage: 1i32,
                hanging: true,
                waterlogged: false,
                age: 4i32,
            }),
            81u32 => Ok(GeneratedStruct5 {
                stage: 0i32,
                age: 4i32,
                waterlogged: true,
                hanging: false,
            }),
            82u32 => Ok(GeneratedStruct5 {
                stage: 0i32,
                age: 4i32,
                waterlogged: false,
                hanging: false,
            }),
            83u32 => Ok(GeneratedStruct5 {
                hanging: false,
                waterlogged: true,
                age: 4i32,
                stage: 1i32,
            }),
            84u32 => Ok(GeneratedStruct5 {
                waterlogged: false,
                stage: 1i32,
                age: 4i32,
                hanging: false,
            }),
            _ => Err(()),
        }
    }
}
impl TryInto<u32> for GeneratedStruct5 {
    type Error = ();
    fn try_into(self) -> Result<u32, Self::Error> {
        #[allow(unreachable_patterns)]
        match self {
            GeneratedStruct5 {
                hanging: true,
                age: 0i32,
                waterlogged: true,
                stage: 0i32,
            } => Ok(45u32),
            GeneratedStruct5 {
                waterlogged: false,
                age: 0i32,
                stage: 0i32,
                hanging: true,
            } => Ok(46u32),
            GeneratedStruct5 {
                waterlogged: true,
                stage: 1i32,
                age: 0i32,
                hanging: true,
            } => Ok(47u32),
            GeneratedStruct5 {
                hanging: true,
                waterlogged: false,
                age: 0i32,
                stage: 1i32,
            } => Ok(48u32),
            GeneratedStruct5 {
                age: 0i32,
                stage: 0i32,
                waterlogged: true,
                hanging: false,
            } => Ok(49u32),
            GeneratedStruct5 {
                age: 0i32,
                stage: 0i32,
                hanging: false,
                waterlogged: false,
            } => Ok(50u32),
            GeneratedStruct5 {
                age: 0i32,
                waterlogged: true,
                hanging: false,
                stage: 1i32,
            } => Ok(51u32),
            GeneratedStruct5 {
                hanging: false,
                waterlogged: false,
                stage: 1i32,
                age: 0i32,
            } => Ok(52u32),
            GeneratedStruct5 {
                stage: 0i32,
                waterlogged: true,
                hanging: true,
                age: 1i32,
            } => Ok(53u32),
            GeneratedStruct5 {
                waterlogged: false,
                age: 1i32,
                hanging: true,
                stage: 0i32,
            } => Ok(54u32),
            GeneratedStruct5 {
                age: 1i32,
                hanging: true,
                stage: 1i32,
                waterlogged: true,
            } => Ok(55u32),
            GeneratedStruct5 {
                age: 1i32,
                waterlogged: false,
                hanging: true,
                stage: 1i32,
            } => Ok(56u32),
            GeneratedStruct5 {
                age: 1i32,
                hanging: false,
                waterlogged: true,
                stage: 0i32,
            } => Ok(57u32),
            GeneratedStruct5 {
                hanging: false,
                stage: 0i32,
                age: 1i32,
                waterlogged: false,
            } => Ok(58u32),
            GeneratedStruct5 {
                waterlogged: true,
                hanging: false,
                age: 1i32,
                stage: 1i32,
            } => Ok(59u32),
            GeneratedStruct5 {
                age: 1i32,
                stage: 1i32,
                waterlogged: false,
                hanging: false,
            } => Ok(60u32),
            GeneratedStruct5 {
                stage: 0i32,
                waterlogged: true,
                hanging: true,
                age: 2i32,
            } => Ok(61u32),
            GeneratedStruct5 {
                stage: 0i32,
                age: 2i32,
                hanging: true,
                waterlogged: false,
            } => Ok(62u32),
            GeneratedStruct5 {
                age: 2i32,
                stage: 1i32,
                hanging: true,
                waterlogged: true,
            } => Ok(63u32),
            GeneratedStruct5 {
                hanging: true,
                age: 2i32,
                waterlogged: false,
                stage: 1i32,
            } => Ok(64u32),
            GeneratedStruct5 {
                hanging: false,
                stage: 0i32,
                waterlogged: true,
                age: 2i32,
            } => Ok(65u32),
            GeneratedStruct5 {
                hanging: false,
                stage: 0i32,
                waterlogged: false,
                age: 2i32,
            } => Ok(66u32),
            GeneratedStruct5 {
                age: 2i32,
                waterlogged: true,
                hanging: false,
                stage: 1i32,
            } => Ok(67u32),
            GeneratedStruct5 {
                age: 2i32,
                stage: 1i32,
                waterlogged: false,
                hanging: false,
            } => Ok(68u32),
            GeneratedStruct5 {
                waterlogged: true,
                age: 3i32,
                stage: 0i32,
                hanging: true,
            } => Ok(69u32),
            GeneratedStruct5 {
                waterlogged: false,
                stage: 0i32,
                hanging: true,
                age: 3i32,
            } => Ok(70u32),
            GeneratedStruct5 {
                waterlogged: true,
                stage: 1i32,
                age: 3i32,
                hanging: true,
            } => Ok(71u32),
            GeneratedStruct5 {
                stage: 1i32,
                waterlogged: false,
                age: 3i32,
                hanging: true,
            } => Ok(72u32),
            GeneratedStruct5 {
                stage: 0i32,
                waterlogged: true,
                hanging: false,
                age: 3i32,
            } => Ok(73u32),
            GeneratedStruct5 {
                hanging: false,
                stage: 0i32,
                waterlogged: false,
                age: 3i32,
            } => Ok(74u32),
            GeneratedStruct5 {
                stage: 1i32,
                age: 3i32,
                hanging: false,
                waterlogged: true,
            } => Ok(75u32),
            GeneratedStruct5 {
                age: 3i32,
                stage: 1i32,
                hanging: false,
                waterlogged: false,
            } => Ok(76u32),
            GeneratedStruct5 {
                stage: 0i32,
                age: 4i32,
                waterlogged: true,
                hanging: true,
            } => Ok(77u32),
            GeneratedStruct5 {
                age: 4i32,
                waterlogged: false,
                hanging: true,
                stage: 0i32,
            } => Ok(78u32),
            GeneratedStruct5 {
                waterlogged: true,
                stage: 1i32,
                age: 4i32,
                hanging: true,
            } => Ok(79u32),
            GeneratedStruct5 {
                stage: 1i32,
                hanging: true,
                waterlogged: false,
                age: 4i32,
            } => Ok(80u32),
            GeneratedStruct5 {
                stage: 0i32,
                age: 4i32,
                waterlogged: true,
                hanging: false,
            } => Ok(81u32),
            GeneratedStruct5 {
                stage: 0i32,
                age: 4i32,
                waterlogged: false,
                hanging: false,
            } => Ok(82u32),
            GeneratedStruct5 {
                hanging: false,
                waterlogged: true,
                age: 4i32,
                stage: 1i32,
            } => Ok(83u32),
            GeneratedStruct5 {
                waterlogged: false,
                stage: 1i32,
                age: 4i32,
                hanging: false,
            } => Ok(84u32),
            _ => Err(()),
        }
    }
}
