#[allow(unused_imports)]
use ferrumc_block_properties::*;
#[allow(dead_code)]
pub struct GeneratedStruct33 {
    pub east: bool,
    pub north: bool,
    pub south: bool,
    pub up: bool,
    pub west: bool,
}
impl TryFrom<u32> for GeneratedStruct33 {
    type Error = ();
    fn try_from(value: u32) -> Result<Self, Self::Error> {
        match value {
            7080u32 => Ok(GeneratedStruct33 {
                west: true,
                east: true,
                north: true,
                up: true,
                south: true,
            }),
            7081u32 => Ok(GeneratedStruct33 {
                west: false,
                east: true,
                up: true,
                south: true,
                north: true,
            }),
            7082u32 => Ok(GeneratedStruct33 {
                east: true,
                north: true,
                south: true,
                up: false,
                west: true,
            }),
            7083u32 => Ok(GeneratedStruct33 {
                north: true,
                east: true,
                south: true,
                up: false,
                west: false,
            }),
            7084u32 => Ok(GeneratedStruct33 {
                south: false,
                west: true,
                up: true,
                east: true,
                north: true,
            }),
            7085u32 => Ok(GeneratedStruct33 {
                east: true,
                south: false,
                up: true,
                north: true,
                west: false,
            }),
            7086u32 => Ok(GeneratedStruct33 {
                east: true,
                up: false,
                west: true,
                north: true,
                south: false,
            }),
            7087u32 => Ok(GeneratedStruct33 {
                north: true,
                east: true,
                south: false,
                up: false,
                west: false,
            }),
            7088u32 => Ok(GeneratedStruct33 {
                up: true,
                north: false,
                south: true,
                east: true,
                west: true,
            }),
            7089u32 => Ok(GeneratedStruct33 {
                south: true,
                east: true,
                north: false,
                west: false,
                up: true,
            }),
            7090u32 => Ok(GeneratedStruct33 {
                east: true,
                up: false,
                north: false,
                south: true,
                west: true,
            }),
            7091u32 => Ok(GeneratedStruct33 {
                west: false,
                east: true,
                north: false,
                up: false,
                south: true,
            }),
            7092u32 => Ok(GeneratedStruct33 {
                north: false,
                south: false,
                east: true,
                up: true,
                west: true,
            }),
            7093u32 => Ok(GeneratedStruct33 {
                up: true,
                east: true,
                north: false,
                south: false,
                west: false,
            }),
            7094u32 => Ok(GeneratedStruct33 {
                south: false,
                north: false,
                up: false,
                west: true,
                east: true,
            }),
            7095u32 => Ok(GeneratedStruct33 {
                west: false,
                north: false,
                south: false,
                east: true,
                up: false,
            }),
            7096u32 => Ok(GeneratedStruct33 {
                east: false,
                south: true,
                west: true,
                north: true,
                up: true,
            }),
            7097u32 => Ok(GeneratedStruct33 {
                north: true,
                west: false,
                up: true,
                east: false,
                south: true,
            }),
            7098u32 => Ok(GeneratedStruct33 {
                west: true,
                east: false,
                north: true,
                south: true,
                up: false,
            }),
            7099u32 => Ok(GeneratedStruct33 {
                east: false,
                north: true,
                up: false,
                west: false,
                south: true,
            }),
            7100u32 => Ok(GeneratedStruct33 {
                north: true,
                south: false,
                west: true,
                east: false,
                up: true,
            }),
            7101u32 => Ok(GeneratedStruct33 {
                north: true,
                east: false,
                up: true,
                south: false,
                west: false,
            }),
            7102u32 => Ok(GeneratedStruct33 {
                up: false,
                east: false,
                west: true,
                north: true,
                south: false,
            }),
            7103u32 => Ok(GeneratedStruct33 {
                east: false,
                north: true,
                west: false,
                south: false,
                up: false,
            }),
            7104u32 => Ok(GeneratedStruct33 {
                south: true,
                west: true,
                east: false,
                north: false,
                up: true,
            }),
            7105u32 => Ok(GeneratedStruct33 {
                north: false,
                west: false,
                up: true,
                east: false,
                south: true,
            }),
            7106u32 => Ok(GeneratedStruct33 {
                north: false,
                west: true,
                east: false,
                up: false,
                south: true,
            }),
            7107u32 => Ok(GeneratedStruct33 {
                east: false,
                south: true,
                west: false,
                north: false,
                up: false,
            }),
            7108u32 => Ok(GeneratedStruct33 {
                up: true,
                west: true,
                east: false,
                south: false,
                north: false,
            }),
            7109u32 => Ok(GeneratedStruct33 {
                north: false,
                west: false,
                up: true,
                south: false,
                east: false,
            }),
            7110u32 => Ok(GeneratedStruct33 {
                south: false,
                up: false,
                west: true,
                east: false,
                north: false,
            }),
            7111u32 => Ok(GeneratedStruct33 {
                east: false,
                south: false,
                north: false,
                west: false,
                up: false,
            }),
            _ => Err(()),
        }
    }
}
impl TryInto<u32> for GeneratedStruct33 {
    type Error = ();
    fn try_into(self) -> Result<u32, Self::Error> {
        #[allow(unreachable_patterns)]
        match self {
            GeneratedStruct33 {
                west: true,
                east: true,
                north: true,
                up: true,
                south: true,
            } => Ok(7080u32),
            GeneratedStruct33 {
                west: false,
                east: true,
                up: true,
                south: true,
                north: true,
            } => Ok(7081u32),
            GeneratedStruct33 {
                east: true,
                north: true,
                south: true,
                up: false,
                west: true,
            } => Ok(7082u32),
            GeneratedStruct33 {
                north: true,
                east: true,
                south: true,
                up: false,
                west: false,
            } => Ok(7083u32),
            GeneratedStruct33 {
                south: false,
                west: true,
                up: true,
                east: true,
                north: true,
            } => Ok(7084u32),
            GeneratedStruct33 {
                east: true,
                south: false,
                up: true,
                north: true,
                west: false,
            } => Ok(7085u32),
            GeneratedStruct33 {
                east: true,
                up: false,
                west: true,
                north: true,
                south: false,
            } => Ok(7086u32),
            GeneratedStruct33 {
                north: true,
                east: true,
                south: false,
                up: false,
                west: false,
            } => Ok(7087u32),
            GeneratedStruct33 {
                up: true,
                north: false,
                south: true,
                east: true,
                west: true,
            } => Ok(7088u32),
            GeneratedStruct33 {
                south: true,
                east: true,
                north: false,
                west: false,
                up: true,
            } => Ok(7089u32),
            GeneratedStruct33 {
                east: true,
                up: false,
                north: false,
                south: true,
                west: true,
            } => Ok(7090u32),
            GeneratedStruct33 {
                west: false,
                east: true,
                north: false,
                up: false,
                south: true,
            } => Ok(7091u32),
            GeneratedStruct33 {
                north: false,
                south: false,
                east: true,
                up: true,
                west: true,
            } => Ok(7092u32),
            GeneratedStruct33 {
                up: true,
                east: true,
                north: false,
                south: false,
                west: false,
            } => Ok(7093u32),
            GeneratedStruct33 {
                south: false,
                north: false,
                up: false,
                west: true,
                east: true,
            } => Ok(7094u32),
            GeneratedStruct33 {
                west: false,
                north: false,
                south: false,
                east: true,
                up: false,
            } => Ok(7095u32),
            GeneratedStruct33 {
                east: false,
                south: true,
                west: true,
                north: true,
                up: true,
            } => Ok(7096u32),
            GeneratedStruct33 {
                north: true,
                west: false,
                up: true,
                east: false,
                south: true,
            } => Ok(7097u32),
            GeneratedStruct33 {
                west: true,
                east: false,
                north: true,
                south: true,
                up: false,
            } => Ok(7098u32),
            GeneratedStruct33 {
                east: false,
                north: true,
                up: false,
                west: false,
                south: true,
            } => Ok(7099u32),
            GeneratedStruct33 {
                north: true,
                south: false,
                west: true,
                east: false,
                up: true,
            } => Ok(7100u32),
            GeneratedStruct33 {
                north: true,
                east: false,
                up: true,
                south: false,
                west: false,
            } => Ok(7101u32),
            GeneratedStruct33 {
                up: false,
                east: false,
                west: true,
                north: true,
                south: false,
            } => Ok(7102u32),
            GeneratedStruct33 {
                east: false,
                north: true,
                west: false,
                south: false,
                up: false,
            } => Ok(7103u32),
            GeneratedStruct33 {
                south: true,
                west: true,
                east: false,
                north: false,
                up: true,
            } => Ok(7104u32),
            GeneratedStruct33 {
                north: false,
                west: false,
                up: true,
                east: false,
                south: true,
            } => Ok(7105u32),
            GeneratedStruct33 {
                north: false,
                west: true,
                east: false,
                up: false,
                south: true,
            } => Ok(7106u32),
            GeneratedStruct33 {
                east: false,
                south: true,
                west: false,
                north: false,
                up: false,
            } => Ok(7107u32),
            GeneratedStruct33 {
                up: true,
                west: true,
                east: false,
                south: false,
                north: false,
            } => Ok(7108u32),
            GeneratedStruct33 {
                north: false,
                west: false,
                up: true,
                south: false,
                east: false,
            } => Ok(7109u32),
            GeneratedStruct33 {
                south: false,
                up: false,
                west: true,
                east: false,
                north: false,
            } => Ok(7110u32),
            GeneratedStruct33 {
                east: false,
                south: false,
                north: false,
                west: false,
                up: false,
            } => Ok(7111u32),
            _ => Err(()),
        }
    }
}
