#[allow(unused_imports)]
use ferrumc_block_properties::*;
#[allow(dead_code)]
pub struct GeneratedStruct25 {
    pub delay: i32,
    pub facing: Direction,
    pub locked: bool,
    pub powered: bool,
}
impl TryFrom<u32> for GeneratedStruct25 {
    type Error = ();
    fn try_from(value: u32) -> Result<Self, Self::Error> {
        match value {
            6060u32 => Ok(GeneratedStruct25 {
                delay: 1i32,
                locked: true,
                powered: true,
                facing: Direction::North,
            }),
            6061u32 => Ok(GeneratedStruct25 {
                facing: Direction::North,
                powered: false,
                locked: true,
                delay: 1i32,
            }),
            6062u32 => Ok(GeneratedStruct25 {
                delay: 1i32,
                powered: true,
                facing: Direction::North,
                locked: false,
            }),
            6063u32 => Ok(GeneratedStruct25 {
                delay: 1i32,
                powered: false,
                facing: Direction::North,
                locked: false,
            }),
            6064u32 => Ok(GeneratedStruct25 {
                locked: true,
                delay: 1i32,
                powered: true,
                facing: Direction::South,
            }),
            6065u32 => Ok(GeneratedStruct25 {
                locked: true,
                powered: false,
                delay: 1i32,
                facing: Direction::South,
            }),
            6066u32 => Ok(GeneratedStruct25 {
                locked: false,
                facing: Direction::South,
                powered: true,
                delay: 1i32,
            }),
            6067u32 => Ok(GeneratedStruct25 {
                locked: false,
                facing: Direction::South,
                powered: false,
                delay: 1i32,
            }),
            6068u32 => Ok(GeneratedStruct25 {
                powered: true,
                delay: 1i32,
                facing: Direction::West,
                locked: true,
            }),
            6069u32 => Ok(GeneratedStruct25 {
                powered: false,
                facing: Direction::West,
                locked: true,
                delay: 1i32,
            }),
            6070u32 => Ok(GeneratedStruct25 {
                delay: 1i32,
                locked: false,
                facing: Direction::West,
                powered: true,
            }),
            6071u32 => Ok(GeneratedStruct25 {
                facing: Direction::West,
                locked: false,
                delay: 1i32,
                powered: false,
            }),
            6072u32 => Ok(GeneratedStruct25 {
                delay: 1i32,
                powered: true,
                facing: Direction::East,
                locked: true,
            }),
            6073u32 => Ok(GeneratedStruct25 {
                locked: true,
                delay: 1i32,
                powered: false,
                facing: Direction::East,
            }),
            6074u32 => Ok(GeneratedStruct25 {
                facing: Direction::East,
                locked: false,
                delay: 1i32,
                powered: true,
            }),
            6075u32 => Ok(GeneratedStruct25 {
                locked: false,
                facing: Direction::East,
                delay: 1i32,
                powered: false,
            }),
            6076u32 => Ok(GeneratedStruct25 {
                locked: true,
                delay: 2i32,
                facing: Direction::North,
                powered: true,
            }),
            6077u32 => Ok(GeneratedStruct25 {
                facing: Direction::North,
                powered: false,
                delay: 2i32,
                locked: true,
            }),
            6078u32 => Ok(GeneratedStruct25 {
                locked: false,
                delay: 2i32,
                facing: Direction::North,
                powered: true,
            }),
            6079u32 => Ok(GeneratedStruct25 {
                powered: false,
                locked: false,
                delay: 2i32,
                facing: Direction::North,
            }),
            6080u32 => Ok(GeneratedStruct25 {
                delay: 2i32,
                facing: Direction::South,
                powered: true,
                locked: true,
            }),
            6081u32 => Ok(GeneratedStruct25 {
                powered: false,
                locked: true,
                delay: 2i32,
                facing: Direction::South,
            }),
            6082u32 => Ok(GeneratedStruct25 {
                facing: Direction::South,
                powered: true,
                delay: 2i32,
                locked: false,
            }),
            6083u32 => Ok(GeneratedStruct25 {
                powered: false,
                locked: false,
                delay: 2i32,
                facing: Direction::South,
            }),
            6084u32 => Ok(GeneratedStruct25 {
                delay: 2i32,
                powered: true,
                locked: true,
                facing: Direction::West,
            }),
            6085u32 => Ok(GeneratedStruct25 {
                locked: true,
                delay: 2i32,
                facing: Direction::West,
                powered: false,
            }),
            6086u32 => Ok(GeneratedStruct25 {
                facing: Direction::West,
                powered: true,
                locked: false,
                delay: 2i32,
            }),
            6087u32 => Ok(GeneratedStruct25 {
                delay: 2i32,
                powered: false,
                locked: false,
                facing: Direction::West,
            }),
            6088u32 => Ok(GeneratedStruct25 {
                facing: Direction::East,
                powered: true,
                delay: 2i32,
                locked: true,
            }),
            6089u32 => Ok(GeneratedStruct25 {
                facing: Direction::East,
                delay: 2i32,
                powered: false,
                locked: true,
            }),
            6090u32 => Ok(GeneratedStruct25 {
                delay: 2i32,
                locked: false,
                facing: Direction::East,
                powered: true,
            }),
            6091u32 => Ok(GeneratedStruct25 {
                powered: false,
                facing: Direction::East,
                locked: false,
                delay: 2i32,
            }),
            6092u32 => Ok(GeneratedStruct25 {
                facing: Direction::North,
                locked: true,
                powered: true,
                delay: 3i32,
            }),
            6093u32 => Ok(GeneratedStruct25 {
                delay: 3i32,
                powered: false,
                locked: true,
                facing: Direction::North,
            }),
            6094u32 => Ok(GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::North,
                locked: false,
                powered: true,
            }),
            6095u32 => Ok(GeneratedStruct25 {
                delay: 3i32,
                powered: false,
                locked: false,
                facing: Direction::North,
            }),
            6096u32 => Ok(GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::South,
                powered: true,
                locked: true,
            }),
            6097u32 => Ok(GeneratedStruct25 {
                powered: false,
                locked: true,
                facing: Direction::South,
                delay: 3i32,
            }),
            6098u32 => Ok(GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::South,
                powered: true,
                locked: false,
            }),
            6099u32 => Ok(GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::South,
                locked: false,
                powered: false,
            }),
            6100u32 => Ok(GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::West,
                locked: true,
                powered: true,
            }),
            6101u32 => Ok(GeneratedStruct25 {
                facing: Direction::West,
                powered: false,
                locked: true,
                delay: 3i32,
            }),
            6102u32 => Ok(GeneratedStruct25 {
                facing: Direction::West,
                powered: true,
                delay: 3i32,
                locked: false,
            }),
            6103u32 => Ok(GeneratedStruct25 {
                powered: false,
                locked: false,
                delay: 3i32,
                facing: Direction::West,
            }),
            6104u32 => Ok(GeneratedStruct25 {
                locked: true,
                powered: true,
                delay: 3i32,
                facing: Direction::East,
            }),
            6105u32 => Ok(GeneratedStruct25 {
                powered: false,
                locked: true,
                delay: 3i32,
                facing: Direction::East,
            }),
            6106u32 => Ok(GeneratedStruct25 {
                facing: Direction::East,
                locked: false,
                delay: 3i32,
                powered: true,
            }),
            6107u32 => Ok(GeneratedStruct25 {
                facing: Direction::East,
                powered: false,
                delay: 3i32,
                locked: false,
            }),
            6108u32 => Ok(GeneratedStruct25 {
                facing: Direction::North,
                locked: true,
                powered: true,
                delay: 4i32,
            }),
            6109u32 => Ok(GeneratedStruct25 {
                locked: true,
                delay: 4i32,
                facing: Direction::North,
                powered: false,
            }),
            6110u32 => Ok(GeneratedStruct25 {
                powered: true,
                facing: Direction::North,
                locked: false,
                delay: 4i32,
            }),
            6111u32 => Ok(GeneratedStruct25 {
                powered: false,
                locked: false,
                facing: Direction::North,
                delay: 4i32,
            }),
            6112u32 => Ok(GeneratedStruct25 {
                powered: true,
                facing: Direction::South,
                delay: 4i32,
                locked: true,
            }),
            6113u32 => Ok(GeneratedStruct25 {
                facing: Direction::South,
                locked: true,
                delay: 4i32,
                powered: false,
            }),
            6114u32 => Ok(GeneratedStruct25 {
                delay: 4i32,
                locked: false,
                powered: true,
                facing: Direction::South,
            }),
            6115u32 => Ok(GeneratedStruct25 {
                locked: false,
                delay: 4i32,
                facing: Direction::South,
                powered: false,
            }),
            6116u32 => Ok(GeneratedStruct25 {
                locked: true,
                facing: Direction::West,
                delay: 4i32,
                powered: true,
            }),
            6117u32 => Ok(GeneratedStruct25 {
                locked: true,
                facing: Direction::West,
                delay: 4i32,
                powered: false,
            }),
            6118u32 => Ok(GeneratedStruct25 {
                delay: 4i32,
                facing: Direction::West,
                powered: true,
                locked: false,
            }),
            6119u32 => Ok(GeneratedStruct25 {
                delay: 4i32,
                facing: Direction::West,
                locked: false,
                powered: false,
            }),
            6120u32 => Ok(GeneratedStruct25 {
                delay: 4i32,
                facing: Direction::East,
                locked: true,
                powered: true,
            }),
            6121u32 => Ok(GeneratedStruct25 {
                delay: 4i32,
                locked: true,
                powered: false,
                facing: Direction::East,
            }),
            6122u32 => Ok(GeneratedStruct25 {
                delay: 4i32,
                powered: true,
                locked: false,
                facing: Direction::East,
            }),
            6123u32 => Ok(GeneratedStruct25 {
                facing: Direction::East,
                delay: 4i32,
                locked: false,
                powered: false,
            }),
            _ => Err(()),
        }
    }
}
impl TryInto<u32> for GeneratedStruct25 {
    type Error = ();
    fn try_into(self) -> Result<u32, Self::Error> {
        #[allow(unreachable_patterns)]
        match self {
            GeneratedStruct25 {
                delay: 1i32,
                locked: true,
                powered: true,
                facing: Direction::North,
            } => Ok(6060u32),
            GeneratedStruct25 {
                facing: Direction::North,
                powered: false,
                locked: true,
                delay: 1i32,
            } => Ok(6061u32),
            GeneratedStruct25 {
                delay: 1i32,
                powered: true,
                facing: Direction::North,
                locked: false,
            } => Ok(6062u32),
            GeneratedStruct25 {
                delay: 1i32,
                powered: false,
                facing: Direction::North,
                locked: false,
            } => Ok(6063u32),
            GeneratedStruct25 {
                locked: true,
                delay: 1i32,
                powered: true,
                facing: Direction::South,
            } => Ok(6064u32),
            GeneratedStruct25 {
                locked: true,
                powered: false,
                delay: 1i32,
                facing: Direction::South,
            } => Ok(6065u32),
            GeneratedStruct25 {
                locked: false,
                facing: Direction::South,
                powered: true,
                delay: 1i32,
            } => Ok(6066u32),
            GeneratedStruct25 {
                locked: false,
                facing: Direction::South,
                powered: false,
                delay: 1i32,
            } => Ok(6067u32),
            GeneratedStruct25 {
                powered: true,
                delay: 1i32,
                facing: Direction::West,
                locked: true,
            } => Ok(6068u32),
            GeneratedStruct25 {
                powered: false,
                facing: Direction::West,
                locked: true,
                delay: 1i32,
            } => Ok(6069u32),
            GeneratedStruct25 {
                delay: 1i32,
                locked: false,
                facing: Direction::West,
                powered: true,
            } => Ok(6070u32),
            GeneratedStruct25 {
                facing: Direction::West,
                locked: false,
                delay: 1i32,
                powered: false,
            } => Ok(6071u32),
            GeneratedStruct25 {
                delay: 1i32,
                powered: true,
                facing: Direction::East,
                locked: true,
            } => Ok(6072u32),
            GeneratedStruct25 {
                locked: true,
                delay: 1i32,
                powered: false,
                facing: Direction::East,
            } => Ok(6073u32),
            GeneratedStruct25 {
                facing: Direction::East,
                locked: false,
                delay: 1i32,
                powered: true,
            } => Ok(6074u32),
            GeneratedStruct25 {
                locked: false,
                facing: Direction::East,
                delay: 1i32,
                powered: false,
            } => Ok(6075u32),
            GeneratedStruct25 {
                locked: true,
                delay: 2i32,
                facing: Direction::North,
                powered: true,
            } => Ok(6076u32),
            GeneratedStruct25 {
                facing: Direction::North,
                powered: false,
                delay: 2i32,
                locked: true,
            } => Ok(6077u32),
            GeneratedStruct25 {
                locked: false,
                delay: 2i32,
                facing: Direction::North,
                powered: true,
            } => Ok(6078u32),
            GeneratedStruct25 {
                powered: false,
                locked: false,
                delay: 2i32,
                facing: Direction::North,
            } => Ok(6079u32),
            GeneratedStruct25 {
                delay: 2i32,
                facing: Direction::South,
                powered: true,
                locked: true,
            } => Ok(6080u32),
            GeneratedStruct25 {
                powered: false,
                locked: true,
                delay: 2i32,
                facing: Direction::South,
            } => Ok(6081u32),
            GeneratedStruct25 {
                facing: Direction::South,
                powered: true,
                delay: 2i32,
                locked: false,
            } => Ok(6082u32),
            GeneratedStruct25 {
                powered: false,
                locked: false,
                delay: 2i32,
                facing: Direction::South,
            } => Ok(6083u32),
            GeneratedStruct25 {
                delay: 2i32,
                powered: true,
                locked: true,
                facing: Direction::West,
            } => Ok(6084u32),
            GeneratedStruct25 {
                locked: true,
                delay: 2i32,
                facing: Direction::West,
                powered: false,
            } => Ok(6085u32),
            GeneratedStruct25 {
                facing: Direction::West,
                powered: true,
                locked: false,
                delay: 2i32,
            } => Ok(6086u32),
            GeneratedStruct25 {
                delay: 2i32,
                powered: false,
                locked: false,
                facing: Direction::West,
            } => Ok(6087u32),
            GeneratedStruct25 {
                facing: Direction::East,
                powered: true,
                delay: 2i32,
                locked: true,
            } => Ok(6088u32),
            GeneratedStruct25 {
                facing: Direction::East,
                delay: 2i32,
                powered: false,
                locked: true,
            } => Ok(6089u32),
            GeneratedStruct25 {
                delay: 2i32,
                locked: false,
                facing: Direction::East,
                powered: true,
            } => Ok(6090u32),
            GeneratedStruct25 {
                powered: false,
                facing: Direction::East,
                locked: false,
                delay: 2i32,
            } => Ok(6091u32),
            GeneratedStruct25 {
                facing: Direction::North,
                locked: true,
                powered: true,
                delay: 3i32,
            } => Ok(6092u32),
            GeneratedStruct25 {
                delay: 3i32,
                powered: false,
                locked: true,
                facing: Direction::North,
            } => Ok(6093u32),
            GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::North,
                locked: false,
                powered: true,
            } => Ok(6094u32),
            GeneratedStruct25 {
                delay: 3i32,
                powered: false,
                locked: false,
                facing: Direction::North,
            } => Ok(6095u32),
            GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::South,
                powered: true,
                locked: true,
            } => Ok(6096u32),
            GeneratedStruct25 {
                powered: false,
                locked: true,
                facing: Direction::South,
                delay: 3i32,
            } => Ok(6097u32),
            GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::South,
                powered: true,
                locked: false,
            } => Ok(6098u32),
            GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::South,
                locked: false,
                powered: false,
            } => Ok(6099u32),
            GeneratedStruct25 {
                delay: 3i32,
                facing: Direction::West,
                locked: true,
                powered: true,
            } => Ok(6100u32),
            GeneratedStruct25 {
                facing: Direction::West,
                powered: false,
                locked: true,
                delay: 3i32,
            } => Ok(6101u32),
            GeneratedStruct25 {
                facing: Direction::West,
                powered: true,
                delay: 3i32,
                locked: false,
            } => Ok(6102u32),
            GeneratedStruct25 {
                powered: false,
                locked: false,
                delay: 3i32,
                facing: Direction::West,
            } => Ok(6103u32),
            GeneratedStruct25 {
                locked: true,
                powered: true,
                delay: 3i32,
                facing: Direction::East,
            } => Ok(6104u32),
            GeneratedStruct25 {
                powered: false,
                locked: true,
                delay: 3i32,
                facing: Direction::East,
            } => Ok(6105u32),
            GeneratedStruct25 {
                facing: Direction::East,
                locked: false,
                delay: 3i32,
                powered: true,
            } => Ok(6106u32),
            GeneratedStruct25 {
                facing: Direction::East,
                powered: false,
                delay: 3i32,
                locked: false,
            } => Ok(6107u32),
            GeneratedStruct25 {
                facing: Direction::North,
                locked: true,
                powered: true,
                delay: 4i32,
            } => Ok(6108u32),
            GeneratedStruct25 {
                locked: true,
                delay: 4i32,
                facing: Direction::North,
                powered: false,
            } => Ok(6109u32),
            GeneratedStruct25 {
                powered: true,
                facing: Direction::North,
                locked: false,
                delay: 4i32,
            } => Ok(6110u32),
            GeneratedStruct25 {
                powered: false,
                locked: false,
                facing: Direction::North,
                delay: 4i32,
            } => Ok(6111u32),
            GeneratedStruct25 {
                powered: true,
                facing: Direction::South,
                delay: 4i32,
                locked: true,
            } => Ok(6112u32),
            GeneratedStruct25 {
                facing: Direction::South,
                locked: true,
                delay: 4i32,
                powered: false,
            } => Ok(6113u32),
            GeneratedStruct25 {
                delay: 4i32,
                locked: false,
                powered: true,
                facing: Direction::South,
            } => Ok(6114u32),
            GeneratedStruct25 {
                locked: false,
                delay: 4i32,
                facing: Direction::South,
                powered: false,
            } => Ok(6115u32),
            GeneratedStruct25 {
                locked: true,
                facing: Direction::West,
                delay: 4i32,
                powered: true,
            } => Ok(6116u32),
            GeneratedStruct25 {
                locked: true,
                facing: Direction::West,
                delay: 4i32,
                powered: false,
            } => Ok(6117u32),
            GeneratedStruct25 {
                delay: 4i32,
                facing: Direction::West,
                powered: true,
                locked: false,
            } => Ok(6118u32),
            GeneratedStruct25 {
                delay: 4i32,
                facing: Direction::West,
                locked: false,
                powered: false,
            } => Ok(6119u32),
            GeneratedStruct25 {
                delay: 4i32,
                facing: Direction::East,
                locked: true,
                powered: true,
            } => Ok(6120u32),
            GeneratedStruct25 {
                delay: 4i32,
                locked: true,
                powered: false,
                facing: Direction::East,
            } => Ok(6121u32),
            GeneratedStruct25 {
                delay: 4i32,
                powered: true,
                locked: false,
                facing: Direction::East,
            } => Ok(6122u32),
            GeneratedStruct25 {
                facing: Direction::East,
                delay: 4i32,
                locked: false,
                powered: false,
            } => Ok(6123u32),
            _ => Err(()),
        }
    }
}
