#[allow(unused_imports)]
use ferrumc_block_properties::*;
#[allow(dead_code)]
pub enum GeneratedStruct64Type {
    Chest,
    TrappedChest,
}
#[allow(dead_code)]
pub struct GeneratedStruct64 {
    pub block_type: GeneratedStruct64Type,
    pub facing: Direction,
    pub ty: ChestType,
    pub waterlogged: bool,
}
impl TryFrom<u32> for GeneratedStruct64 {
    type Error = ();
    fn try_from(value: u32) -> Result<Self, Self::Error> {
        match value {
            3018u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::North,
                ty: ChestType::Single,
                waterlogged: true,
            }),
            3019u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::North,
                ty: ChestType::Single,
                waterlogged: false,
            }),
            3020u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::North,
                ty: ChestType::Left,
                waterlogged: true,
            }),
            3021u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::North,
                ty: ChestType::Left,
                waterlogged: false,
            }),
            3022u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::North,
                ty: ChestType::Right,
                waterlogged: true,
            }),
            3023u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::North,
                ty: ChestType::Right,
                waterlogged: false,
            }),
            3024u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::South,
                ty: ChestType::Single,
                waterlogged: true,
            }),
            3025u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::South,
                ty: ChestType::Single,
                waterlogged: false,
            }),
            3026u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::South,
                ty: ChestType::Left,
                waterlogged: true,
            }),
            3027u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::South,
                ty: ChestType::Left,
                waterlogged: false,
            }),
            3028u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::South,
                ty: ChestType::Right,
                waterlogged: true,
            }),
            3029u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::South,
                ty: ChestType::Right,
                waterlogged: false,
            }),
            3030u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::West,
                ty: ChestType::Single,
                waterlogged: true,
            }),
            3031u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::West,
                ty: ChestType::Single,
                waterlogged: false,
            }),
            3032u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::West,
                ty: ChestType::Left,
                waterlogged: true,
            }),
            3033u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::West,
                ty: ChestType::Left,
                waterlogged: false,
            }),
            3034u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::West,
                ty: ChestType::Right,
                waterlogged: true,
            }),
            3035u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::West,
                ty: ChestType::Right,
                waterlogged: false,
            }),
            3036u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::East,
                ty: ChestType::Single,
                waterlogged: true,
            }),
            3037u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::East,
                ty: ChestType::Single,
                waterlogged: false,
            }),
            3038u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::East,
                ty: ChestType::Left,
                waterlogged: true,
            }),
            3039u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::East,
                ty: ChestType::Left,
                waterlogged: false,
            }),
            3040u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::East,
                ty: ChestType::Right,
                waterlogged: true,
            }),
            3041u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::East,
                ty: ChestType::Right,
                waterlogged: false,
            }),
            9928u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::North,
                ty: ChestType::Single,
                waterlogged: true,
            }),
            9929u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::North,
                ty: ChestType::Single,
                waterlogged: false,
            }),
            9930u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::North,
                ty: ChestType::Left,
                waterlogged: true,
            }),
            9931u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::North,
                ty: ChestType::Left,
                waterlogged: false,
            }),
            9932u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::North,
                ty: ChestType::Right,
                waterlogged: true,
            }),
            9933u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::North,
                ty: ChestType::Right,
                waterlogged: false,
            }),
            9934u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::South,
                ty: ChestType::Single,
                waterlogged: true,
            }),
            9935u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::South,
                ty: ChestType::Single,
                waterlogged: false,
            }),
            9936u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::South,
                ty: ChestType::Left,
                waterlogged: true,
            }),
            9937u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::South,
                ty: ChestType::Left,
                waterlogged: false,
            }),
            9938u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::South,
                ty: ChestType::Right,
                waterlogged: true,
            }),
            9939u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::South,
                ty: ChestType::Right,
                waterlogged: false,
            }),
            9940u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::West,
                ty: ChestType::Single,
                waterlogged: true,
            }),
            9941u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::West,
                ty: ChestType::Single,
                waterlogged: false,
            }),
            9942u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::West,
                ty: ChestType::Left,
                waterlogged: true,
            }),
            9943u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::West,
                ty: ChestType::Left,
                waterlogged: false,
            }),
            9944u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::West,
                ty: ChestType::Right,
                waterlogged: true,
            }),
            9945u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::West,
                ty: ChestType::Right,
                waterlogged: false,
            }),
            9946u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::East,
                ty: ChestType::Single,
                waterlogged: true,
            }),
            9947u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::East,
                ty: ChestType::Single,
                waterlogged: false,
            }),
            9948u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::East,
                ty: ChestType::Left,
                waterlogged: true,
            }),
            9949u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::East,
                ty: ChestType::Left,
                waterlogged: false,
            }),
            9950u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::East,
                ty: ChestType::Right,
                waterlogged: true,
            }),
            9951u32 => Ok(GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::East,
                ty: ChestType::Right,
                waterlogged: false,
            }),
            _ => Err(()),
        }
    }
}
impl TryInto<u32> for GeneratedStruct64 {
    type Error = ();
    fn try_into(self) -> Result<u32, Self::Error> {
        #[allow(unreachable_patterns)]
        match self {
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::North,
                ty: ChestType::Single,
                waterlogged: true,
            } => Ok(3018u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::North,
                ty: ChestType::Single,
                waterlogged: false,
            } => Ok(3019u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::North,
                ty: ChestType::Left,
                waterlogged: true,
            } => Ok(3020u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::North,
                ty: ChestType::Left,
                waterlogged: false,
            } => Ok(3021u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::North,
                ty: ChestType::Right,
                waterlogged: true,
            } => Ok(3022u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::North,
                ty: ChestType::Right,
                waterlogged: false,
            } => Ok(3023u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::South,
                ty: ChestType::Single,
                waterlogged: true,
            } => Ok(3024u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::South,
                ty: ChestType::Single,
                waterlogged: false,
            } => Ok(3025u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::South,
                ty: ChestType::Left,
                waterlogged: true,
            } => Ok(3026u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::South,
                ty: ChestType::Left,
                waterlogged: false,
            } => Ok(3027u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::South,
                ty: ChestType::Right,
                waterlogged: true,
            } => Ok(3028u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::South,
                ty: ChestType::Right,
                waterlogged: false,
            } => Ok(3029u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::West,
                ty: ChestType::Single,
                waterlogged: true,
            } => Ok(3030u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::West,
                ty: ChestType::Single,
                waterlogged: false,
            } => Ok(3031u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::West,
                ty: ChestType::Left,
                waterlogged: true,
            } => Ok(3032u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::West,
                ty: ChestType::Left,
                waterlogged: false,
            } => Ok(3033u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::West,
                ty: ChestType::Right,
                waterlogged: true,
            } => Ok(3034u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::West,
                ty: ChestType::Right,
                waterlogged: false,
            } => Ok(3035u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::East,
                ty: ChestType::Single,
                waterlogged: true,
            } => Ok(3036u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::East,
                ty: ChestType::Single,
                waterlogged: false,
            } => Ok(3037u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::East,
                ty: ChestType::Left,
                waterlogged: true,
            } => Ok(3038u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::East,
                ty: ChestType::Left,
                waterlogged: false,
            } => Ok(3039u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::East,
                ty: ChestType::Right,
                waterlogged: true,
            } => Ok(3040u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::Chest,
                facing: Direction::East,
                ty: ChestType::Right,
                waterlogged: false,
            } => Ok(3041u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::North,
                ty: ChestType::Single,
                waterlogged: true,
            } => Ok(9928u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::North,
                ty: ChestType::Single,
                waterlogged: false,
            } => Ok(9929u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::North,
                ty: ChestType::Left,
                waterlogged: true,
            } => Ok(9930u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::North,
                ty: ChestType::Left,
                waterlogged: false,
            } => Ok(9931u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::North,
                ty: ChestType::Right,
                waterlogged: true,
            } => Ok(9932u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::North,
                ty: ChestType::Right,
                waterlogged: false,
            } => Ok(9933u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::South,
                ty: ChestType::Single,
                waterlogged: true,
            } => Ok(9934u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::South,
                ty: ChestType::Single,
                waterlogged: false,
            } => Ok(9935u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::South,
                ty: ChestType::Left,
                waterlogged: true,
            } => Ok(9936u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::South,
                ty: ChestType::Left,
                waterlogged: false,
            } => Ok(9937u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::South,
                ty: ChestType::Right,
                waterlogged: true,
            } => Ok(9938u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::South,
                ty: ChestType::Right,
                waterlogged: false,
            } => Ok(9939u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::West,
                ty: ChestType::Single,
                waterlogged: true,
            } => Ok(9940u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::West,
                ty: ChestType::Single,
                waterlogged: false,
            } => Ok(9941u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::West,
                ty: ChestType::Left,
                waterlogged: true,
            } => Ok(9942u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::West,
                ty: ChestType::Left,
                waterlogged: false,
            } => Ok(9943u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::West,
                ty: ChestType::Right,
                waterlogged: true,
            } => Ok(9944u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::West,
                ty: ChestType::Right,
                waterlogged: false,
            } => Ok(9945u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::East,
                ty: ChestType::Single,
                waterlogged: true,
            } => Ok(9946u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::East,
                ty: ChestType::Single,
                waterlogged: false,
            } => Ok(9947u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::East,
                ty: ChestType::Left,
                waterlogged: true,
            } => Ok(9948u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::East,
                ty: ChestType::Left,
                waterlogged: false,
            } => Ok(9949u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::East,
                ty: ChestType::Right,
                waterlogged: true,
            } => Ok(9950u32),
            GeneratedStruct64 {
                block_type: GeneratedStruct64Type::TrappedChest,
                facing: Direction::East,
                ty: ChestType::Right,
                waterlogged: false,
            } => Ok(9951u32),
            _ => Err(()),
        }
    }
}
