#[allow(unused_imports)]
use ferrumc_block_properties::*;
#[allow(dead_code)]
#[derive(Clone, Debug)]
pub struct GeneratedStruct61 {
    pub facing: Direction,
    pub slot_0_occupied: bool,
    pub slot_1_occupied: bool,
    pub slot_2_occupied: bool,
    pub slot_3_occupied: bool,
    pub slot_4_occupied: bool,
    pub slot_5_occupied: bool,
}
impl TryInto<u32> for GeneratedStruct61 {
    type Error = ();
    fn try_into(self) -> Result<u32, Self::Error> {
        #[allow(unreachable_patterns)]
        match self {
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2143u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2144u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2145u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2146u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2147u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2148u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2149u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2150u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2151u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2152u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2153u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2154u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2155u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2156u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2157u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2158u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2159u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2160u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2161u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2162u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2163u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2164u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2165u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2166u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2167u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2168u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2169u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2170u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2171u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2172u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2173u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2174u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2175u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2176u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2177u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2178u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2179u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2180u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2181u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2182u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2183u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2184u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2185u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2186u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2187u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2188u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2189u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2190u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2191u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2192u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2193u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2194u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2195u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2196u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2197u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2198u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2199u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2200u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2201u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2202u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2203u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2204u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2205u32),
            GeneratedStruct61 {
                facing: Direction::North,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2206u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2207u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2208u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2209u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2210u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2211u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2212u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2213u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2214u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2215u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2216u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2217u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2218u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2219u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2220u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2221u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2222u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2223u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2224u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2225u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2226u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2227u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2228u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2229u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2230u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2231u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2232u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2233u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2234u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2235u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2236u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2237u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2238u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2239u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2240u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2241u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2242u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2243u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2244u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2245u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2246u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2247u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2248u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2249u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2250u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2251u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2252u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2253u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2254u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2255u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2256u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2257u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2258u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2259u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2260u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2261u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2262u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2263u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2264u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2265u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2266u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2267u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2268u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2269u32),
            GeneratedStruct61 {
                facing: Direction::South,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2270u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2271u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2272u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2273u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2274u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2275u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2276u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2277u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2278u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2279u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2280u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2281u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2282u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2283u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2284u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2285u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2286u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2287u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2288u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2289u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2290u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2291u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2292u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2293u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2294u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2295u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2296u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2297u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2298u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2299u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2300u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2301u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2302u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2303u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2304u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2305u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2306u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2307u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2308u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2309u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2310u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2311u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2312u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2313u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2314u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2315u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2316u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2317u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2318u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2319u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2320u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2321u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2322u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2323u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2324u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2325u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2326u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2327u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2328u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2329u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2330u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2331u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2332u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2333u32),
            GeneratedStruct61 {
                facing: Direction::West,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2334u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2335u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2336u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2337u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2338u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2339u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2340u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2341u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2342u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2343u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2344u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2345u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2346u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2347u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2348u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2349u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2350u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2351u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2352u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2353u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2354u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2355u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2356u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2357u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2358u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2359u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2360u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2361u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2362u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2363u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2364u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2365u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: true,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2366u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2367u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2368u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2369u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2370u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2371u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2372u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2373u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2374u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2375u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2376u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2377u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2378u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2379u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2380u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2381u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: true,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2382u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2383u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2384u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2385u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2386u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2387u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2388u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2389u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: true,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2390u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2391u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2392u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2393u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: true,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2394u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: true,
            } => Ok(2395u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: true,
                slot_5_occupied: false,
            } => Ok(2396u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: true,
            } => Ok(2397u32),
            GeneratedStruct61 {
                facing: Direction::East,
                slot_0_occupied: false,
                slot_1_occupied: false,
                slot_2_occupied: false,
                slot_3_occupied: false,
                slot_4_occupied: false,
                slot_5_occupied: false,
            } => Ok(2398u32),
            _ => Err(()),
        }
    }
}
