#[allow(unused_imports)]
use ferrumc_block_properties::*;
#[allow(dead_code)]
#[derive(Clone, Debug)]
pub enum LargeMushroomBlockType {
    BrownMushroomBlock,
    ChorusPlant,
    MushroomStem,
    RedMushroomBlock,
}
#[allow(dead_code)]
#[derive(Clone, Debug)]
pub struct LargeMushroomBlock {
    pub block_type: LargeMushroomBlockType,
    pub down: bool,
    pub east: bool,
    pub north: bool,
    pub south: bool,
    pub up: bool,
    pub west: bool,
}
impl TryInto<u32> for LargeMushroomBlock {
    type Error = ();
    fn try_into(self) -> Result<u32, Self::Error> {
        #[allow(unreachable_patterns)]
        match self {
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: true,
                north: true,
                south: true,
                up: true,
                west: true,
            } => Ok(6792u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: true,
                north: true,
                south: true,
                up: true,
                west: false,
            } => Ok(6793u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: true,
                north: true,
                south: true,
                up: false,
                west: true,
            } => Ok(6794u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: true,
                north: true,
                south: true,
                up: false,
                west: false,
            } => Ok(6795u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: true,
                north: true,
                south: false,
                up: true,
                west: true,
            } => Ok(6796u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: true,
                north: true,
                south: false,
                up: true,
                west: false,
            } => Ok(6797u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: true,
                north: true,
                south: false,
                up: false,
                west: true,
            } => Ok(6798u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: true,
                north: true,
                south: false,
                up: false,
                west: false,
            } => Ok(6799u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: true,
                north: false,
                south: true,
                up: true,
                west: true,
            } => Ok(6800u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: true,
                north: false,
                south: true,
                up: true,
                west: false,
            } => Ok(6801u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: true,
                north: false,
                south: true,
                up: false,
                west: true,
            } => Ok(6802u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: true,
                north: false,
                south: true,
                up: false,
                west: false,
            } => Ok(6803u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: true,
                north: false,
                south: false,
                up: true,
                west: true,
            } => Ok(6804u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: true,
                north: false,
                south: false,
                up: true,
                west: false,
            } => Ok(6805u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: true,
                north: false,
                south: false,
                up: false,
                west: true,
            } => Ok(6806u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: true,
                north: false,
                south: false,
                up: false,
                west: false,
            } => Ok(6807u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: false,
                north: true,
                south: true,
                up: true,
                west: true,
            } => Ok(6808u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: false,
                north: true,
                south: true,
                up: true,
                west: false,
            } => Ok(6809u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: false,
                north: true,
                south: true,
                up: false,
                west: true,
            } => Ok(6810u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: false,
                north: true,
                south: true,
                up: false,
                west: false,
            } => Ok(6811u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: false,
                north: true,
                south: false,
                up: true,
                west: true,
            } => Ok(6812u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: false,
                north: true,
                south: false,
                up: true,
                west: false,
            } => Ok(6813u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: false,
                north: true,
                south: false,
                up: false,
                west: true,
            } => Ok(6814u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: false,
                north: true,
                south: false,
                up: false,
                west: false,
            } => Ok(6815u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: false,
                north: false,
                south: true,
                up: true,
                west: true,
            } => Ok(6816u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: false,
                north: false,
                south: true,
                up: true,
                west: false,
            } => Ok(6817u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: false,
                north: false,
                south: true,
                up: false,
                west: true,
            } => Ok(6818u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: false,
                north: false,
                south: true,
                up: false,
                west: false,
            } => Ok(6819u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: false,
                north: false,
                south: false,
                up: true,
                west: true,
            } => Ok(6820u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: false,
                north: false,
                south: false,
                up: true,
                west: false,
            } => Ok(6821u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: false,
                north: false,
                south: false,
                up: false,
                west: true,
            } => Ok(6822u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: true,
                east: false,
                north: false,
                south: false,
                up: false,
                west: false,
            } => Ok(6823u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: true,
                north: true,
                south: true,
                up: true,
                west: true,
            } => Ok(6824u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: true,
                north: true,
                south: true,
                up: true,
                west: false,
            } => Ok(6825u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: true,
                north: true,
                south: true,
                up: false,
                west: true,
            } => Ok(6826u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: true,
                north: true,
                south: true,
                up: false,
                west: false,
            } => Ok(6827u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: true,
                north: true,
                south: false,
                up: true,
                west: true,
            } => Ok(6828u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: true,
                north: true,
                south: false,
                up: true,
                west: false,
            } => Ok(6829u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: true,
                north: true,
                south: false,
                up: false,
                west: true,
            } => Ok(6830u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: true,
                north: true,
                south: false,
                up: false,
                west: false,
            } => Ok(6831u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: true,
                north: false,
                south: true,
                up: true,
                west: true,
            } => Ok(6832u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: true,
                north: false,
                south: true,
                up: true,
                west: false,
            } => Ok(6833u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: true,
                north: false,
                south: true,
                up: false,
                west: true,
            } => Ok(6834u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: true,
                north: false,
                south: true,
                up: false,
                west: false,
            } => Ok(6835u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: true,
                north: false,
                south: false,
                up: true,
                west: true,
            } => Ok(6836u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: true,
                north: false,
                south: false,
                up: true,
                west: false,
            } => Ok(6837u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: true,
                north: false,
                south: false,
                up: false,
                west: true,
            } => Ok(6838u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: true,
                north: false,
                south: false,
                up: false,
                west: false,
            } => Ok(6839u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: false,
                north: true,
                south: true,
                up: true,
                west: true,
            } => Ok(6840u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: false,
                north: true,
                south: true,
                up: true,
                west: false,
            } => Ok(6841u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: false,
                north: true,
                south: true,
                up: false,
                west: true,
            } => Ok(6842u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: false,
                north: true,
                south: true,
                up: false,
                west: false,
            } => Ok(6843u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: false,
                north: true,
                south: false,
                up: true,
                west: true,
            } => Ok(6844u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: false,
                north: true,
                south: false,
                up: true,
                west: false,
            } => Ok(6845u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: false,
                north: true,
                south: false,
                up: false,
                west: true,
            } => Ok(6846u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: false,
                north: true,
                south: false,
                up: false,
                west: false,
            } => Ok(6847u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: false,
                north: false,
                south: true,
                up: true,
                west: true,
            } => Ok(6848u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: false,
                north: false,
                south: true,
                up: true,
                west: false,
            } => Ok(6849u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: false,
                north: false,
                south: true,
                up: false,
                west: true,
            } => Ok(6850u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: false,
                north: false,
                south: true,
                up: false,
                west: false,
            } => Ok(6851u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: false,
                north: false,
                south: false,
                up: true,
                west: true,
            } => Ok(6852u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: false,
                north: false,
                south: false,
                up: true,
                west: false,
            } => Ok(6853u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: false,
                north: false,
                south: false,
                up: false,
                west: true,
            } => Ok(6854u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::BrownMushroomBlock,
                down: false,
                east: false,
                north: false,
                south: false,
                up: false,
                west: false,
            } => Ok(6855u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: true,
                north: true,
                south: true,
                up: true,
                west: true,
            } => Ok(13363u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: true,
                north: true,
                south: true,
                up: true,
                west: false,
            } => Ok(13364u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: true,
                north: true,
                south: true,
                up: false,
                west: true,
            } => Ok(13365u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: true,
                north: true,
                south: true,
                up: false,
                west: false,
            } => Ok(13366u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: true,
                north: true,
                south: false,
                up: true,
                west: true,
            } => Ok(13367u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: true,
                north: true,
                south: false,
                up: true,
                west: false,
            } => Ok(13368u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: true,
                north: true,
                south: false,
                up: false,
                west: true,
            } => Ok(13369u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: true,
                north: true,
                south: false,
                up: false,
                west: false,
            } => Ok(13370u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: true,
                north: false,
                south: true,
                up: true,
                west: true,
            } => Ok(13371u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: true,
                north: false,
                south: true,
                up: true,
                west: false,
            } => Ok(13372u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: true,
                north: false,
                south: true,
                up: false,
                west: true,
            } => Ok(13373u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: true,
                north: false,
                south: true,
                up: false,
                west: false,
            } => Ok(13374u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: true,
                north: false,
                south: false,
                up: true,
                west: true,
            } => Ok(13375u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: true,
                north: false,
                south: false,
                up: true,
                west: false,
            } => Ok(13376u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: true,
                north: false,
                south: false,
                up: false,
                west: true,
            } => Ok(13377u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: true,
                north: false,
                south: false,
                up: false,
                west: false,
            } => Ok(13378u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: false,
                north: true,
                south: true,
                up: true,
                west: true,
            } => Ok(13379u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: false,
                north: true,
                south: true,
                up: true,
                west: false,
            } => Ok(13380u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: false,
                north: true,
                south: true,
                up: false,
                west: true,
            } => Ok(13381u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: false,
                north: true,
                south: true,
                up: false,
                west: false,
            } => Ok(13382u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: false,
                north: true,
                south: false,
                up: true,
                west: true,
            } => Ok(13383u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: false,
                north: true,
                south: false,
                up: true,
                west: false,
            } => Ok(13384u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: false,
                north: true,
                south: false,
                up: false,
                west: true,
            } => Ok(13385u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: false,
                north: true,
                south: false,
                up: false,
                west: false,
            } => Ok(13386u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: false,
                north: false,
                south: true,
                up: true,
                west: true,
            } => Ok(13387u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: false,
                north: false,
                south: true,
                up: true,
                west: false,
            } => Ok(13388u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: false,
                north: false,
                south: true,
                up: false,
                west: true,
            } => Ok(13389u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: false,
                north: false,
                south: true,
                up: false,
                west: false,
            } => Ok(13390u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: false,
                north: false,
                south: false,
                up: true,
                west: true,
            } => Ok(13391u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: false,
                north: false,
                south: false,
                up: true,
                west: false,
            } => Ok(13392u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: false,
                north: false,
                south: false,
                up: false,
                west: true,
            } => Ok(13393u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: true,
                east: false,
                north: false,
                south: false,
                up: false,
                west: false,
            } => Ok(13394u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: true,
                north: true,
                south: true,
                up: true,
                west: true,
            } => Ok(13395u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: true,
                north: true,
                south: true,
                up: true,
                west: false,
            } => Ok(13396u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: true,
                north: true,
                south: true,
                up: false,
                west: true,
            } => Ok(13397u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: true,
                north: true,
                south: true,
                up: false,
                west: false,
            } => Ok(13398u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: true,
                north: true,
                south: false,
                up: true,
                west: true,
            } => Ok(13399u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: true,
                north: true,
                south: false,
                up: true,
                west: false,
            } => Ok(13400u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: true,
                north: true,
                south: false,
                up: false,
                west: true,
            } => Ok(13401u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: true,
                north: true,
                south: false,
                up: false,
                west: false,
            } => Ok(13402u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: true,
                north: false,
                south: true,
                up: true,
                west: true,
            } => Ok(13403u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: true,
                north: false,
                south: true,
                up: true,
                west: false,
            } => Ok(13404u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: true,
                north: false,
                south: true,
                up: false,
                west: true,
            } => Ok(13405u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: true,
                north: false,
                south: true,
                up: false,
                west: false,
            } => Ok(13406u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: true,
                north: false,
                south: false,
                up: true,
                west: true,
            } => Ok(13407u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: true,
                north: false,
                south: false,
                up: true,
                west: false,
            } => Ok(13408u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: true,
                north: false,
                south: false,
                up: false,
                west: true,
            } => Ok(13409u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: true,
                north: false,
                south: false,
                up: false,
                west: false,
            } => Ok(13410u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: false,
                north: true,
                south: true,
                up: true,
                west: true,
            } => Ok(13411u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: false,
                north: true,
                south: true,
                up: true,
                west: false,
            } => Ok(13412u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: false,
                north: true,
                south: true,
                up: false,
                west: true,
            } => Ok(13413u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: false,
                north: true,
                south: true,
                up: false,
                west: false,
            } => Ok(13414u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: false,
                north: true,
                south: false,
                up: true,
                west: true,
            } => Ok(13415u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: false,
                north: true,
                south: false,
                up: true,
                west: false,
            } => Ok(13416u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: false,
                north: true,
                south: false,
                up: false,
                west: true,
            } => Ok(13417u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: false,
                north: true,
                south: false,
                up: false,
                west: false,
            } => Ok(13418u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: false,
                north: false,
                south: true,
                up: true,
                west: true,
            } => Ok(13419u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: false,
                north: false,
                south: true,
                up: true,
                west: false,
            } => Ok(13420u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: false,
                north: false,
                south: true,
                up: false,
                west: true,
            } => Ok(13421u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: false,
                north: false,
                south: true,
                up: false,
                west: false,
            } => Ok(13422u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: false,
                north: false,
                south: false,
                up: true,
                west: true,
            } => Ok(13423u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: false,
                north: false,
                south: false,
                up: true,
                west: false,
            } => Ok(13424u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: false,
                north: false,
                south: false,
                up: false,
                west: true,
            } => Ok(13425u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::ChorusPlant,
                down: false,
                east: false,
                north: false,
                south: false,
                up: false,
                west: false,
            } => Ok(13426u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: true,
                north: true,
                south: true,
                up: true,
                west: true,
            } => Ok(6920u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: true,
                north: true,
                south: true,
                up: true,
                west: false,
            } => Ok(6921u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: true,
                north: true,
                south: true,
                up: false,
                west: true,
            } => Ok(6922u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: true,
                north: true,
                south: true,
                up: false,
                west: false,
            } => Ok(6923u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: true,
                north: true,
                south: false,
                up: true,
                west: true,
            } => Ok(6924u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: true,
                north: true,
                south: false,
                up: true,
                west: false,
            } => Ok(6925u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: true,
                north: true,
                south: false,
                up: false,
                west: true,
            } => Ok(6926u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: true,
                north: true,
                south: false,
                up: false,
                west: false,
            } => Ok(6927u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: true,
                north: false,
                south: true,
                up: true,
                west: true,
            } => Ok(6928u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: true,
                north: false,
                south: true,
                up: true,
                west: false,
            } => Ok(6929u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: true,
                north: false,
                south: true,
                up: false,
                west: true,
            } => Ok(6930u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: true,
                north: false,
                south: true,
                up: false,
                west: false,
            } => Ok(6931u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: true,
                north: false,
                south: false,
                up: true,
                west: true,
            } => Ok(6932u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: true,
                north: false,
                south: false,
                up: true,
                west: false,
            } => Ok(6933u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: true,
                north: false,
                south: false,
                up: false,
                west: true,
            } => Ok(6934u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: true,
                north: false,
                south: false,
                up: false,
                west: false,
            } => Ok(6935u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: false,
                north: true,
                south: true,
                up: true,
                west: true,
            } => Ok(6936u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: false,
                north: true,
                south: true,
                up: true,
                west: false,
            } => Ok(6937u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: false,
                north: true,
                south: true,
                up: false,
                west: true,
            } => Ok(6938u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: false,
                north: true,
                south: true,
                up: false,
                west: false,
            } => Ok(6939u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: false,
                north: true,
                south: false,
                up: true,
                west: true,
            } => Ok(6940u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: false,
                north: true,
                south: false,
                up: true,
                west: false,
            } => Ok(6941u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: false,
                north: true,
                south: false,
                up: false,
                west: true,
            } => Ok(6942u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: false,
                north: true,
                south: false,
                up: false,
                west: false,
            } => Ok(6943u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: false,
                north: false,
                south: true,
                up: true,
                west: true,
            } => Ok(6944u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: false,
                north: false,
                south: true,
                up: true,
                west: false,
            } => Ok(6945u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: false,
                north: false,
                south: true,
                up: false,
                west: true,
            } => Ok(6946u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: false,
                north: false,
                south: true,
                up: false,
                west: false,
            } => Ok(6947u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: false,
                north: false,
                south: false,
                up: true,
                west: true,
            } => Ok(6948u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: false,
                north: false,
                south: false,
                up: true,
                west: false,
            } => Ok(6949u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: false,
                north: false,
                south: false,
                up: false,
                west: true,
            } => Ok(6950u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: true,
                east: false,
                north: false,
                south: false,
                up: false,
                west: false,
            } => Ok(6951u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: true,
                north: true,
                south: true,
                up: true,
                west: true,
            } => Ok(6952u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: true,
                north: true,
                south: true,
                up: true,
                west: false,
            } => Ok(6953u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: true,
                north: true,
                south: true,
                up: false,
                west: true,
            } => Ok(6954u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: true,
                north: true,
                south: true,
                up: false,
                west: false,
            } => Ok(6955u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: true,
                north: true,
                south: false,
                up: true,
                west: true,
            } => Ok(6956u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: true,
                north: true,
                south: false,
                up: true,
                west: false,
            } => Ok(6957u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: true,
                north: true,
                south: false,
                up: false,
                west: true,
            } => Ok(6958u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: true,
                north: true,
                south: false,
                up: false,
                west: false,
            } => Ok(6959u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: true,
                north: false,
                south: true,
                up: true,
                west: true,
            } => Ok(6960u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: true,
                north: false,
                south: true,
                up: true,
                west: false,
            } => Ok(6961u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: true,
                north: false,
                south: true,
                up: false,
                west: true,
            } => Ok(6962u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: true,
                north: false,
                south: true,
                up: false,
                west: false,
            } => Ok(6963u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: true,
                north: false,
                south: false,
                up: true,
                west: true,
            } => Ok(6964u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: true,
                north: false,
                south: false,
                up: true,
                west: false,
            } => Ok(6965u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: true,
                north: false,
                south: false,
                up: false,
                west: true,
            } => Ok(6966u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: true,
                north: false,
                south: false,
                up: false,
                west: false,
            } => Ok(6967u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: false,
                north: true,
                south: true,
                up: true,
                west: true,
            } => Ok(6968u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: false,
                north: true,
                south: true,
                up: true,
                west: false,
            } => Ok(6969u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: false,
                north: true,
                south: true,
                up: false,
                west: true,
            } => Ok(6970u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: false,
                north: true,
                south: true,
                up: false,
                west: false,
            } => Ok(6971u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: false,
                north: true,
                south: false,
                up: true,
                west: true,
            } => Ok(6972u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: false,
                north: true,
                south: false,
                up: true,
                west: false,
            } => Ok(6973u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: false,
                north: true,
                south: false,
                up: false,
                west: true,
            } => Ok(6974u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: false,
                north: true,
                south: false,
                up: false,
                west: false,
            } => Ok(6975u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: false,
                north: false,
                south: true,
                up: true,
                west: true,
            } => Ok(6976u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: false,
                north: false,
                south: true,
                up: true,
                west: false,
            } => Ok(6977u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: false,
                north: false,
                south: true,
                up: false,
                west: true,
            } => Ok(6978u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: false,
                north: false,
                south: true,
                up: false,
                west: false,
            } => Ok(6979u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: false,
                north: false,
                south: false,
                up: true,
                west: true,
            } => Ok(6980u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: false,
                north: false,
                south: false,
                up: true,
                west: false,
            } => Ok(6981u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: false,
                north: false,
                south: false,
                up: false,
                west: true,
            } => Ok(6982u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::MushroomStem,
                down: false,
                east: false,
                north: false,
                south: false,
                up: false,
                west: false,
            } => Ok(6983u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: true,
                north: true,
                south: true,
                up: true,
                west: true,
            } => Ok(6856u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: true,
                north: true,
                south: true,
                up: true,
                west: false,
            } => Ok(6857u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: true,
                north: true,
                south: true,
                up: false,
                west: true,
            } => Ok(6858u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: true,
                north: true,
                south: true,
                up: false,
                west: false,
            } => Ok(6859u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: true,
                north: true,
                south: false,
                up: true,
                west: true,
            } => Ok(6860u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: true,
                north: true,
                south: false,
                up: true,
                west: false,
            } => Ok(6861u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: true,
                north: true,
                south: false,
                up: false,
                west: true,
            } => Ok(6862u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: true,
                north: true,
                south: false,
                up: false,
                west: false,
            } => Ok(6863u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: true,
                north: false,
                south: true,
                up: true,
                west: true,
            } => Ok(6864u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: true,
                north: false,
                south: true,
                up: true,
                west: false,
            } => Ok(6865u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: true,
                north: false,
                south: true,
                up: false,
                west: true,
            } => Ok(6866u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: true,
                north: false,
                south: true,
                up: false,
                west: false,
            } => Ok(6867u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: true,
                north: false,
                south: false,
                up: true,
                west: true,
            } => Ok(6868u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: true,
                north: false,
                south: false,
                up: true,
                west: false,
            } => Ok(6869u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: true,
                north: false,
                south: false,
                up: false,
                west: true,
            } => Ok(6870u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: true,
                north: false,
                south: false,
                up: false,
                west: false,
            } => Ok(6871u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: false,
                north: true,
                south: true,
                up: true,
                west: true,
            } => Ok(6872u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: false,
                north: true,
                south: true,
                up: true,
                west: false,
            } => Ok(6873u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: false,
                north: true,
                south: true,
                up: false,
                west: true,
            } => Ok(6874u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: false,
                north: true,
                south: true,
                up: false,
                west: false,
            } => Ok(6875u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: false,
                north: true,
                south: false,
                up: true,
                west: true,
            } => Ok(6876u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: false,
                north: true,
                south: false,
                up: true,
                west: false,
            } => Ok(6877u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: false,
                north: true,
                south: false,
                up: false,
                west: true,
            } => Ok(6878u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: false,
                north: true,
                south: false,
                up: false,
                west: false,
            } => Ok(6879u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: false,
                north: false,
                south: true,
                up: true,
                west: true,
            } => Ok(6880u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: false,
                north: false,
                south: true,
                up: true,
                west: false,
            } => Ok(6881u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: false,
                north: false,
                south: true,
                up: false,
                west: true,
            } => Ok(6882u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: false,
                north: false,
                south: true,
                up: false,
                west: false,
            } => Ok(6883u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: false,
                north: false,
                south: false,
                up: true,
                west: true,
            } => Ok(6884u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: false,
                north: false,
                south: false,
                up: true,
                west: false,
            } => Ok(6885u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: false,
                north: false,
                south: false,
                up: false,
                west: true,
            } => Ok(6886u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: true,
                east: false,
                north: false,
                south: false,
                up: false,
                west: false,
            } => Ok(6887u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: true,
                north: true,
                south: true,
                up: true,
                west: true,
            } => Ok(6888u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: true,
                north: true,
                south: true,
                up: true,
                west: false,
            } => Ok(6889u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: true,
                north: true,
                south: true,
                up: false,
                west: true,
            } => Ok(6890u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: true,
                north: true,
                south: true,
                up: false,
                west: false,
            } => Ok(6891u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: true,
                north: true,
                south: false,
                up: true,
                west: true,
            } => Ok(6892u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: true,
                north: true,
                south: false,
                up: true,
                west: false,
            } => Ok(6893u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: true,
                north: true,
                south: false,
                up: false,
                west: true,
            } => Ok(6894u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: true,
                north: true,
                south: false,
                up: false,
                west: false,
            } => Ok(6895u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: true,
                north: false,
                south: true,
                up: true,
                west: true,
            } => Ok(6896u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: true,
                north: false,
                south: true,
                up: true,
                west: false,
            } => Ok(6897u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: true,
                north: false,
                south: true,
                up: false,
                west: true,
            } => Ok(6898u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: true,
                north: false,
                south: true,
                up: false,
                west: false,
            } => Ok(6899u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: true,
                north: false,
                south: false,
                up: true,
                west: true,
            } => Ok(6900u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: true,
                north: false,
                south: false,
                up: true,
                west: false,
            } => Ok(6901u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: true,
                north: false,
                south: false,
                up: false,
                west: true,
            } => Ok(6902u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: true,
                north: false,
                south: false,
                up: false,
                west: false,
            } => Ok(6903u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: false,
                north: true,
                south: true,
                up: true,
                west: true,
            } => Ok(6904u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: false,
                north: true,
                south: true,
                up: true,
                west: false,
            } => Ok(6905u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: false,
                north: true,
                south: true,
                up: false,
                west: true,
            } => Ok(6906u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: false,
                north: true,
                south: true,
                up: false,
                west: false,
            } => Ok(6907u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: false,
                north: true,
                south: false,
                up: true,
                west: true,
            } => Ok(6908u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: false,
                north: true,
                south: false,
                up: true,
                west: false,
            } => Ok(6909u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: false,
                north: true,
                south: false,
                up: false,
                west: true,
            } => Ok(6910u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: false,
                north: true,
                south: false,
                up: false,
                west: false,
            } => Ok(6911u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: false,
                north: false,
                south: true,
                up: true,
                west: true,
            } => Ok(6912u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: false,
                north: false,
                south: true,
                up: true,
                west: false,
            } => Ok(6913u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: false,
                north: false,
                south: true,
                up: false,
                west: true,
            } => Ok(6914u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: false,
                north: false,
                south: true,
                up: false,
                west: false,
            } => Ok(6915u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: false,
                north: false,
                south: false,
                up: true,
                west: true,
            } => Ok(6916u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: false,
                north: false,
                south: false,
                up: true,
                west: false,
            } => Ok(6917u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: false,
                north: false,
                south: false,
                up: false,
                west: true,
            } => Ok(6918u32),
            LargeMushroomBlock {
                block_type: LargeMushroomBlockType::RedMushroomBlock,
                down: false,
                east: false,
                north: false,
                south: false,
                up: false,
                west: false,
            } => Ok(6919u32),
            _ => Err(()),
        }
    }
}
