#[allow(unused_imports)]
use ferrumc_block_properties::*;
#[allow(dead_code)]
#[derive(Clone, Debug)]
pub enum LeavesBlockType {
    AcaciaLeaves,
    AzaleaLeaves,
    BirchLeaves,
    CherryLeaves,
    DarkOakLeaves,
    FloweringAzaleaLeaves,
    JungleLeaves,
    MangroveLeaves,
    OakLeaves,
    PaleOakLeaves,
    SpruceLeaves,
}
#[allow(dead_code)]
#[derive(Clone, Debug)]
pub struct LeavesBlock {
    pub block_type: LeavesBlockType,
    pub distance: i32,
    pub persistent: bool,
    pub waterlogged: bool,
}
impl TryInto<u32> for LeavesBlock {
    type Error = ();
    fn try_into(self) -> Result<u32, Self::Error> {
        #[allow(unreachable_patterns)]
        match self {
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 1i32,
                persistent: true,
                waterlogged: true,
            } => Ok(364u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 1i32,
                persistent: true,
                waterlogged: false,
            } => Ok(365u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 1i32,
                persistent: false,
                waterlogged: true,
            } => Ok(366u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 1i32,
                persistent: false,
                waterlogged: false,
            } => Ok(367u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 2i32,
                persistent: true,
                waterlogged: true,
            } => Ok(368u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 2i32,
                persistent: true,
                waterlogged: false,
            } => Ok(369u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 2i32,
                persistent: false,
                waterlogged: true,
            } => Ok(370u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 2i32,
                persistent: false,
                waterlogged: false,
            } => Ok(371u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 3i32,
                persistent: true,
                waterlogged: true,
            } => Ok(372u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 3i32,
                persistent: true,
                waterlogged: false,
            } => Ok(373u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 3i32,
                persistent: false,
                waterlogged: true,
            } => Ok(374u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 3i32,
                persistent: false,
                waterlogged: false,
            } => Ok(375u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 4i32,
                persistent: true,
                waterlogged: true,
            } => Ok(376u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 4i32,
                persistent: true,
                waterlogged: false,
            } => Ok(377u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 4i32,
                persistent: false,
                waterlogged: true,
            } => Ok(378u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 4i32,
                persistent: false,
                waterlogged: false,
            } => Ok(379u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 5i32,
                persistent: true,
                waterlogged: true,
            } => Ok(380u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 5i32,
                persistent: true,
                waterlogged: false,
            } => Ok(381u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 5i32,
                persistent: false,
                waterlogged: true,
            } => Ok(382u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 5i32,
                persistent: false,
                waterlogged: false,
            } => Ok(383u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 6i32,
                persistent: true,
                waterlogged: true,
            } => Ok(384u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 6i32,
                persistent: true,
                waterlogged: false,
            } => Ok(385u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 6i32,
                persistent: false,
                waterlogged: true,
            } => Ok(386u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 6i32,
                persistent: false,
                waterlogged: false,
            } => Ok(387u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 7i32,
                persistent: true,
                waterlogged: true,
            } => Ok(388u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 7i32,
                persistent: true,
                waterlogged: false,
            } => Ok(389u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 7i32,
                persistent: false,
                waterlogged: true,
            } => Ok(390u32),
            LeavesBlock {
                block_type: LeavesBlockType::AcaciaLeaves,
                distance: 7i32,
                persistent: false,
                waterlogged: false,
            } => Ok(391u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 1i32,
                persistent: true,
                waterlogged: true,
            } => Ok(504u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 1i32,
                persistent: true,
                waterlogged: false,
            } => Ok(505u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 1i32,
                persistent: false,
                waterlogged: true,
            } => Ok(506u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 1i32,
                persistent: false,
                waterlogged: false,
            } => Ok(507u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 2i32,
                persistent: true,
                waterlogged: true,
            } => Ok(508u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 2i32,
                persistent: true,
                waterlogged: false,
            } => Ok(509u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 2i32,
                persistent: false,
                waterlogged: true,
            } => Ok(510u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 2i32,
                persistent: false,
                waterlogged: false,
            } => Ok(511u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 3i32,
                persistent: true,
                waterlogged: true,
            } => Ok(512u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 3i32,
                persistent: true,
                waterlogged: false,
            } => Ok(513u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 3i32,
                persistent: false,
                waterlogged: true,
            } => Ok(514u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 3i32,
                persistent: false,
                waterlogged: false,
            } => Ok(515u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 4i32,
                persistent: true,
                waterlogged: true,
            } => Ok(516u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 4i32,
                persistent: true,
                waterlogged: false,
            } => Ok(517u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 4i32,
                persistent: false,
                waterlogged: true,
            } => Ok(518u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 4i32,
                persistent: false,
                waterlogged: false,
            } => Ok(519u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 5i32,
                persistent: true,
                waterlogged: true,
            } => Ok(520u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 5i32,
                persistent: true,
                waterlogged: false,
            } => Ok(521u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 5i32,
                persistent: false,
                waterlogged: true,
            } => Ok(522u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 5i32,
                persistent: false,
                waterlogged: false,
            } => Ok(523u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 6i32,
                persistent: true,
                waterlogged: true,
            } => Ok(524u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 6i32,
                persistent: true,
                waterlogged: false,
            } => Ok(525u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 6i32,
                persistent: false,
                waterlogged: true,
            } => Ok(526u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 6i32,
                persistent: false,
                waterlogged: false,
            } => Ok(527u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 7i32,
                persistent: true,
                waterlogged: true,
            } => Ok(528u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 7i32,
                persistent: true,
                waterlogged: false,
            } => Ok(529u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 7i32,
                persistent: false,
                waterlogged: true,
            } => Ok(530u32),
            LeavesBlock {
                block_type: LeavesBlockType::AzaleaLeaves,
                distance: 7i32,
                persistent: false,
                waterlogged: false,
            } => Ok(531u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 1i32,
                persistent: true,
                waterlogged: true,
            } => Ok(308u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 1i32,
                persistent: true,
                waterlogged: false,
            } => Ok(309u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 1i32,
                persistent: false,
                waterlogged: true,
            } => Ok(310u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 1i32,
                persistent: false,
                waterlogged: false,
            } => Ok(311u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 2i32,
                persistent: true,
                waterlogged: true,
            } => Ok(312u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 2i32,
                persistent: true,
                waterlogged: false,
            } => Ok(313u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 2i32,
                persistent: false,
                waterlogged: true,
            } => Ok(314u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 2i32,
                persistent: false,
                waterlogged: false,
            } => Ok(315u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 3i32,
                persistent: true,
                waterlogged: true,
            } => Ok(316u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 3i32,
                persistent: true,
                waterlogged: false,
            } => Ok(317u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 3i32,
                persistent: false,
                waterlogged: true,
            } => Ok(318u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 3i32,
                persistent: false,
                waterlogged: false,
            } => Ok(319u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 4i32,
                persistent: true,
                waterlogged: true,
            } => Ok(320u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 4i32,
                persistent: true,
                waterlogged: false,
            } => Ok(321u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 4i32,
                persistent: false,
                waterlogged: true,
            } => Ok(322u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 4i32,
                persistent: false,
                waterlogged: false,
            } => Ok(323u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 5i32,
                persistent: true,
                waterlogged: true,
            } => Ok(324u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 5i32,
                persistent: true,
                waterlogged: false,
            } => Ok(325u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 5i32,
                persistent: false,
                waterlogged: true,
            } => Ok(326u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 5i32,
                persistent: false,
                waterlogged: false,
            } => Ok(327u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 6i32,
                persistent: true,
                waterlogged: true,
            } => Ok(328u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 6i32,
                persistent: true,
                waterlogged: false,
            } => Ok(329u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 6i32,
                persistent: false,
                waterlogged: true,
            } => Ok(330u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 6i32,
                persistent: false,
                waterlogged: false,
            } => Ok(331u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 7i32,
                persistent: true,
                waterlogged: true,
            } => Ok(332u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 7i32,
                persistent: true,
                waterlogged: false,
            } => Ok(333u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 7i32,
                persistent: false,
                waterlogged: true,
            } => Ok(334u32),
            LeavesBlock {
                block_type: LeavesBlockType::BirchLeaves,
                distance: 7i32,
                persistent: false,
                waterlogged: false,
            } => Ok(335u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 1i32,
                persistent: true,
                waterlogged: true,
            } => Ok(392u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 1i32,
                persistent: true,
                waterlogged: false,
            } => Ok(393u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 1i32,
                persistent: false,
                waterlogged: true,
            } => Ok(394u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 1i32,
                persistent: false,
                waterlogged: false,
            } => Ok(395u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 2i32,
                persistent: true,
                waterlogged: true,
            } => Ok(396u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 2i32,
                persistent: true,
                waterlogged: false,
            } => Ok(397u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 2i32,
                persistent: false,
                waterlogged: true,
            } => Ok(398u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 2i32,
                persistent: false,
                waterlogged: false,
            } => Ok(399u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 3i32,
                persistent: true,
                waterlogged: true,
            } => Ok(400u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 3i32,
                persistent: true,
                waterlogged: false,
            } => Ok(401u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 3i32,
                persistent: false,
                waterlogged: true,
            } => Ok(402u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 3i32,
                persistent: false,
                waterlogged: false,
            } => Ok(403u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 4i32,
                persistent: true,
                waterlogged: true,
            } => Ok(404u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 4i32,
                persistent: true,
                waterlogged: false,
            } => Ok(405u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 4i32,
                persistent: false,
                waterlogged: true,
            } => Ok(406u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 4i32,
                persistent: false,
                waterlogged: false,
            } => Ok(407u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 5i32,
                persistent: true,
                waterlogged: true,
            } => Ok(408u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 5i32,
                persistent: true,
                waterlogged: false,
            } => Ok(409u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 5i32,
                persistent: false,
                waterlogged: true,
            } => Ok(410u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 5i32,
                persistent: false,
                waterlogged: false,
            } => Ok(411u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 6i32,
                persistent: true,
                waterlogged: true,
            } => Ok(412u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 6i32,
                persistent: true,
                waterlogged: false,
            } => Ok(413u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 6i32,
                persistent: false,
                waterlogged: true,
            } => Ok(414u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 6i32,
                persistent: false,
                waterlogged: false,
            } => Ok(415u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 7i32,
                persistent: true,
                waterlogged: true,
            } => Ok(416u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 7i32,
                persistent: true,
                waterlogged: false,
            } => Ok(417u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 7i32,
                persistent: false,
                waterlogged: true,
            } => Ok(418u32),
            LeavesBlock {
                block_type: LeavesBlockType::CherryLeaves,
                distance: 7i32,
                persistent: false,
                waterlogged: false,
            } => Ok(419u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 1i32,
                persistent: true,
                waterlogged: true,
            } => Ok(420u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 1i32,
                persistent: true,
                waterlogged: false,
            } => Ok(421u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 1i32,
                persistent: false,
                waterlogged: true,
            } => Ok(422u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 1i32,
                persistent: false,
                waterlogged: false,
            } => Ok(423u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 2i32,
                persistent: true,
                waterlogged: true,
            } => Ok(424u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 2i32,
                persistent: true,
                waterlogged: false,
            } => Ok(425u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 2i32,
                persistent: false,
                waterlogged: true,
            } => Ok(426u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 2i32,
                persistent: false,
                waterlogged: false,
            } => Ok(427u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 3i32,
                persistent: true,
                waterlogged: true,
            } => Ok(428u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 3i32,
                persistent: true,
                waterlogged: false,
            } => Ok(429u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 3i32,
                persistent: false,
                waterlogged: true,
            } => Ok(430u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 3i32,
                persistent: false,
                waterlogged: false,
            } => Ok(431u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 4i32,
                persistent: true,
                waterlogged: true,
            } => Ok(432u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 4i32,
                persistent: true,
                waterlogged: false,
            } => Ok(433u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 4i32,
                persistent: false,
                waterlogged: true,
            } => Ok(434u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 4i32,
                persistent: false,
                waterlogged: false,
            } => Ok(435u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 5i32,
                persistent: true,
                waterlogged: true,
            } => Ok(436u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 5i32,
                persistent: true,
                waterlogged: false,
            } => Ok(437u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 5i32,
                persistent: false,
                waterlogged: true,
            } => Ok(438u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 5i32,
                persistent: false,
                waterlogged: false,
            } => Ok(439u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 6i32,
                persistent: true,
                waterlogged: true,
            } => Ok(440u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 6i32,
                persistent: true,
                waterlogged: false,
            } => Ok(441u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 6i32,
                persistent: false,
                waterlogged: true,
            } => Ok(442u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 6i32,
                persistent: false,
                waterlogged: false,
            } => Ok(443u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 7i32,
                persistent: true,
                waterlogged: true,
            } => Ok(444u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 7i32,
                persistent: true,
                waterlogged: false,
            } => Ok(445u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 7i32,
                persistent: false,
                waterlogged: true,
            } => Ok(446u32),
            LeavesBlock {
                block_type: LeavesBlockType::DarkOakLeaves,
                distance: 7i32,
                persistent: false,
                waterlogged: false,
            } => Ok(447u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 1i32,
                persistent: true,
                waterlogged: true,
            } => Ok(532u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 1i32,
                persistent: true,
                waterlogged: false,
            } => Ok(533u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 1i32,
                persistent: false,
                waterlogged: true,
            } => Ok(534u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 1i32,
                persistent: false,
                waterlogged: false,
            } => Ok(535u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 2i32,
                persistent: true,
                waterlogged: true,
            } => Ok(536u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 2i32,
                persistent: true,
                waterlogged: false,
            } => Ok(537u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 2i32,
                persistent: false,
                waterlogged: true,
            } => Ok(538u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 2i32,
                persistent: false,
                waterlogged: false,
            } => Ok(539u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 3i32,
                persistent: true,
                waterlogged: true,
            } => Ok(540u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 3i32,
                persistent: true,
                waterlogged: false,
            } => Ok(541u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 3i32,
                persistent: false,
                waterlogged: true,
            } => Ok(542u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 3i32,
                persistent: false,
                waterlogged: false,
            } => Ok(543u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 4i32,
                persistent: true,
                waterlogged: true,
            } => Ok(544u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 4i32,
                persistent: true,
                waterlogged: false,
            } => Ok(545u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 4i32,
                persistent: false,
                waterlogged: true,
            } => Ok(546u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 4i32,
                persistent: false,
                waterlogged: false,
            } => Ok(547u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 5i32,
                persistent: true,
                waterlogged: true,
            } => Ok(548u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 5i32,
                persistent: true,
                waterlogged: false,
            } => Ok(549u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 5i32,
                persistent: false,
                waterlogged: true,
            } => Ok(550u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 5i32,
                persistent: false,
                waterlogged: false,
            } => Ok(551u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 6i32,
                persistent: true,
                waterlogged: true,
            } => Ok(552u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 6i32,
                persistent: true,
                waterlogged: false,
            } => Ok(553u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 6i32,
                persistent: false,
                waterlogged: true,
            } => Ok(554u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 6i32,
                persistent: false,
                waterlogged: false,
            } => Ok(555u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 7i32,
                persistent: true,
                waterlogged: true,
            } => Ok(556u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 7i32,
                persistent: true,
                waterlogged: false,
            } => Ok(557u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 7i32,
                persistent: false,
                waterlogged: true,
            } => Ok(558u32),
            LeavesBlock {
                block_type: LeavesBlockType::FloweringAzaleaLeaves,
                distance: 7i32,
                persistent: false,
                waterlogged: false,
            } => Ok(559u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 1i32,
                persistent: true,
                waterlogged: true,
            } => Ok(336u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 1i32,
                persistent: true,
                waterlogged: false,
            } => Ok(337u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 1i32,
                persistent: false,
                waterlogged: true,
            } => Ok(338u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 1i32,
                persistent: false,
                waterlogged: false,
            } => Ok(339u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 2i32,
                persistent: true,
                waterlogged: true,
            } => Ok(340u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 2i32,
                persistent: true,
                waterlogged: false,
            } => Ok(341u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 2i32,
                persistent: false,
                waterlogged: true,
            } => Ok(342u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 2i32,
                persistent: false,
                waterlogged: false,
            } => Ok(343u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 3i32,
                persistent: true,
                waterlogged: true,
            } => Ok(344u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 3i32,
                persistent: true,
                waterlogged: false,
            } => Ok(345u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 3i32,
                persistent: false,
                waterlogged: true,
            } => Ok(346u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 3i32,
                persistent: false,
                waterlogged: false,
            } => Ok(347u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 4i32,
                persistent: true,
                waterlogged: true,
            } => Ok(348u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 4i32,
                persistent: true,
                waterlogged: false,
            } => Ok(349u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 4i32,
                persistent: false,
                waterlogged: true,
            } => Ok(350u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 4i32,
                persistent: false,
                waterlogged: false,
            } => Ok(351u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 5i32,
                persistent: true,
                waterlogged: true,
            } => Ok(352u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 5i32,
                persistent: true,
                waterlogged: false,
            } => Ok(353u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 5i32,
                persistent: false,
                waterlogged: true,
            } => Ok(354u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 5i32,
                persistent: false,
                waterlogged: false,
            } => Ok(355u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 6i32,
                persistent: true,
                waterlogged: true,
            } => Ok(356u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 6i32,
                persistent: true,
                waterlogged: false,
            } => Ok(357u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 6i32,
                persistent: false,
                waterlogged: true,
            } => Ok(358u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 6i32,
                persistent: false,
                waterlogged: false,
            } => Ok(359u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 7i32,
                persistent: true,
                waterlogged: true,
            } => Ok(360u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 7i32,
                persistent: true,
                waterlogged: false,
            } => Ok(361u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 7i32,
                persistent: false,
                waterlogged: true,
            } => Ok(362u32),
            LeavesBlock {
                block_type: LeavesBlockType::JungleLeaves,
                distance: 7i32,
                persistent: false,
                waterlogged: false,
            } => Ok(363u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 1i32,
                persistent: true,
                waterlogged: true,
            } => Ok(476u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 1i32,
                persistent: true,
                waterlogged: false,
            } => Ok(477u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 1i32,
                persistent: false,
                waterlogged: true,
            } => Ok(478u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 1i32,
                persistent: false,
                waterlogged: false,
            } => Ok(479u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 2i32,
                persistent: true,
                waterlogged: true,
            } => Ok(480u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 2i32,
                persistent: true,
                waterlogged: false,
            } => Ok(481u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 2i32,
                persistent: false,
                waterlogged: true,
            } => Ok(482u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 2i32,
                persistent: false,
                waterlogged: false,
            } => Ok(483u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 3i32,
                persistent: true,
                waterlogged: true,
            } => Ok(484u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 3i32,
                persistent: true,
                waterlogged: false,
            } => Ok(485u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 3i32,
                persistent: false,
                waterlogged: true,
            } => Ok(486u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 3i32,
                persistent: false,
                waterlogged: false,
            } => Ok(487u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 4i32,
                persistent: true,
                waterlogged: true,
            } => Ok(488u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 4i32,
                persistent: true,
                waterlogged: false,
            } => Ok(489u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 4i32,
                persistent: false,
                waterlogged: true,
            } => Ok(490u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 4i32,
                persistent: false,
                waterlogged: false,
            } => Ok(491u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 5i32,
                persistent: true,
                waterlogged: true,
            } => Ok(492u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 5i32,
                persistent: true,
                waterlogged: false,
            } => Ok(493u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 5i32,
                persistent: false,
                waterlogged: true,
            } => Ok(494u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 5i32,
                persistent: false,
                waterlogged: false,
            } => Ok(495u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 6i32,
                persistent: true,
                waterlogged: true,
            } => Ok(496u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 6i32,
                persistent: true,
                waterlogged: false,
            } => Ok(497u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 6i32,
                persistent: false,
                waterlogged: true,
            } => Ok(498u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 6i32,
                persistent: false,
                waterlogged: false,
            } => Ok(499u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 7i32,
                persistent: true,
                waterlogged: true,
            } => Ok(500u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 7i32,
                persistent: true,
                waterlogged: false,
            } => Ok(501u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 7i32,
                persistent: false,
                waterlogged: true,
            } => Ok(502u32),
            LeavesBlock {
                block_type: LeavesBlockType::MangroveLeaves,
                distance: 7i32,
                persistent: false,
                waterlogged: false,
            } => Ok(503u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 1i32,
                persistent: true,
                waterlogged: true,
            } => Ok(252u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 1i32,
                persistent: true,
                waterlogged: false,
            } => Ok(253u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 1i32,
                persistent: false,
                waterlogged: true,
            } => Ok(254u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 1i32,
                persistent: false,
                waterlogged: false,
            } => Ok(255u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 2i32,
                persistent: true,
                waterlogged: true,
            } => Ok(256u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 2i32,
                persistent: true,
                waterlogged: false,
            } => Ok(257u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 2i32,
                persistent: false,
                waterlogged: true,
            } => Ok(258u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 2i32,
                persistent: false,
                waterlogged: false,
            } => Ok(259u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 3i32,
                persistent: true,
                waterlogged: true,
            } => Ok(260u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 3i32,
                persistent: true,
                waterlogged: false,
            } => Ok(261u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 3i32,
                persistent: false,
                waterlogged: true,
            } => Ok(262u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 3i32,
                persistent: false,
                waterlogged: false,
            } => Ok(263u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 4i32,
                persistent: true,
                waterlogged: true,
            } => Ok(264u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 4i32,
                persistent: true,
                waterlogged: false,
            } => Ok(265u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 4i32,
                persistent: false,
                waterlogged: true,
            } => Ok(266u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 4i32,
                persistent: false,
                waterlogged: false,
            } => Ok(267u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 5i32,
                persistent: true,
                waterlogged: true,
            } => Ok(268u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 5i32,
                persistent: true,
                waterlogged: false,
            } => Ok(269u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 5i32,
                persistent: false,
                waterlogged: true,
            } => Ok(270u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 5i32,
                persistent: false,
                waterlogged: false,
            } => Ok(271u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 6i32,
                persistent: true,
                waterlogged: true,
            } => Ok(272u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 6i32,
                persistent: true,
                waterlogged: false,
            } => Ok(273u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 6i32,
                persistent: false,
                waterlogged: true,
            } => Ok(274u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 6i32,
                persistent: false,
                waterlogged: false,
            } => Ok(275u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 7i32,
                persistent: true,
                waterlogged: true,
            } => Ok(276u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 7i32,
                persistent: true,
                waterlogged: false,
            } => Ok(277u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 7i32,
                persistent: false,
                waterlogged: true,
            } => Ok(278u32),
            LeavesBlock {
                block_type: LeavesBlockType::OakLeaves,
                distance: 7i32,
                persistent: false,
                waterlogged: false,
            } => Ok(279u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 1i32,
                persistent: true,
                waterlogged: true,
            } => Ok(448u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 1i32,
                persistent: true,
                waterlogged: false,
            } => Ok(449u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 1i32,
                persistent: false,
                waterlogged: true,
            } => Ok(450u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 1i32,
                persistent: false,
                waterlogged: false,
            } => Ok(451u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 2i32,
                persistent: true,
                waterlogged: true,
            } => Ok(452u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 2i32,
                persistent: true,
                waterlogged: false,
            } => Ok(453u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 2i32,
                persistent: false,
                waterlogged: true,
            } => Ok(454u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 2i32,
                persistent: false,
                waterlogged: false,
            } => Ok(455u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 3i32,
                persistent: true,
                waterlogged: true,
            } => Ok(456u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 3i32,
                persistent: true,
                waterlogged: false,
            } => Ok(457u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 3i32,
                persistent: false,
                waterlogged: true,
            } => Ok(458u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 3i32,
                persistent: false,
                waterlogged: false,
            } => Ok(459u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 4i32,
                persistent: true,
                waterlogged: true,
            } => Ok(460u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 4i32,
                persistent: true,
                waterlogged: false,
            } => Ok(461u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 4i32,
                persistent: false,
                waterlogged: true,
            } => Ok(462u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 4i32,
                persistent: false,
                waterlogged: false,
            } => Ok(463u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 5i32,
                persistent: true,
                waterlogged: true,
            } => Ok(464u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 5i32,
                persistent: true,
                waterlogged: false,
            } => Ok(465u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 5i32,
                persistent: false,
                waterlogged: true,
            } => Ok(466u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 5i32,
                persistent: false,
                waterlogged: false,
            } => Ok(467u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 6i32,
                persistent: true,
                waterlogged: true,
            } => Ok(468u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 6i32,
                persistent: true,
                waterlogged: false,
            } => Ok(469u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 6i32,
                persistent: false,
                waterlogged: true,
            } => Ok(470u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 6i32,
                persistent: false,
                waterlogged: false,
            } => Ok(471u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 7i32,
                persistent: true,
                waterlogged: true,
            } => Ok(472u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 7i32,
                persistent: true,
                waterlogged: false,
            } => Ok(473u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 7i32,
                persistent: false,
                waterlogged: true,
            } => Ok(474u32),
            LeavesBlock {
                block_type: LeavesBlockType::PaleOakLeaves,
                distance: 7i32,
                persistent: false,
                waterlogged: false,
            } => Ok(475u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 1i32,
                persistent: true,
                waterlogged: true,
            } => Ok(280u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 1i32,
                persistent: true,
                waterlogged: false,
            } => Ok(281u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 1i32,
                persistent: false,
                waterlogged: true,
            } => Ok(282u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 1i32,
                persistent: false,
                waterlogged: false,
            } => Ok(283u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 2i32,
                persistent: true,
                waterlogged: true,
            } => Ok(284u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 2i32,
                persistent: true,
                waterlogged: false,
            } => Ok(285u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 2i32,
                persistent: false,
                waterlogged: true,
            } => Ok(286u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 2i32,
                persistent: false,
                waterlogged: false,
            } => Ok(287u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 3i32,
                persistent: true,
                waterlogged: true,
            } => Ok(288u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 3i32,
                persistent: true,
                waterlogged: false,
            } => Ok(289u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 3i32,
                persistent: false,
                waterlogged: true,
            } => Ok(290u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 3i32,
                persistent: false,
                waterlogged: false,
            } => Ok(291u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 4i32,
                persistent: true,
                waterlogged: true,
            } => Ok(292u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 4i32,
                persistent: true,
                waterlogged: false,
            } => Ok(293u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 4i32,
                persistent: false,
                waterlogged: true,
            } => Ok(294u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 4i32,
                persistent: false,
                waterlogged: false,
            } => Ok(295u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 5i32,
                persistent: true,
                waterlogged: true,
            } => Ok(296u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 5i32,
                persistent: true,
                waterlogged: false,
            } => Ok(297u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 5i32,
                persistent: false,
                waterlogged: true,
            } => Ok(298u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 5i32,
                persistent: false,
                waterlogged: false,
            } => Ok(299u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 6i32,
                persistent: true,
                waterlogged: true,
            } => Ok(300u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 6i32,
                persistent: true,
                waterlogged: false,
            } => Ok(301u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 6i32,
                persistent: false,
                waterlogged: true,
            } => Ok(302u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 6i32,
                persistent: false,
                waterlogged: false,
            } => Ok(303u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 7i32,
                persistent: true,
                waterlogged: true,
            } => Ok(304u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 7i32,
                persistent: true,
                waterlogged: false,
            } => Ok(305u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 7i32,
                persistent: false,
                waterlogged: true,
            } => Ok(306u32),
            LeavesBlock {
                block_type: LeavesBlockType::SpruceLeaves,
                distance: 7i32,
                persistent: false,
                waterlogged: false,
            } => Ok(307u32),
            _ => Err(()),
        }
    }
}
